import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'zh' | 'zh-TW' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'zh' || saved === 'zh-TW' || saved === 'en') ? saved : 'zh';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  zh: {
    header: {
      tagline: '专为海外华人设计',
      taglineEn: 'Built for Chinese Abroad',
      home: '首页',
      homeEn: 'Home',
      features: '产品特色',
      featuresEn: 'Features',
      pricing: '套餐价格',
      pricingEn: 'Pricing',
      download: '下载客户端',
      downloadEn: 'Download',
      contact: '联系我们',
      contactEn: 'Contact',
      login: '登录',
      freeTrial: '免费试用',
      accountManagement: '账号管理',
      logout: '退出登录'
    },
    hero: {
      title: '倦鸟归巢 一键回国',
      subtitle: '专业的回国网络加速服务，让海外华人轻松访问国内网络资源',
      badge: '高速稳定 • 安全可靠 • 一键连接',
      security: '企业级安全',
      securityEn: 'Enterprise Security',
      latency: '毫秒级延迟',
      latencyEn: 'Ultra Low Latency',
      network: '全球节点',
      networkEn: 'Global Network',
      startTrial: '立即免费试用',
      downloadClient: '下载客户端',
      windows: 'Windows',
      windowsDesc: 'PC客户端',
      macos: 'macOS',
      macosDesc: 'Mac客户端',
      ios: 'iOS',
      iosDesc: 'iPhone/iPad',
      android: 'Android',
      androidDesc: '安卓手机',
      browser: '浏览器',
      browserDesc: 'Chrome插件',
      clickDownload: '点击下载'
    },
    features: {
      badge: '⚡ 产品特色',
      title: '为什么选择',
      titleBrand: '归巢',
      subtitle: '专为海外华人打造的回国网络解决方案，让您在海外也能无缝享受国内的网络服务',
      speed: '极速连接',
      speedDesc: '采用最新加速技术，连接速度提升300%，观看4K视频无缓冲',
      speedHighlight: '毫秒级延迟',
      encryption: '军用级加密',
      encryptionDesc: 'AES-256位加密技术，保护您的网络安全和隐私数据',
      encryptionHighlight: '银行级安全',
      nodes: '全球节点',
      nodesDesc: '覆盖全球50+城市，智能选择最优线路，确保连接稳定',
      nodesHighlight: '50+节点',
      devices: '多设备支持',
      devicesDesc: '一个账户支持10台设备同时使用，全家共享无忧',
      devicesHighlight: '10台设备',
      uptime: '7x24在线',
      uptimeDesc: '99.9%服务可用性，全年无休为您提供稳定的网络服务',
      uptimeHighlight: '99.9%稳定',
      support: '专业客服',
      supportDesc: '中文技术支持团队，微信群实时答疑，问题快速解决',
      supportHighlight: '中文支持',
      stat1: '1M+',
      stat1Label: '用户信赖',
      stat1En: 'Active Users',
      stat2: '50+',
      stat2Label: '全球节点',
      stat2En: 'Global Nodes',
      stat3: '99.9%',
      stat3Label: '稳定运行',
      stat3En: 'Uptime SLA',
      stat4: '24/7',
      stat4Label: '技术支持',
      stat4En: 'Support'
    },
    scenarios: {
      title: '支持加速多种场景',
      subtitle: '无论是娱乐、学习还是工作，归巢为您提供全方位的加速支持',
      video: '影音娱乐',
      videoDesc: '流畅观看国内视频平台，享受高清流媒体',
      sports: '体育赛事',
      sportsDesc: '实时观看大陆体育赛事直播，不错过精彩瞬间',
      gaming: '国服游戏',
      gamingDesc: '降低游戏延迟，畅玩国服热门游戏',
      education: '远程学习',
      educationDesc: '稳定连接大陆教育平台，在线学习无忧',
      meeting: '办公会议',
      meetingDesc: '高效跨境视频会议，团队协作更流畅',
      streaming: '达人直播',
      streamingDesc: '高清流畅直播推流，内容创作更专业'
    },
    pricing: {
      badge: '💰 套餐价格',
      title: '选择适合您的',
      titleBrand: '套餐',
      subtitle: '灵活的价格方案，满足不同用户需求。支持微信、支付宝、USDT等多种支付方式',
      discount: '🎉 年付用户享8折优惠，可节省高达HK$140',
      popular: '🔥 最受欢迎',
      trial: '体验版',
      trialDesc: '新用户专享，体验归巢服务',
      trialPrice: '免费',
      trialPeriod: '3天试用',
      trialButton: '立即试用',
      standard: '标准版',
      standardDesc: '个人用户推荐，性价比之选',
      standardButton: '选择标准版',
      premium: '旗舰版',
      premiumDesc: '家庭/企业用户首选',
      premiumButton: '选择旗舰版',
      selectPlan: '点击选择',
      guarantee1: '7天无忧退款',
      guarantee1Desc: '不满意随时退款',
      guarantee2: '24小时客服',
      guarantee2Desc: '随时为您解答问题',
      guarantee3: '无限流量',
      guarantee3Desc: '畅享高速网络体验',
      paymentTitle: '选择支付方式',
      paymentSecurity: '支付过程安全加密，支持7天无忧退款',
      cancel: '取消',
      wechat: '微信支付',
      wechatDesc: '使用微信快速支付',
      alipayHK: '香港支付宝',
      alipayHKDesc: '支付宝(香港)便捷支付',
      paypal: 'PayPal',
      paypalDesc: '全球通用在线支付',
      googlePay: 'Google Pay',
      googlePayDesc: 'Google 快速支付',
      applePay: 'Apple Pay',
      applePayDesc: 'Apple 设备专用支付',
      stripe: 'Stripe',
      stripeDesc: '信用卡/借记卡支付'
    },
    footer: {
      brand: '专为海外华人打造的回国网络加速服务，让您在海外也能无缝享受国内的网络体验。',
      wechatGroup: '微信群',
      email: '邮箱',
      products: '产品服务',
      features: '产品特色',
      pricing: '套餐价格',
      freeTrial: '免费试用',
      nodeStatus: '节点状态',
      speedTest: '速度测试',
      download: '客户端下载',
      windowsClient: 'Windows 客户端',
      macosClient: 'macOS 客户端',
      iosApp: 'iOS 应用',
      androidApp: 'Android 应用',
      webVersion: '网页版',
      support: '帮助支持',
      tutorial: '使用教程',
      faq: '常见问题',
      contactSupport: '联系客服',
      feedback: '意见反馈',
      terms: '服务条款',
      newsletter: '最新动态',
      emailPlaceholder: '输入邮箱地址',
      subscribe: '订阅',
      copyright: '© 2024 归巢 GuiChao.win. 保留所有权利。',
      privacy: '隐私政策',
      cookie: 'Cookie政策',
      research: '加速器技术研究',
      techBlog: '技术博客',
      whitepapers: '白皮书',
      caseStudies: '案例分析',
      networkOptimization: '网络优化',
      securityResearch: '安全研究',
      tagline: '专业的海外华人回国网络服务提供商 | 让距离不再是障碍',
      ownership: '本网页是属于 HK Guichao Technology Co., Limited所拥有和全权使用'
    },
    auth: {
      joinTitle: '加入',
      joinBrand: '归巢',
      subtitle: '专为海外华人打造的回国网络加速服务，让您在海外也能无缝享受国内的网络体验。',
      fastConnection: '极速连接',
      fastDesc: '毫秒级延迟，4K视频无缓冲',
      militaryEncryption: '军用级加密',
      encryptionDesc: 'AES-256位加密，保护隐私安全',
      globalNodes: '全球节点',
      nodesDesc: '覆盖50+城市，智能路由优化',
      review1: '"归巢真的太好用了！连接速度超快，看国内视频完全没问题。"',
      reviewer1: '- 来自美国的用户 张先生',
      review2: '"在海外工作需要经常查询企查查和天眼查，之前用国内手机流量又慢又贵。归巢完美解决了我的痛点，速度快、价格实惠，商务办公必备！"',
      reviewer2: '- 来自英国的用户 李女士',
      welcomeTitle: '欢迎使用归巢',
      welcomeDesc: '请登录或注册您的账号',
      login: '登录',
      register: '注册',
      email: '邮箱',
      emailPlaceholder: '请输入邮箱地址',
      password: '密码',
      passwordPlaceholder: '请输入密码',
      passwordPlaceholder6: '请设置密码（至少6位）',
      passwordPlaceholder8: '请输入密码（至少8位）',
      newPasswordPlaceholder: '请设置新密码（至少6位）',
      confirmPassword: '确认密码',
      confirmPasswordPlaceholder: '请再次输入密码',
      rememberMe: '记住我',
      forgotPassword: '忘记密码？',
      loggingIn: '登录中...',
      loginButton: '登录',
      registerButton: '注册账号',
      registering: '注册中...',
      agreeTerms1: '登录即表示您同意我们的',
      agreeTerms2: '服务条款',
      agreeTerms3: '和',
      agreeTerms4: '隐私协议',
      username: '用户名',
      usernamePlaceholder: '请输入用户名',
      readAgree: '我已阅读并同意',
      termsLink: '《服务条款》',
      privacyLink: '《隐私协议》',
      orDivider: '或',
      googleLogin: '使用 Google 登录',
      wechatLogin: '使用微信登录',
      // 登录方式
      emailLogin: '邮箱登录',
      phoneLogin: '手机号登录',
      otpLogin: '验证码登录',
      phone: '手机号',
      phonePlaceholder: '请输入手机号',
      otpPlaceholder: '请输入6位验证码',
      getOtp: '获取验证码',
      resendOtp: '重新发送',
      // 登录状态
      sendingOtp: '发送中...',
      verifying: '验证中...',
      resetting: '重置中...',
      nextStep: '下一步',
      // 注册
      phoneRegister: '手机号',
      emailRegister: '邮箱',
      // 忘记密码
      resetPassword: '重置密码',
      backToLogin: '返回登录',
      // 提示消息
      pleaseAgreeTerms: '请先同意服务条款',
      otpSent: '验证码已发送',
      checkSms: '请查看手机短信',
      checkEmail: '请查看邮箱',
      sendFailed: '发送失败',
      loginSuccess: '登录成功',
      verifyFailed: '验证失败',
      registerSuccess: '注册成功',
      resetSuccess: '密码重置成功',
      useNewPassword: '请使用新密码登录',
      resetFailed: '重置失败',
      phoneNotRegistered: '该手机号未注册',
      emailNotRegistered: '该邮箱未注册',
      pleaseRegisterFirst: '请先注册账号',
      cannotResetPassword: '无法重置密码，请先注册账号',
      passwordMinLength: '密码至少6个字符',
      invalidEmail: '请输入有效的邮箱地址',
      invalidPhone: '请输入有效的手机号码',
      otpLength: '验证码为6位数字'
    },
    download: {
      badge: '📱 客户端下载',
      title: '全平台',
      titleBrand: '客户端',
      subtitle: '支持Windows、macOS、iOS、Android等全平台，一个账号多设备同时使用',
      smartDownload: '智能下载',
      viewTutorial: '查看教程',
      downloadBtn: '下载',
      oneClickConnect: '一键连接',
      smartRouting: '智能路由',
      autoStart: '开机自启',
      nativeSupport: '原生支持',
      menubarControl: '菜单栏控制',
      systemIntegration: '系统集成',
      appStore: 'App Store 下载',
      shortcuts: '快捷指令',
      siriSupport: 'Siri 支持',
      googlePlay: 'Google Play',
      oneClickShare: '一键分享',
      powerSaving: '省电模式',
      routerFirmware: '路由器固件',
      familyShare: '全家共享',
      deviceControl: '设备管控',
      timedSwitch: '定时开关',
      browserExtension: '浏览器插件',
      freeUse: '免费使用',
      webProxy: '网页代理',
      smartSplit: '智能分流',
      tutorialTitle: '使用',
      tutorialBrand: '教程',
      tutorialSubtitle: '简单几步，快速上手',
      windowsTutorial: 'Windows',
      windowsStep1: '下载并运行安装程序',
      windowsStep2: '按照向导完成安装',
      windowsStep3: '使用账号密码登录',
      windowsStep4: '选择节点并点击连接',
      mobileTutorial: '手机客户端',
      mobileStep1: '从应用商店下载应用',
      mobileStep2: '注册或登录账号',
      mobileStep3: '允许VPN配置权限',
      mobileStep4: '选择服务器开始连接',
      routerTutorial: '路由器',
      routerStep1: '备份原固件设置',
      routerStep2: '刷入归巢专用固件',
      routerStep3: '配置网络连接参数',
      routerStep4: '设置设备访问控制',
      helpTitle: '需要',
      helpBrand: '帮助？',
      helpSubtitle: '我们的技术支持团队随时为您提供帮助',
      downloadIssues: '下载问题',
      downloadIssuesDesc: '下载失败、安装错误等问题',
      tutorialGuide: '使用教程',
      tutorialGuideDesc: '详细的图文和视频教程',
      support247: '24/7客服',
      support247Desc: '全天候在线技术支持',
      contactSupport: '联系客服'
    },
    notFound: {
      title: '页面',
      titleBrand: '走丢了',
      subtitle: '抱歉，您访问的页面不存在或已被移动',
      backHome: '返回首页',
      hint: '或者您可以尝试使用导航菜单找到您需要的内容'
    },
    privacy: {
      title: '隐私政策',
      subtitle: '归巢 GuiChao 深知个人信息对您的重要性，我们将按照法律法规的要求，采取相应安全保护措施，尽力保护您的个人信息安全可控。',
      updateDate: '更新日期：2024年12月30日',
      effectiveDate: '生效日期：2024年12月30日',
      importantTitle: '特别提示',
      importantText: '请您仔细阅读本《归巢隐私政策》（尤其是加粗的内容）并确定了解我们对您个人信息的处理规则。在阅读过程中，如您有任何疑问，可通过本政策中约定的联系方式与我们联系。如您不同意本协议中的任何条款，您应立即停止访问和使用归巢服务。',
      tocTitle: '目录',
      section1: '一、我们如何收集和使用您的个人信息',
      section2: '二、我们如何使用 Cookie 和同类技术',
      section3: '三、我们如何共享、转让、公开披露您的个人信息',
      section4: '四、我们如何存储和保护您的个人信息',
      section5: '五、您管理个人信息的权利',
      section6: '六、未成年人个人信息的保护',
      section7: '七、隐私政策的变更和修订',
      section8: '八、如何联系我们',
      introPara1: '归巢（GuiChao）由 HK Guichao Technology Co., Limited 开发和运营。我们尊重并保护所有使用服务用户的个人信息，并将按照法律法规的规定保护用户信息及隐私安全。我们致力于维持您对我们的信任，恪守以下原则保护您的个人信息：权责一致原则、目的明确原则、选择同意原则、最少够用原则、确保安全原则、主体参与原则、公开透明原则等。',
      introPara2: '请您在使用我们的产品和服务前，仔细阅读并了解本隐私政策。一旦您开始使用归巢服务，即表示您已充分理解并同意本政策。',
      s1h1: '1.1 账号注册与登录',
      s1p1: '当您注册归巢账号时，我们会收集您的手机号码、邮箱地址、密码等信息，用于创建账号和验证您的身份。您可以选择通过第三方账号（如微信、Apple ID）登录，我们将在获得您授权后收集您的昵称、头像等公开信息。',
      s1h2: '1.2 网络加速服务',
      s1p2: '为了向您提供网络加速服务，我们需要收集您的设备信息（设备型号、操作系统版本、设备标识符）、网络信息（IP地址、网络类型、网络状态）、连接日志等。这些信息用于优化服务质量、诊断网络问题和保障服务安全。',
      s1h3: '1.3 支付功能',
      s1p3: '当您购买我们的付费服务时，我们可能会收集您的支付信息，包括第三方支付账号（支付宝、微信支付、Apple Pay等）。支付信息由第三方支付机构收集和处理，我们仅保存必要的订单信息。',
      s1h4: '1.4 客户服务',
      s1p4: '当您联系我们的客户服务时，我们可能会收集您的联系方式、问题描述、聊天记录等，以便为您提供支持和解决问题。',
      s1h5: '1.5 征得授权同意的例外',
      s1p5: '根据相关法律法规规定，以下情形中收集您的个人信息无需征得您的授权同意：',
      s1l1: '与国家安全、国防安全直接相关的',
      s1l2: '与公共安全、公共卫生、重大公共利益直接相关的',
      s1l3: '与犯罪侦查、起诉、审判和判决执行等直接相关的',
      s1l4: '出于维护您或其他个人的生命、财产等重大合法权益但又很难得到本人同意的',
      s1l5: '您自行向社会公众公开的个人信息',
      s1l6: '从合法公开披露的信息中收集的个人信息',
      s2p1: '为确保网站正常运转、为您获得更轻松的访问体验、向您推荐您可能感兴趣的内容，我们会在您的设备上存储名为 Cookie 的小数据文件。Cookie 通常包含标识符、站点名称以及一些号码和字符。',
      s2h1: 'Cookie 的主要用途：',
      s2l1: '保障产品与服务的安全、高效运转：我们可能会设置认证与保障安全性的 Cookie，使您避免重复登录',
      s2l2: '帮助您获得更轻松的访问体验：使用 Cookie 可以帮助您省去重复填写信息、输入搜索内容的步骤',
      s2l3: '为您推荐、展示个性化内容：我们可能会利用 Cookie 了解您的偏好和使用习惯，进行数据分析，以改善产品服务、推荐个性化内容',
      s2p2: '您可以通过浏览器设置管理或删除 Cookie。但如果您这么做，可能需要在每次访问时亲自更改用户设置，并且您之前所记录的相应信息也均会被删除，可能会对您使用的服务的安全性有一定影响。',
      s3h1: '3.1 共享',
      s3p1: '我们不会与任何公司、组织和个人共享您的个人信息，但以下情况除外：',
      s3l1: '在获取明确同意的情况下共享：获得您的明确同意后，我们会与其他方共享您的个人信息',
      s3l2: '在法定情形下的共享：根据法律法规、诉讼、争议解决需要，或按行政、司法机关依法提出的要求，我们可能会共享您的个人信息',
      s3l3: '与关联公司共享：为便于我们向您提供服务，您的个人信息可能会与我们的关联公司共享',
      s3l4: '与授权合作伙伴共享：仅为实现本政策中声明的目的，我们的某些服务将由授权合作伙伴提供。我们可能会与合作伙伴共享您的某些个人信息',
      s3h2: '3.2 转让',
      s3p2: '我们不会将您的个人信息转让给任何公司、组织和个人，但以下情况除外：在获取明确同意的情况下转让；在涉及合并、收购或破产清算时，如涉及到个人信息转让，我们会要求新的持有您个人信息的公司、组织继续受本政策的约束。',
      s3h3: '3.3 公开披露',
      s3p3: '我们仅会在以下情况下，公开披露您的个人信息：获得您明确同意后；基于法律的披露：在法律、法律程序、诉讼或政府主管部门强制性要求的情况下，我们可能会公开披露您的个人信息。',
      s4h1: '4.1 信息存储',
      s4p1: '您的个人信息将存储于中华人民共和国境内。如需跨境传输，我们将会单独征得您的授权同意，并确保数据接收方有充足的数据保护能力来保护您的个人信息。我们只会在达成本政策所述目的所需的期限内保留您的个人信息，除非法律有强制的存留要求。',
      s4h2: '4.2 信息安全',
      s4p2: '我们努力为用户的信息安全提供保障，以防止信息的丢失、不当使用、未经授权访问或披露。我们采取的安全措施包括：',
      s4l1: '我们使用各种安全技术以保障信息的安全。例如，我们会使用加密技术（如 SSL）来保护您的个人信息',
      s4l2: '我们建立专门的管理制度、流程和组织以保障信息的安全',
      s4l3: '我们对可能接触到您的信息的员工采取严格管理，包括采取不同的权限控制',
      s4l4: '我们会采取适当的符合业界标准的安全措施和技术手段存储和保护您的个人信息，以防止其丢失、被误用、受到未授权访问或泄漏、被篡改或毁坏',
      s4h3: '4.3 安全事件处置',
      s4p3: '在不幸发生个人信息安全事件后，我们将按照法律法规的要求，及时向您告知：安全事件的基本情况和可能的影响、我们已采取或将要采取的处置措施、您可自主防范和降低风险的建议、对您的补救措施等。我们将及时将事件相关情况以邮件、信函、电话、推送通知等方式告知您。',
      s5p1: '按照中国相关的法律、法规、标准，以及其他国家、地区的通行做法，我们保障您对自己的个人信息行使以下权利：',
      s5h1: '5.1 访问和更新您的个人信息',
      s5p2: '您有权访问和更新您的个人信息，法律法规规定的例外情况除外。您可以通过以下方式自行访问和更新您的个人信息：登录账号后，在"个人中心"查看和修改您的账号信息、个人资料等。',
      s5h2: '5.2 删除您的个人信息',
      s5p3: '在以下情形中，您可以向我们提出删除个人信息的请求：',
      s5l1: '如果我们处理个人信息的行为违反法律法规',
      s5l2: '如果我们收集、使用您的个人信息，却未征得您的同意',
      s5l3: '如果我们处理个人信息的行为违反了与您的约定',
      s5l4: '如果您注销了账号',
      s5h3: '5.3 注销账号',
      s5p4: '您可以通过联系客服的方式申请注销您的账号。在您注销账号后，我们将停止为您提供产品或服务，并根据您的要求删除您的个人信息，法律法规另有规定的除外。',
      s5h4: '5.4 撤回同意',
      s5p5: '您可以通过删除信息、关闭设备功能、在网站或软件中进行隐私设置等方式改变您授权我们继续收集个人信息的范围或撤回您的授权。您也可以通过注销账号的方式，撤回我们继续收集您个人信息的全部授权。',
      s5h5: '5.5 响应您的请求',
      s5p6: '为保障安全，您可能需要提供书面请求，或以其他方式证明您的身份。我们可能会先要求您验证自己的身份，然后再处理您的请求。我们将在15个工作日内做出答复。如您不满意，还可以通过本政策中的联系方式投诉。',
      s6p1: '我们非常重视对未成年人个人信息的保护。若您是18周岁以下的未成年人，在使用我们的产品和/或服务前，应事先取得您家长或法定监护人的书面同意。',
      s6p2: '我们根据国家相关法律法规的规定保护未成年人的个人信息。对于经父母或法定监护人同意而收集未成年人个人信息的情况，我们只会在受到法律允许、父母或监护人明确同意或者保护未成年人所必要的情况下使用或公开披露此信息。',
      s6p3: '如果我们发现自己在未事先获得可证实的父母或法定监护人同意的情况下收集了未成年人的个人信息，则会设法尽快删除相关数据。',
      s7p1: '为了给您提供更好的服务，我们可能会根据产品或服务的更新情况及法律法规的相关要求适时修改本政策的条款，该等修改构成本隐私政策的一部分。',
      s7p2: '如该等更新造成您在本隐私政策下权利的实质减少或重大变更，我们将在本政策生效前通过网站公告、推送通知、弹窗提示或其他方式来通知您，您如果不同意该等变更，可以选择停止使用我们的产品和服务；如您仍然继续使用我们的产品和服务，即表示您已充分阅读、理解并同意受经修订的本隐私政策的约束。',
      s7p3: '本政策所指的重大变更包括但不限于：',
      s7l1: '我们的服务模式发生重大变化',
      s7l2: '个人信息共享、转让或公开披露的主要对象发生变化',
      s7l3: '您参与个人信息处理方面的权利及其行使方式发生重大变化',
      s7l4: '我们负责处理个人信息安全的责任部门、联络方式及投诉渠道发生变化',
      s8p1: '如果您对本隐私政策有任何疑问、意见或建议，或您在使用我们的服务时遇到任何与个人信息保护相关的问题，您可以通过以下方式与我们联系：',
      s8p2: '一般情况下，我们将在15个工作日内回复。如果您对我们的回复不满意，特别是您认为我们的个人信息处理行为损害了您的合法权益，您还可以通过向被告住所地有管辖权的法院提起诉讼来寻求解决方案。',
      contactEmail: '电子邮件',
      companyName: '公司名称',
      thanksTitle: '再次感谢您对归巢的信任！',
      thanksText: '我们将竭诚为您提供安全、可靠的网络加速服务，并持续保护您的个人信息安全。'
    },
    cookie: {
      title: 'Cookie政策',
      lastUpdated: '最后更新日期：2024年1月',
      intro: '本Cookie政策说明AI智联加速器（"我们"或"本服务"）如何使用Cookie及类似技术来识别您访问我们的网站、应用程序和服务时的身份。本政策解释了这些技术是什么，我们为何使用它们，以及您如何控制它们的使用。',
      
      whatAreCookies: {
        title: '什么是Cookie？',
        content: 'Cookie是当您访问网站时放置在您的计算机或移动设备上的小型数据文件。网站所有者广泛使用Cookie来使其网站运行或更高效地运行，以及提供报告信息。网站所有者设置的Cookie称为"第一方Cookie"。由网站所有者以外的各方设置的Cookie称为"第三方Cookie"。第三方Cookie启用可在网站上或通过网站提供的第三方功能或功能（例如广告、交互式内容和分析）。设置这些第三方Cookie的各方可以在您的计算机访问相关网站以及访问某些其他网站时识别您的计算机。'
      },
      
      whyWeUseCookies: {
        title: '我们为什么使用Cookie？',
        content: '我们使用第一方和第三方Cookie的原因有多种。出于技术原因，我们的网站需要某些Cookie才能运行，我们将其称为"必需"或"绝对必要"Cookie。其他Cookie还使我们能够跟踪和定位用户的兴趣，以增强我们在线资产上的体验。第三方通过我们的网站提供Cookie，用于广告、分析和其他目的。'
      },
      
      typesOfCookies: {
        title: '我们使用的Cookie类型',
        essential: {
          title: '必需Cookie',
          description: '这些Cookie对于向您提供通过我们的网站可用的服务以及使用其某些功能（例如访问安全区域）是绝对必要的。由于这些Cookie对于向您提供服务是绝对必要的，因此您无法拒绝它们而不影响我们网站的功能。您可以通过更改浏览器设置来阻止或删除它们，但这可能会影响网站的某些功能。'
        },
        performance: {
          title: '性能和功能Cookie',
          description: '这些Cookie用于增强我们网站的性能和功能，但对其使用并非必不可少。但是，如果没有这些Cookie，某些功能（如视频）可能会变得不可用，或者您将需要每次访问网站时输入您的登录详细信息，因为我们无法记住您之前已登录。'
        },
        analytics: {
          title: '分析和定制Cookie',
          description: '这些Cookie收集用于汇总分析我们网站使用情况的信息，以便我们可以改善访问者体验。它们还允许我们测试新想法并监控和改善我们网站的性能。例如，我们使用这些Cookie来计算网站的访问者数量并查看访问者如何浏览网站。我们使用这些信息来改进我们网站的工作方式，例如，通过确保用户轻松找到所需内容。'
        },
        advertising: {
          title: '广告Cookie',
          description: '这些Cookie用于使广告信息与您更相关。它们执行诸如防止相同广告不断重新出现、确保广告正确显示给广告主以及在某些情况下根据您的兴趣选择广告等功能。'
        }
      },
      
      howToControl: {
        title: '如何控制Cookie？',
        content: '您有权决定是否接受或拒绝Cookie。您可以通过在Cookie同意管理器中设置您的首选项来行使您的Cookie权利。Cookie同意管理器允许您选择接受或拒绝哪些类别的Cookie。必需Cookie不能被拒绝，因为它们对于向您提供服务是绝对必要的。',
        browserSettings: '如果您选择拒绝Cookie，您仍可以使用我们的网站，但您对网站某些功能和区域的访问可能会受到限制。您还可以设置或修改Web浏览器控件以接受或拒绝Cookie。'
      },
      
      specificCookies: {
        title: '我们使用的具体Cookie',
        sessionCookies: '会话Cookie：这些Cookie在您浏览会话期间临时存储信息。它们在您关闭浏览器时被删除。',
        persistentCookies: '持久Cookie：这些Cookie在您的设备上保留更长时间，用于记住您的偏好设置和登录信息。',
        securityCookies: '安全Cookie：这些Cookie用于验证用户身份、防止欺诈性使用登录凭证，并保护用户数据免受未经授权方的侵害。'
      },
      
      thirdParty: {
        title: '第三方Cookie',
        content: '除了我们自己的Cookie之外，我们还可能使用各种第三方Cookie来报告我们网站的使用统计信息、投放广告等。这些第三方服务提供商可能会使用Cookie来收集您访问我们网站和其他网站的信息。我们不控制这些第三方Cookie，它们的使用受提供它们的公司的隐私政策约束。'
      },
      
      updates: {
        title: '本Cookie政策的更新',
        content: '我们可能会不时更新本Cookie政策，以反映我们使用的Cookie的更改或出于其他运营、法律或监管原因。因此，请定期重新访问本Cookie政策以了解我们对Cookie和相关技术的使用情况。本Cookie政策顶部的日期表示其最后更新时间。'
      },
      
      contact: {
        title: '联系我们',
        content: '如果您对我们使用Cookie或其他技术有任何疑问，请通过以下方式与我们联系：',
        email: '邮箱：support@ai-accelerator.com'
      }
    },
    terms: {
      title: '服务条款',
      lastUpdate: '最后更新日期：2024年1月',
      importantTitle: '重要提示',
      importantText: '在使用我们的服务之前，请仔细阅读并理解本服务条款。使用我们的服务即表示您同意接受本条款的约束。',
      section1Title: '1. 服务说明',
      s1p1: '我们提供的网络加速服务旨在优化您的网络连接体验。服务内容包括但不限于：',
      s1l1: '网络连接加速和优化',
      s1l2: '多节点服务器支持',
      s1l3: '数据传输加密',
      s1l4: '技术支持和客户服务',
      s1p2: '我们保留随时修改、暂停或终止部分或全部服务的权利，恕不另行通知。',
      section2Title: '2. 用户责任与义务',
      s2p1: '作为服务用户，您同意：',
      s2l1: '提供真实、准确的注册信息',
      s2l2: '妥善保管账户信息和密码',
      s2l3: '遵守所有适用的法律法规',
      s2l4: '不得将服务用于任何非法或未授权的目的',
      s2l5: '不得干扰或破坏服务的正常运行',
      s2l6: '不得尝试未经授权访问我们的系统或网络',
      section3Title: '3. 禁止行为',
      s3p1: '使用我们的服务时，严禁从事以下行为：',
      s3l1: '发布、传输任何违法、有害、威胁、辱骂、骚扰、侵权、中伤、粗俗、淫秽或其他令人反感的内容',
      s3l2: '侵犯他人的知识产权或其他合法权益',
      s3l3: '传播病毒、恶意代码或其他可能损害系统的内容',
      s3l4: '进行任何形式的网络攻击或恶意行为',
      s3l5: '滥用服务资源或影响其他用户的正常使用',
      s3l6: '未经授权共享账户或转售服务',
      section4Title: '4. 知识产权',
      s4p1: '本服务及其所有相关内容（包括但不限于软件、文本、图片、标志、音频、视频）的知识产权归我们或相关权利人所有。',
      s4p2: '未经明确书面许可，您不得复制、修改、传播、展示或以其他方式使用这些内容。',
      section5Title: '5. 免责声明',
      s5p1: '我们将尽力提供稳定可靠的服务，但不对以下情况承担责任：',
      s5l1: '因不可抗力、网络故障、系统维护等原因导致的服务中断',
      s5l2: '因用户自身原因（如设备故障、网络问题）造成的使用障碍',
      s5l3: '第三方服务或内容的质量、安全性或合法性',
      s5l4: '因用户违反本条款或相关法律法规造成的任何损失',
      s5p2: '服务按"现状"和"可用"基础提供，不提供任何明示或暗示的保证。',
      section6Title: '6. 费用与支付',
      s6p1: '部分服务需要付费使用。具体费用标准以网站公布的价格为准。',
      s6l1: '所有费用均以人民币计价',
      s6l2: '支付后不支持退款，除非法律另有规定',
      s6l3: '我们保留随时调整价格的权利',
      s6l4: '如因您的原因导致支付失败，我们不承担责任',
      section7Title: '7. 账户终止',
      s7p1: '在以下情况下，我们有权暂停或终止您的账户：',
      s7l1: '您违反本服务条款的任何规定',
      s7l2: '您的行为可能给我们或其他用户带来法律风险',
      s7l3: '您长期未使用账户（超过12个月）',
      s7l4: '应司法机关或政府部门的要求',
      s7p2: '账户终止后，您将无法访问服务，且我们不对任何数据丢失承担责任。',
      section8Title: '8. 条款变更',
      s8p1: '我们保留随时修改本服务条款的权利。重大变更将通过网站公告或电子邮件通知您。',
      s8p2: '继续使用服务即表示您接受修改后的条款。如不同意变更，请停止使用服务。',
      section9Title: '9. 争议解决',
      s9p1: '本条款受中华人民共和国法律管辖。因本条款引起的任何争议，双方应首先通过友好协商解决。',
      s9p2: '协商不成的，任何一方均可向我们所在地有管辖权的人民法院提起诉讼。',
      section10Title: '10. 联系我们',
      s10p1: '如您对本服务条款有任何疑问或建议，请通过以下方式联系我们：',
      contactEmail: '邮箱：support@example.com',
      contactService: '在线客服：工作日 9:00-18:00',
      agreementText: '使用我们的服务即表示您已阅读、理解并同意遵守本服务条款的所有内容。'
    },
    research: {
      title: '加速器技术研究',
      subtitle: '探索网络加速技术的前沿，分享我们的技术洞察和实践经验',
      searchPlaceholder: '搜索文章...',
      noArticlesFound: '未找到相关文章',
      noArticlesPublished: '暂无文章发布',
      readMore: '阅读全文',
      navTitle: '技术研究',
      navTitleEn: 'Research',
      categories: {
        tech_blog: '技术博客',
        whitepaper: '白皮书',
        case_study: '案例分析',
        network_optimization: '网络优化',
        security_research: '安全研究'
      }
    },
    profile: {
      title: '账号管理',
      subtitle: '管理您的个人信息和账号设置',
      loading: '加载中...',
      accountInfo: '账号信息',
      purchases: '购买记录',
      security: '安全设置',
      deleteAccount: '删除账号',
      accountInfoTitle: '账号信息',
      accountInfoDesc: '查看您的账号状态和订阅信息',
      emailAddress: '邮箱地址',
      phoneNumber: '手机号码',
      notSet: '未设置',
      memberStatus: '会员状态',
      vipMember: 'VIP会员',
      regularUser: '普通用户',
      vipRemaining: 'VIP剩余时长',
      days: '天',
      renew: '续费',
      purchase: '购买',
      expiryTime: '到期时间',
      vipBenefits: 'VIP会员权益',
      aiAdvanced: 'AI高级功能',
      priorityProcessing: '优先处理',
      exclusiveSupport: '专属客服',
      exclusiveContent: '独家内容',
      editEmail: '修改邮箱地址',
      editEmailDesc: '输入新邮箱地址后，我们将发送验证邮件到新邮箱',
      newEmail: '新邮箱地址',
      newEmailPlaceholder: '请输入新邮箱地址',
      verificationSent: '验证邮件已发送到',
      checkEmail: '，请检查邮箱并点击验证链接',
      cancel: '取消',
      sending: '发送中...',
      sendVerificationEmail: '发送验证邮件',
      done: '完成',
      editPhone: '修改手机号码',
      editPhoneDesc: '输入新手机号码后，我们将发送验证码到新手机',
      newPhone: '新手机号码',
      newPhonePlaceholder: '请输入新手机号码',
      verificationCode: '验证码',
      verificationCodePlaceholder: '请输入6位验证码',
      sendCode: '发送验证码',
      verifying: '验证中...',
      verifyAndUpdate: '验证并更新',
      purchasesTitle: '购买记录',
      purchasesDesc: '查看您的所有购买历史',
      orderDate: '订单日期',
      orderNumber: '订单编号',
      memberType: '会员类型',
      memberDuration: '会员时长',
      acquisitionMethod: '获取途径',
      noPurchases: '暂无购买记录',
      permanent: '永久',
      gifted: '赠送',
      purchased: '购买',
      securityTitle: '安全设置',
      securityDesc: '管理您的密码和账号安全',
      changePassword: '修改密码',
      currentPassword: '当前密码',
      currentPasswordPlaceholder: '请输入当前密码',
      newPassword: '新密码',
      newPasswordPlaceholder: '请输入新密码',
      confirmNewPassword: '确认新密码',
      confirmNewPasswordPlaceholder: '请再次输入新密码',
      changing: '修改中...',
      deleteAccountAgreement: '账号注销协议',
      agreementSection1: '一、注销前需满足的条件',
      agreementSection1Item1: '已取消所有自动订阅服务，确保无未完成的订阅套餐；',
      agreementSection1Item2: '账号当前不存在任何纠纷、投诉或被举报的情况，且未违反用户协议。',
      agreementSection2: '二、注销流程说明',
      agreementSection2Item1: '确认满足上述条件后，可提交账号删除申请，提交后无法撤回；',
      agreementSection2Item2: '申请提交后账号将立即注销，所有数据将被清除。',
      agreementSection3: '三、数据删除与保留说明',
      agreementSection3Item1: '账号注销后，我们将删除账号注册时使用的邮箱、手机号及密码；',
      agreementSection3Item2: '同时删除订单记录、登录记录及使用GUICHAO服务的历史数据；',
      agreementSection3Item3: '账号剩余会员天数等所有权益将清空，无法恢复。',
      agreementSection4: '四、其他提示',
      agreementSection4Item1: '注销后，原账号绑定的手机号、邮箱及第三方登录信息将被释放，可重新用于注册或绑定；',
      agreementSection4Item2: '已注销账号无法再次登录或恢复，重新注册亦无法享受此前已获得的新用户福利；',
      agreementSection4Item3: '如需再次使用GUICHAO服务，需重新注册账号。',
      agreementCheckbox: '我已仔细阅读并理解《账号注销协议》的全部内容，明确知晓注销后的所有后果，并自愿申请注销账号',
      deleteWarning: '警告：此操作无法撤销',
      deleteWarningDesc: '删除账号将永久删除以下内容：',
      deleteWarningItem1: '您的所有个人资料',
      deleteWarningItem2: '购买记录和订阅信息',
      deleteWarningItem3: '账号相关的所有数据',
      confirmDelete: '确认删除账号',
      confirmDeleteDesc: '为了确保账号安全，请输入您的登录密码以继续删除操作。',
      loginPassword: '登录密码',
      loginPasswordPlaceholder: '请输入您的登录密码',
      deleteNote: '此操作无法撤销，将永久删除您的账号及所有相关数据。',
      deleting: '删除中...',
      confirmDeleteBtn: '确认删除',
      loadFailed: '加载失败',
      loadPurchasesFailed: '加载购买记录失败',
      saveFailed: '保存失败',
      saveSuccess: '保存成功',
      profileUpdated: '您的个人信息已更新',
      oldPasswordError: '旧密码错误',
      oldPasswordErrorDesc: '您输入的当前密码不正确，请重试',
      changeSuccess: '修改成功',
      passwordUpdated: '您的密码已更新',
      changeFailed: '修改失败',
      loggedOut: '已退出登录',
      logoutSuccess: '您已成功退出账号',
      logoutFailed: '退出失败',
      enterPassword: '请输入密码',
      enterPasswordDesc: '为了安全起见，请输入您的登录密码',
      passwordError: '密码错误',
      passwordErrorDesc: '您输入的密码不正确，请重试',
      verificationSuccess: '验证成功',
      deleteRequestSubmitted: '您的账号删除请求已提交，请联系管理员完成删除',
      verificationFailed: '验证失败',
      enterContact: '请输入新的联系方式',
      emailVerificationSent: '验证邮件已发送',
      checkNewEmail: '请检查您的新邮箱并点击验证链接',
      codeVerificationSent: '验证码已发送',
      checkSMS: '请检查您的手机短信',
      sendFailed: '发送失败',
      enterCode: '请输入验证码',
      phoneUpdated: '手机号已更新',
      phoneUpdateSuccess: '您的手机号已成功修改',
      emailVerification: '邮箱验证',
      clickEmailLink: '请点击邮件中的验证链接完成邮箱更新',
      usernameMin: '用户名至少2个字符',
      usernameMax: '用户名最多50个字符',
      invalidURL: '请输入有效的URL',
      bioMax: '简介最多500个字符',
      enterCurrentPassword: '请输入当前密码',
      passwordMin: '密码至少6个字符',
      passwordMismatch: '两次密码输入不一致',
      noSubscription: '未设置订阅',
      expired: '已过期'
    }
  },
  en: {
    header: {
      tagline: 'Built for Chinese Abroad',
      taglineEn: '专为海外华人设计',
      home: 'Home',
      homeEn: '首页',
      features: 'Features',
      featuresEn: '产品特色',
      pricing: 'Pricing',
      pricingEn: '套餐价格',
      download: 'Download',
      downloadEn: '下载客户端',
      contact: 'Contact',
      contactEn: '联系我们',
      login: 'Login',
      freeTrial: 'Free Trial',
      accountManagement: 'Account',
      logout: 'Logout'
    },
    hero: {
      title: 'Home Network Access Simplified',
      subtitle: 'Professional network acceleration service for Chinese living abroad to easily access domestic network resources',
      badge: 'Fast & Stable • Secure & Reliable • One-Click Connect',
      security: 'Enterprise Security',
      securityEn: '企业级安全',
      latency: 'Ultra Low Latency',
      latencyEn: '毫秒级延迟',
      network: 'Global Network',
      networkEn: '全球节点',
      startTrial: 'Start Free Trial',
      downloadClient: 'Download Client',
      windows: 'Windows',
      windowsDesc: 'PC Client',
      macos: 'macOS',
      macosDesc: 'Mac Client',
      ios: 'iOS',
      iosDesc: 'iPhone/iPad',
      android: 'Android',
      androidDesc: 'Android Phone',
      browser: 'Browser',
      browserDesc: 'Chrome Extension',
      clickDownload: 'Click to Download'
    },
    features: {
      badge: '⚡ Features',
      title: 'Why Choose',
      titleBrand: 'GuiChao',
      subtitle: 'Network solution designed for overseas Chinese, enabling seamless access to domestic network services',
      speed: 'Lightning Fast',
      speedDesc: 'Latest acceleration technology, 300% speed boost, buffer-free 4K streaming',
      speedHighlight: 'Ultra Low Latency',
      encryption: 'Military Grade Encryption',
      encryptionDesc: 'AES-256 encryption protects your network security and privacy',
      encryptionHighlight: 'Bank Level Security',
      nodes: 'Global Network',
      nodesDesc: '50+ cities worldwide, intelligent routing for stable connections',
      nodesHighlight: '50+ Nodes',
      devices: 'Multi-Device Support',
      devicesDesc: 'One account supports 10 devices simultaneously, family sharing made easy',
      devicesHighlight: '10 Devices',
      uptime: '7x24 Online',
      uptimeDesc: '99.9% service availability, year-round stable network service',
      uptimeHighlight: '99.9% Uptime',
      support: 'Professional Support',
      supportDesc: 'Chinese technical support team, WeChat group real-time assistance',
      supportHighlight: 'Chinese Support',
      stat1: '1M+',
      stat1Label: 'Active Users',
      stat1En: '用户信赖',
      stat2: '50+',
      stat2Label: 'Global Nodes',
      stat2En: '全球节点',
      stat3: '99.9%',
      stat3Label: 'Uptime SLA',
      stat3En: '稳定运行',
      stat4: '24/7',
      stat4Label: 'Support',
      stat4En: '技术支持'
    },
    scenarios: {
      title: 'Multiple Acceleration Scenarios',
      subtitle: 'Whether entertainment, learning or work, GuiChao provides comprehensive acceleration support',
      video: 'Video Entertainment',
      videoDesc: 'Smooth streaming from domestic video platforms, enjoy HD content',
      sports: 'Sports Events',
      sportsDesc: 'Watch mainland sports broadcasts in real-time, never miss exciting moments',
      gaming: 'Domestic Gaming',
      gamingDesc: 'Reduce game latency, enjoy popular domestic games smoothly',
      education: 'Remote Learning',
      educationDesc: 'Stable connection to mainland education platforms, worry-free online learning',
      meeting: 'Business Meetings',
      meetingDesc: 'Efficient cross-border video conferences, smoother team collaboration',
      streaming: 'Live Streaming',
      streamingDesc: 'HD smooth streaming, more professional content creation'
    },
    pricing: {
      badge: '💰 Pricing',
      title: 'Choose Your',
      titleBrand: 'Plan',
      subtitle: 'Flexible pricing plans to meet different user needs. Supports WeChat Pay, Alipay, USDT and more',
      discount: '🎉 Annual plan users enjoy 20% off, save up to HK$140',
      popular: '🔥 Most Popular',
      trial: 'Trial',
      trialDesc: 'New user exclusive, experience GuiChao service',
      trialPrice: 'Free',
      trialPeriod: '3-day trial',
      trialButton: 'Start Trial',
      standard: 'Standard',
      standardDesc: 'Recommended for individual users, best value',
      standardButton: 'Choose Standard',
      premium: 'Premium',
      premiumDesc: 'Best choice for families/enterprises',
      premiumButton: 'Choose Premium',
      selectPlan: 'Click to Select',
      guarantee1: '7-Day Money Back',
      guarantee1Desc: 'Refund anytime if unsatisfied',
      guarantee2: '24-Hour Support',
      guarantee2Desc: 'Answer your questions anytime',
      guarantee3: 'Unlimited Data',
      guarantee3Desc: 'Enjoy high-speed network experience',
      paymentTitle: 'Select Payment Method',
      paymentSecurity: 'Secure encrypted payment, supports 7-day money-back guarantee',
      cancel: 'Cancel',
      wechat: 'WeChat Pay',
      wechatDesc: 'Quick payment with WeChat',
      alipayHK: 'Alipay HK',
      alipayHKDesc: 'Convenient payment with Alipay (Hong Kong)',
      paypal: 'PayPal',
      paypalDesc: 'Global online payment',
      googlePay: 'Google Pay',
      googlePayDesc: 'Quick payment with Google',
      applePay: 'Apple Pay',
      applePayDesc: 'Payment for Apple devices',
      stripe: 'Stripe',
      stripeDesc: 'Credit/Debit card payment'
    },
    footer: {
      brand: 'Network acceleration service designed for overseas Chinese, enabling seamless access to domestic network experience abroad.',
      wechatGroup: 'WeChat Group',
      email: 'Email',
      products: 'Products & Services',
      features: 'Features',
      pricing: 'Pricing',
      freeTrial: 'Free Trial',
      nodeStatus: 'Node Status',
      speedTest: 'Speed Test',
      download: 'Download',
      windowsClient: 'Windows Client',
      macosClient: 'macOS Client',
      iosApp: 'iOS App',
      androidApp: 'Android App',
      webVersion: 'Web Version',
      support: 'Help & Support',
      tutorial: 'Tutorial',
      faq: 'FAQ',
      contactSupport: 'Contact Support',
      feedback: 'Feedback',
      terms: 'Terms of Service',
      newsletter: 'Newsletter',
      emailPlaceholder: 'Enter email address',
      subscribe: 'Subscribe',
      copyright: '© 2024 GuiChao GuiChao.win. All rights reserved.',
      privacy: 'Privacy Policy',
      cookie: 'Cookie Policy',
      research: 'Accelerator Technology Research',
      techBlog: 'Tech Blog',
      whitepapers: 'Whitepapers',
      caseStudies: 'Case Studies',
      networkOptimization: 'Network Optimization',
      securityResearch: 'Security Research',
      tagline: 'Professional network service provider for overseas Chinese | Distance is no longer a barrier',
      ownership: 'This website is owned and operated by HK Guichao Technology Co., Limited'
    },
    auth: {
      joinTitle: 'Join',
      joinBrand: 'GuiChao',
      subtitle: 'Network acceleration service designed for overseas Chinese, enabling seamless access to domestic network experience.',
      fastConnection: 'Lightning Fast',
      fastDesc: 'Ultra low latency, buffer-free 4K streaming',
      militaryEncryption: 'Military Grade Encryption',
      encryptionDesc: 'AES-256 encryption, privacy protection',
      globalNodes: 'Global Network',
      nodesDesc: '50+ cities worldwide, intelligent routing',
      review1: '"GuiChao is amazing! Super fast connection, watching domestic videos is flawless."',
      reviewer1: '- User from USA, Mr. Zhang',
      review2: '"Working abroad, I often need to access domestic business databases. GuiChao perfectly solves my pain point with fast speed and affordable price. Essential for business!"',
      reviewer2: '- User from UK, Ms. Li',
      welcomeTitle: 'Welcome to GuiChao',
      welcomeDesc: 'Please login or register your account',
      login: 'Login',
      register: 'Register',
      email: 'Email',
      emailPlaceholder: 'Enter email address',
      password: 'Password',
      passwordPlaceholder: 'Enter password',
      passwordPlaceholder6: 'Set password (at least 6 characters)',
      passwordPlaceholder8: 'Enter password (at least 8 characters)',
      newPasswordPlaceholder: 'Set new password (at least 6 characters)',
      confirmPassword: 'Confirm Password',
      confirmPasswordPlaceholder: 'Enter password again',
      rememberMe: 'Remember me',
      forgotPassword: 'Forgot password?',
      loggingIn: 'Logging in...',
      loginButton: 'Login',
      registerButton: 'Register Account',
      registering: 'Registering...',
      agreeTerms1: 'By logging in, you agree to our',
      agreeTerms2: 'Terms of Service',
      agreeTerms3: 'and',
      agreeTerms4: 'Privacy Policy',
      username: 'Username',
      usernamePlaceholder: 'Enter username',
      readAgree: 'I have read and agree to',
      termsLink: 'Terms of Service',
      privacyLink: 'Privacy Policy',
      orDivider: 'or',
      googleLogin: 'Login with Google',
      wechatLogin: 'Login with WeChat',
      // Login methods
      emailLogin: 'Email Login',
      phoneLogin: 'Phone Login',
      otpLogin: 'OTP Login',
      phone: 'Phone',
      phonePlaceholder: 'Enter phone number',
      otpPlaceholder: 'Enter 6-digit code',
      getOtp: 'Get Code',
      resendOtp: 'Resend',
      // Login status
      sendingOtp: 'Sending...',
      verifying: 'Verifying...',
      resetting: 'Resetting...',
      nextStep: 'Next',
      // Register
      phoneRegister: 'Phone',
      emailRegister: 'Email',
      // Forgot password
      resetPassword: 'Reset Password',
      backToLogin: 'Back to Login',
      // Messages
      pleaseAgreeTerms: 'Please agree to the terms first',
      otpSent: 'Code sent',
      checkSms: 'Please check your SMS',
      checkEmail: 'Please check your email',
      sendFailed: 'Send failed',
      loginSuccess: 'Login successful',
      verifyFailed: 'Verification failed',
      registerSuccess: 'Registration successful',
      resetSuccess: 'Password reset successful',
      useNewPassword: 'Please login with your new password',
      resetFailed: 'Reset failed',
      phoneNotRegistered: 'Phone number not registered',
      emailNotRegistered: 'Email not registered',
      pleaseRegisterFirst: 'Please register first',
      cannotResetPassword: 'Cannot reset password, please register first',
      passwordMinLength: 'Password must be at least 6 characters',
      invalidEmail: 'Please enter a valid email address',
      invalidPhone: 'Please enter a valid phone number',
      otpLength: 'Code must be 6 digits'
    },
    download: {
      badge: '📱 Download',
      title: 'All',
      titleBrand: 'Platforms',
      subtitle: 'Supports Windows, macOS, iOS, Android and more. One account for multiple devices',
      smartDownload: 'Smart Download',
      viewTutorial: 'View Tutorial',
      downloadBtn: 'Download',
      oneClickConnect: 'One-Click Connect',
      smartRouting: 'Smart Routing',
      autoStart: 'Auto Start',
      nativeSupport: 'Native Support',
      menubarControl: 'Menubar Control',
      systemIntegration: 'System Integration',
      appStore: 'App Store Download',
      shortcuts: 'Shortcuts',
      siriSupport: 'Siri Support',
      googlePlay: 'Google Play',
      oneClickShare: 'One-Click Share',
      powerSaving: 'Power Saving Mode',
      routerFirmware: 'Router Firmware',
      familyShare: 'Family Share',
      deviceControl: 'Device Control',
      timedSwitch: 'Timed Switch',
      browserExtension: 'Browser Extension',
      freeUse: 'Free to Use',
      webProxy: 'Web Proxy',
      smartSplit: 'Smart Split',
      tutorialTitle: 'Usage',
      tutorialBrand: 'Tutorial',
      tutorialSubtitle: 'Quick start in simple steps',
      windowsTutorial: 'Windows',
      windowsStep1: 'Download and run installer',
      windowsStep2: 'Follow wizard to complete installation',
      windowsStep3: 'Login with your credentials',
      windowsStep4: 'Select node and click connect',
      mobileTutorial: 'Mobile Client',
      mobileStep1: 'Download app from store',
      mobileStep2: 'Register or login',
      mobileStep3: 'Allow VPN configuration',
      mobileStep4: 'Select server and connect',
      routerTutorial: 'Router',
      routerStep1: 'Backup original firmware',
      routerStep2: 'Flash GuiChao firmware',
      routerStep3: 'Configure network parameters',
      routerStep4: 'Set device access control',
      helpTitle: 'Need',
      helpBrand: 'Help?',
      helpSubtitle: 'Our technical support team is here to assist you',
      downloadIssues: 'Download Issues',
      downloadIssuesDesc: 'Download failures, installation errors',
      tutorialGuide: 'Tutorial Guide',
      tutorialGuideDesc: 'Detailed text and video tutorials',
      support247: '24/7 Support',
      support247Desc: 'Round-the-clock technical support',
      contactSupport: 'Contact Support'
    },
    notFound: {
      title: 'Page',
      titleBrand: 'Not Found',
      subtitle: 'Sorry, the page you are looking for does not exist or has been moved',
      backHome: 'Back to Home',
      hint: 'Or you can try using the navigation menu to find what you need'
    },
    privacy: {
      title: 'Privacy Policy',
      subtitle: 'GuiChao values your personal information. We will take security measures in accordance with laws and regulations to protect your personal information.',
      updateDate: 'Last Updated: December 30, 2024',
      effectiveDate: 'Effective Date: December 30, 2024',
      importantTitle: 'Important Notice',
      importantText: 'Please read this GuiChao Privacy Policy carefully (especially the bold content) and ensure you understand how we handle your personal information. If you have any questions, please contact us. If you do not agree to any terms, please stop using GuiChao services immediately.',
      tocTitle: 'Table of Contents',
      section1: '1. How We Collect and Use Your Personal Information',
      section2: '2. How We Use Cookies and Similar Technologies',
      section3: '3. How We Share, Transfer, and Publicly Disclose Your Personal Information',
      section4: '4. How We Store and Protect Your Personal Information',
      section5: '5. Your Rights to Manage Personal Information',
      section6: '6. Protection of Minors\' Personal Information',
      section7: '7. Changes and Revisions to Privacy Policy',
      section8: '8. How to Contact Us',
      introPara1: 'GuiChao is developed and operated by HK Guichao Technology Co., Limited. We respect and protect the personal information of all users, and will protect user information and privacy security in accordance with laws and regulations. We are committed to maintaining your trust and adhering to the following principles: accountability, purpose limitation, consent, data minimization, security, participation, and transparency.',
      introPara2: 'Please read and understand this Privacy Policy carefully before using our products and services. Once you start using GuiChao services, it indicates that you have fully understood and agreed to this policy.',
      s1h1: '1.1 Account Registration and Login',
      s1p1: 'When you register a GuiChao account, we will collect your phone number, email address, password and other information to create an account and verify your identity. You can choose to log in through third-party accounts (such as WeChat, Apple ID), and we will collect your nickname, avatar and other public information after obtaining your authorization.',
      s1h2: '1.2 Network Acceleration Service',
      s1p2: 'To provide you with network acceleration services, we need to collect your device information (device model, operating system version, device identifier), network information (IP address, network type, network status), connection logs, etc. This information is used to optimize service quality, diagnose network problems, and ensure service security.',
      s1h3: '1.3 Payment Function',
      s1p3: 'When you purchase our paid services, we may collect your payment information, including third-party payment accounts (Alipay, WeChat Pay, Apple Pay, etc.). Payment information is collected and processed by third-party payment institutions, and we only save necessary order information.',
      s1h4: '1.4 Customer Service',
      s1p4: 'When you contact our customer service, we may collect your contact information, problem description, chat records, etc., in order to provide you with support and solve problems.',
      s1h5: '1.5 Exceptions to Authorization and Consent',
      s1p5: 'According to relevant laws and regulations, collection of your personal information does not require your authorization and consent in the following circumstances:',
      s1l1: 'Directly related to national security and defense security',
      s1l2: 'Directly related to public security, public health, and major public interests',
      s1l3: 'Directly related to criminal investigation, prosecution, trial and judgment execution',
      s1l4: 'For maintaining your or other individuals\' life, property and other major legitimate rights but it is difficult to obtain consent',
      s1l5: 'Personal information that you disclose to the public',
      s1l6: 'Personal information collected from legally disclosed information',
      s2p1: 'To ensure the normal operation of the website, provide you with an easier access experience, and recommend content that may interest you, we will store small data files called Cookies on your device. Cookies usually contain identifiers, site names, and some numbers and characters.',
      s2h1: 'Main uses of Cookies:',
      s2l1: 'Ensuring security and efficient operation of products and services: We may set authentication and security Cookies to avoid repeated logins',
      s2l2: 'Helping you get an easier access experience: Using Cookies can help you skip repeated form filling and search input',
      s2l3: 'Recommending and displaying personalized content: We may use Cookies to understand your preferences and usage habits, perform data analysis, improve product services, and recommend personalized content',
      s2p2: 'You can manage or delete Cookies through browser settings. However, if you do so, you may need to personally change user settings each time you visit, and the corresponding information you previously recorded will be deleted, which may have a certain impact on the security of the services you use.',
      s3h1: '3.1 Sharing',
      s3p1: 'We will not share your personal information with any company, organization or individual, except in the following circumstances:',
      s3l1: 'Sharing with explicit consent: After obtaining your explicit consent, we will share your personal information with other parties',
      s3l2: 'Sharing under legal circumstances: According to laws and regulations, litigation, dispute resolution needs, or at the request of administrative and judicial authorities, we may share your personal information',
      s3l3: 'Sharing with affiliates: For the convenience of providing you with services, your personal information may be shared with our affiliates',
      s3l4: 'Sharing with authorized partners: Only to achieve the purposes stated in this policy, some of our services will be provided by authorized partners. We may share some of your personal information with partners',
      s3h2: '3.2 Transfer',
      s3p2: 'We will not transfer your personal information to any company, organization or individual, except in the following circumstances: transfer with explicit consent; in the event of merger, acquisition or bankruptcy liquidation, if personal information transfer is involved, we will require the new company or organization holding your personal information to continue to be bound by this policy.',
      s3h3: '3.3 Public Disclosure',
      s3p3: 'We will only publicly disclose your personal information in the following circumstances: after obtaining your explicit consent; disclosure based on law: in the case of laws, legal procedures, litigation or mandatory requirements of government authorities, we may publicly disclose your personal information.',
      s4h1: '4.1 Information Storage',
      s4p1: 'Your personal information will be stored in the People\'s Republic of China. If cross-border transmission is required, we will obtain your separate authorization and consent, and ensure that the data recipient has sufficient data protection capabilities to protect your personal information. We will only retain your personal information for the period necessary to achieve the purposes stated in this policy, unless there is a mandatory legal retention requirement.',
      s4h2: '4.2 Information Security',
      s4p2: 'We strive to provide security for users\' information to prevent information loss, improper use, unauthorized access or disclosure. The security measures we take include:',
      s4l1: 'We use various security technologies to ensure information security. For example, we will use encryption technology (such as SSL) to protect your personal information',
      s4l2: 'We establish specialized management systems, processes and organizations to ensure information security',
      s4l3: 'We take strict management measures for employees who may have access to your information, including adopting different permission controls',
      s4l4: 'We will take appropriate security measures and technical means that comply with industry standards to store and protect your personal information to prevent it from being lost, misused, subjected to unauthorized access or disclosure, tampered with or destroyed',
      s4h3: '4.3 Security Incident Handling',
      s4p3: 'In the unfortunate event of a personal information security incident, we will notify you in accordance with legal requirements: the basic situation of the security incident and possible impact, the disposal measures we have taken or will take, suggestions for you to independently prevent and reduce risks, remedial measures for you, etc. We will promptly notify you of the relevant information about the incident by email, letter, phone, push notification, etc.',
      s5p1: 'In accordance with relevant laws, regulations, standards of China, as well as common practices in other countries and regions, we guarantee that you can exercise the following rights regarding your personal information:',
      s5h1: '5.1 Access and Update Your Personal Information',
      s5p2: 'You have the right to access and update your personal information, except as otherwise provided by laws and regulations. You can access and update your personal information by yourself in the following ways: After logging in to your account, view and modify your account information, personal data, etc. in "Personal Center".',
      s5h2: '5.2 Delete Your Personal Information',
      s5p3: 'In the following circumstances, you can request us to delete your personal information:',
      s5l1: 'If our handling of personal information violates laws and regulations',
      s5l2: 'If we collect and use your personal information without obtaining your consent',
      s5l3: 'If our handling of personal information violates our agreement with you',
      s5l4: 'If you have deactivated your account',
      s5h3: '5.3 Account Deactivation',
      s5p4: 'You can apply to deactivate your account by contacting customer service. After you deactivate your account, we will stop providing you with products or services and delete your personal information according to your request, except as otherwise provided by laws and regulations.',
      s5h4: '5.4 Withdraw Consent',
      s5p5: 'You can change the scope of your authorization for us to continue collecting personal information or withdraw your authorization by deleting information, turning off device functions, making privacy settings on the website or software, etc. You can also withdraw all authorization for us to continue collecting your personal information by deactivating your account.',
      s5h5: '5.5 Responding to Your Requests',
      s5p6: 'To ensure security, you may need to provide a written request or prove your identity in other ways. We may first require you to verify your identity before processing your request. We will respond within 15 working days. If you are not satisfied, you can also file a complaint through the contact information in this policy.',
      s6p1: 'We attach great importance to the protection of minors\' personal information. If you are a minor under the age of 18, you should obtain the written consent of your parents or legal guardians before using our products and/or services.',
      s6p2: 'We protect minors\' personal information in accordance with national laws and regulations. For the collection of minors\' personal information with the consent of parents or legal guardians, we will only use or publicly disclose this information when permitted by law, with the explicit consent of parents or guardians, or when necessary to protect minors.',
      s6p3: 'If we discover that we have collected personal information of minors without first obtaining verifiable parental or legal guardian consent, we will try to delete the relevant data as soon as possible.',
      s7p1: 'In order to provide you with better services, we may modify the terms of this policy from time to time according to the update of products or services and relevant requirements of laws and regulations. Such modifications constitute part of this Privacy Policy.',
      s7p2: 'If such updates result in a substantial reduction or major change to your rights under this Privacy Policy, we will notify you by website announcement, push notification, pop-up prompt or other means before this policy takes effect. If you do not agree to such changes, you can choose to stop using our products and services; if you continue to use our products and services, it means that you have fully read, understood and agreed to be bound by this revised Privacy Policy.',
      s7p3: 'The major changes referred to in this policy include but are not limited to:',
      s7l1: 'Major changes in our service model',
      s7l2: 'Changes in the main objects of personal information sharing, transfer or public disclosure',
      s7l3: 'Major changes in your rights regarding personal information processing and how to exercise them',
      s7l4: 'Changes in the department responsible for personal information security, contact information and complaint channels',
      s8p1: 'If you have any questions, opinions or suggestions about this Privacy Policy, or encounter any problems related to personal information protection when using our services, you can contact us in the following ways:',
      s8p2: 'In general, we will respond within 15 working days. If you are not satisfied with our response, especially if you believe that our personal information processing behavior has damaged your legitimate rights and interests, you can also seek a solution by filing a lawsuit with a court having jurisdiction over the defendant\'s domicile.',
      contactEmail: 'Email',
      companyName: 'Company Name',
      thanksTitle: 'Thank you again for trusting GuiChao!',
      thanksText: 'We will provide secure and reliable network acceleration services and continue to protect your personal information.'
    },
    cookie: {
      title: 'Cookie Policy',
      lastUpdated: 'Last Updated: January 2024',
      intro: 'This Cookie Policy explains how AI Smart Accelerator (\'we\' or \'the Service\') uses cookies and similar technologies to recognize you when you visit our websites, applications, and services. It explains what these technologies are, why we use them, and how you can control their use.',
      
      whatAreCookies: {
        title: 'What Are Cookies?',
        content: 'Cookies are small data files that are placed on your computer or mobile device when you visit a website. Cookies are widely used by website owners to make their websites work, or to work more efficiently, as well as to provide reporting information. Cookies set by the website owner (in this case, AI Smart Accelerator) are called \'first-party cookies.\' Cookies set by parties other than the website owner are called \'third-party cookies.\' Third-party cookies enable third-party features or functionality to be provided on or through the website (e.g., advertising, interactive content, and analytics). The parties that set these third-party cookies can recognize your computer both when it visits the website in question and also when it visits certain other websites.'
      },
      
      whyWeUseCookies: {
        title: 'Why Do We Use Cookies?',
        content: 'We use first-party and third-party cookies for several reasons. Some cookies are required for technical reasons for our websites to operate, and we refer to these as \'essential\' or \'strictly necessary\' cookies. Other cookies enable us to track and target the interests of our users to enhance the experience on our online properties. Third parties serve cookies through our websites for advertising, analytics, and other purposes.'
      },
      
      typesOfCookies: {
        title: 'Types of Cookies We Use',
        essential: {
          title: 'Essential Cookies',
          description: 'These cookies are strictly necessary to provide you with services available through our websites and to use some of its features, such as access to secure areas. Because these cookies are strictly necessary to deliver the services to you, you cannot refuse them without impacting how our websites function. You can block or delete them by changing your browser settings, but this may affect certain features of the website.'
        },
        performance: {
          title: 'Performance and Functionality Cookies',
          description: 'These cookies are used to enhance the performance and functionality of our websites but are not essential to their use. However, without these cookies, certain functionality (like videos) may become unavailable, or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously.'
        },
        analytics: {
          title: 'Analytics and Customization Cookies',
          description: 'These cookies collect information that is used to help us understand how our websites are being used or how effective our marketing campaigns are, or to help us customize our websites for you. For example, we use these cookies to count the number of visitors to the website and see how visitors move around the website. We use this information to improve the way our websites work, for example, by ensuring that users are finding what they are looking for easily.'
        },
        advertising: {
          title: 'Advertising Cookies',
          description: 'These cookies are used to make advertising messages more relevant to you. They perform functions like preventing the same ad from continuously reappearing, ensuring that ads are properly displayed for advertisers, and in some cases selecting advertisements that are based on your interests.'
        }
      },
      
      howToControl: {
        title: 'How Can You Control Cookies?',
        content: 'You have the right to decide whether to accept or reject cookies. You can exercise your cookie rights by setting your preferences in the Cookie Consent Manager. The Cookie Consent Manager allows you to select which categories of cookies you accept or reject. Essential cookies cannot be rejected as they are strictly necessary to provide you with services.',
        browserSettings: 'If you choose to reject cookies, you may still use our website, but your access to some functionality and areas of our website may be restricted. You may also set or amend your web browser controls to accept or refuse cookies.'
      },
      
      specificCookies: {
        title: 'Specific Cookies We Use',
        sessionCookies: 'Session Cookies: These cookies temporarily store information during your browsing session. They are deleted when you close your browser.',
        persistentCookies: 'Persistent Cookies: These cookies remain on your device for a longer period and are used to remember your preferences and login information.',
        securityCookies: 'Security Cookies: These cookies are used to authenticate users, prevent fraudulent use of login credentials, and protect user data from unauthorized parties.'
      },
      
      thirdParty: {
        title: 'Third-Party Cookies',
        content: 'In addition to our own cookies, we may also use various third-party cookies to report usage statistics of the website, deliver advertisements, and so on. These third-party service providers may use cookies to collect information about your visits to our website and other websites. We do not control these third-party cookies, and their use is governed by the privacy policies of the companies that provide them.'
      },
      
      updates: {
        title: 'Updates to This Cookie Policy',
        content: 'We may update this Cookie Policy from time to time to reflect changes to the cookies we use or for other operational, legal, or regulatory reasons. Please therefore revisit this Cookie Policy regularly to stay informed about our use of cookies and related technologies. The date at the top of this Cookie Policy indicates when it was last updated.'
      },
      
      contact: {
        title: 'Contact Us',
        content: 'If you have any questions about our use of cookies or other technologies, please contact us at:',
        email: 'Email: support@ai-accelerator.com'
      }
    },
    terms: {
      title: 'Terms of Service',
      lastUpdate: 'Last Updated: January 2024',
      importantTitle: 'Important Notice',
      importantText: 'Please read and understand these Terms of Service carefully before using our services. Using our services indicates your agreement to be bound by these terms.',
      section1Title: '1. Service Description',
      s1p1: 'Our network acceleration service is designed to optimize your network connection experience. Services include but are not limited to:',
      s1l1: 'Network connection acceleration and optimization',
      s1l2: 'Multi-node server support',
      s1l3: 'Data transmission encryption',
      s1l4: 'Technical support and customer service',
      s1p2: 'We reserve the right to modify, suspend or terminate part or all of the services at any time without notice.',
      section2Title: '2. User Responsibilities and Obligations',
      s2p1: 'As a service user, you agree to:',
      s2l1: 'Provide true and accurate registration information',
      s2l2: 'Properly keep account information and passwords',
      s2l3: 'Comply with all applicable laws and regulations',
      s2l4: 'Not use the service for any illegal or unauthorized purposes',
      s2l5: 'Not interfere with or disrupt the normal operation of the service',
      s2l6: 'Not attempt to access our systems or networks without authorization',
      section3Title: '3. Prohibited Activities',
      s3p1: 'When using our services, the following activities are strictly prohibited:',
      s3l1: 'Posting or transmitting any illegal, harmful, threatening, abusive, harassing, infringing, defamatory, vulgar, obscene or otherwise objectionable content',
      s3l2: 'Infringing on the intellectual property rights or other legitimate rights of others',
      s3l3: 'Spreading viruses, malicious code or other content that may damage the system',
      s3l4: 'Conducting any form of cyber attack or malicious behavior',
      s3l5: 'Abusing service resources or affecting other users\' normal use',
      s3l6: 'Sharing accounts or reselling services without authorization',
      section4Title: '4. Intellectual Property',
      s4p1: 'The intellectual property rights of this service and all related content (including but not limited to software, text, images, logos, audio, video) belong to us or relevant rights holders.',
      s4p2: 'Without explicit written permission, you may not copy, modify, distribute, display or otherwise use this content.',
      section5Title: '5. Disclaimer',
      s5p1: 'We will strive to provide stable and reliable services, but are not responsible for the following situations:',
      s5l1: 'Service interruptions due to force majeure, network failures, system maintenance, etc.',
      s5l2: 'Usage obstacles caused by user reasons (such as device failures, network problems)',
      s5l3: 'The quality, security or legality of third-party services or content',
      s5l4: 'Any losses caused by users violating these terms or relevant laws and regulations',
      s5p2: 'Services are provided on an "as is" and "as available" basis, without any express or implied warranties.',
      section6Title: '6. Fees and Payment',
      s6p1: 'Some services require payment. Specific fee standards are subject to the prices published on the website.',
      s6l1: 'All fees are denominated in RMB',
      s6l2: 'Refunds are not supported after payment, unless otherwise provided by law',
      s6l3: 'We reserve the right to adjust prices at any time',
      s6l4: 'We are not responsible for payment failures caused by your reasons',
      section7Title: '7. Account Termination',
      s7p1: 'We reserve the right to suspend or terminate your account in the following circumstances:',
      s7l1: 'You violate any provision of these Terms of Service',
      s7l2: 'Your behavior may bring legal risks to us or other users',
      s7l3: 'You have not used your account for a long time (more than 12 months)',
      s7l4: 'At the request of judicial authorities or government departments',
      s7p2: 'After account termination, you will not be able to access the service, and we are not responsible for any data loss.',
      section8Title: '8. Terms Changes',
      s8p1: 'We reserve the right to modify these Terms of Service at any time. Major changes will be notified to you through website announcements or email.',
      s8p2: 'Continued use of the service indicates your acceptance of the modified terms. If you do not agree to the changes, please stop using the service.',
      section9Title: '9. Dispute Resolution',
      s9p1: 'These terms are governed by the laws of the People\'s Republic of China. Any disputes arising from these terms should first be resolved through friendly negotiation.',
      s9p2: 'If negotiation fails, either party may file a lawsuit with a people\'s court having jurisdiction over our location.',
      section10Title: '10. Contact Us',
      s10p1: 'If you have any questions or suggestions about these Terms of Service, please contact us in the following ways:',
      contactEmail: 'Email: support@example.com',
      contactService: 'Online Support: Weekdays 9:00-18:00',
      agreementText: 'By using our services, you have read, understood, and agreed to comply with all contents of these Terms of Service.'
    },
    research: {
      title: 'Accelerator Technology Research',
      subtitle: 'Exploring the frontiers of network acceleration technology, sharing our technical insights and practical experience',
      searchPlaceholder: 'Search articles...',
      noArticlesFound: 'No articles found',
      noArticlesPublished: 'No articles published yet',
      readMore: 'Read More',
      navTitle: 'Research',
      navTitleEn: '技术研究',
      categories: {
        tech_blog: 'Tech Blog',
        whitepaper: 'Whitepaper',
        case_study: 'Case Study',
        network_optimization: 'Network Optimization',
        security_research: 'Security Research'
      }
    },
    profile: {
      title: 'Account Management',
      subtitle: 'Manage your personal information and account settings',
      loading: 'Loading...',
      accountInfo: 'Account Info',
      purchases: 'Purchase History',
      security: 'Security',
      deleteAccount: 'Delete Account',
      accountInfoTitle: 'Account Information',
      accountInfoDesc: 'View your account status and subscription information',
      emailAddress: 'Email Address',
      phoneNumber: 'Phone Number',
      notSet: 'Not Set',
      memberStatus: 'Membership Status',
      vipMember: 'VIP Member',
      regularUser: 'Regular User',
      vipRemaining: 'VIP Remaining',
      days: 'days',
      renew: 'Renew',
      purchase: 'Purchase',
      expiryTime: 'Expiry Time',
      vipBenefits: 'VIP Benefits',
      aiAdvanced: 'AI Advanced Features',
      priorityProcessing: 'Priority Processing',
      exclusiveSupport: 'Exclusive Support',
      exclusiveContent: 'Exclusive Content',
      editEmail: 'Edit Email Address',
      editEmailDesc: 'After entering your new email address, we will send a verification email to the new address',
      newEmail: 'New Email Address',
      newEmailPlaceholder: 'Enter new email address',
      verificationSent: 'Verification email sent to',
      checkEmail: ', please check your inbox and click the verification link',
      cancel: 'Cancel',
      sending: 'Sending...',
      sendVerificationEmail: 'Send Verification Email',
      done: 'Done',
      editPhone: 'Edit Phone Number',
      editPhoneDesc: 'After entering your new phone number, we will send a verification code to the new number',
      newPhone: 'New Phone Number',
      newPhonePlaceholder: 'Enter new phone number',
      verificationCode: 'Verification Code',
      verificationCodePlaceholder: 'Enter 6-digit code',
      sendCode: 'Send Code',
      verifying: 'Verifying...',
      verifyAndUpdate: 'Verify & Update',
      purchasesTitle: 'Purchase History',
      purchasesDesc: 'View all your purchase records',
      orderDate: 'Order Date',
      orderNumber: 'Order Number',
      memberType: 'Member Type',
      memberDuration: 'Member Duration',
      acquisitionMethod: 'Acquisition Method',
      noPurchases: 'No purchase records',
      permanent: 'Permanent',
      gifted: 'Gifted',
      purchased: 'Purchased',
      securityTitle: 'Security Settings',
      securityDesc: 'Manage your password and account security',
      changePassword: 'Change Password',
      currentPassword: 'Current Password',
      currentPasswordPlaceholder: 'Enter current password',
      newPassword: 'New Password',
      newPasswordPlaceholder: 'Enter new password',
      confirmNewPassword: 'Confirm New Password',
      confirmNewPasswordPlaceholder: 'Enter new password again',
      changing: 'Changing...',
      deleteAccountAgreement: 'Account Deletion Agreement',
      agreementSection1: '1. Requirements Before Deletion',
      agreementSection1Item1: 'All automatic subscriptions have been cancelled, ensuring no unfinished subscription packages;',
      agreementSection1Item2: 'The account currently has no disputes, complaints, or reports, and has not violated the user agreement.',
      agreementSection2: '2. Deletion Process',
      agreementSection2Item1: 'After confirming the above requirements, you can submit an account deletion request, which cannot be withdrawn;',
      agreementSection2Item2: 'After submission, the account will be immediately deleted and all data will be cleared.',
      agreementSection3: '3. Data Deletion and Retention',
      agreementSection3Item1: 'After account deletion, we will delete the email, phone number and password used for account registration;',
      agreementSection3Item2: 'Order records, login records and historical data of using GUICHAO services will be deleted;',
      agreementSection3Item3: 'All benefits including remaining VIP days will be cleared and cannot be recovered.',
      agreementSection4: '4. Other Notes',
      agreementSection4Item1: 'After deletion, the phone number, email and third-party login information bound to the original account will be released and can be used for registration or binding again;',
      agreementSection4Item2: 'Deleted accounts cannot be logged in or restored. New registrations cannot enjoy the new user benefits obtained before;',
      agreementSection4Item3: 'If you need to use GUICHAO services again, you need to register a new account.',
      agreementCheckbox: 'I have carefully read and understood all contents of the "Account Deletion Agreement", clearly know all consequences after deletion, and voluntarily apply for account deletion',
      deleteWarning: 'Warning: This action cannot be undone',
      deleteWarningDesc: 'Deleting your account will permanently delete:',
      deleteWarningItem1: 'All your personal information',
      deleteWarningItem2: 'Purchase records and subscription information',
      deleteWarningItem3: 'All account-related data',
      confirmDelete: 'Confirm Account Deletion',
      confirmDeleteDesc: 'To ensure account security, please enter your login password to continue the deletion operation.',
      loginPassword: 'Login Password',
      loginPasswordPlaceholder: 'Enter your login password',
      deleteNote: 'This action cannot be undone and will permanently delete your account and all related data.',
      deleting: 'Deleting...',
      confirmDeleteBtn: 'Confirm Delete',
      loadFailed: 'Load Failed',
      loadPurchasesFailed: 'Failed to load purchase records',
      saveFailed: 'Save Failed',
      saveSuccess: 'Save Successful',
      profileUpdated: 'Your profile has been updated',
      oldPasswordError: 'Incorrect Old Password',
      oldPasswordErrorDesc: 'The current password you entered is incorrect, please try again',
      changeSuccess: 'Change Successful',
      passwordUpdated: 'Your password has been updated',
      changeFailed: 'Change Failed',
      loggedOut: 'Logged Out',
      logoutSuccess: 'You have successfully logged out',
      logoutFailed: 'Logout Failed',
      enterPassword: 'Please Enter Password',
      enterPasswordDesc: 'For security reasons, please enter your login password',
      passwordError: 'Password Error',
      passwordErrorDesc: 'The password you entered is incorrect, please try again',
      verificationSuccess: 'Verification Successful',
      deleteRequestSubmitted: 'Your account deletion request has been submitted, please contact the administrator to complete deletion',
      verificationFailed: 'Verification Failed',
      enterContact: 'Please enter new contact information',
      emailVerificationSent: 'Verification email sent',
      checkNewEmail: 'Please check your new email inbox and click the verification link',
      codeVerificationSent: 'Verification code sent',
      checkSMS: 'Please check your SMS',
      sendFailed: 'Send Failed',
      enterCode: 'Please enter verification code',
      phoneUpdated: 'Phone Number Updated',
      phoneUpdateSuccess: 'Your phone number has been successfully updated',
      emailVerification: 'Email Verification',
      clickEmailLink: 'Please click the verification link in the email to complete email update',
      usernameMin: 'Username must be at least 2 characters',
      usernameMax: 'Username must be at most 50 characters',
      invalidURL: 'Please enter a valid URL',
      bioMax: 'Bio must be at most 500 characters',
      enterCurrentPassword: 'Please enter current password',
      passwordMin: 'Password must be at least 6 characters',
      passwordMismatch: 'Passwords do not match',
      noSubscription: 'No subscription set',
      expired: 'Expired'
    }
  },
  'zh-TW': {
    header: {
      tagline: '專為海外華人設計',
      taglineEn: 'Built for Chinese Abroad',
      home: '首頁',
      homeEn: 'Home',
      features: '產品特色',
      featuresEn: 'Features',
      pricing: '套餐價格',
      pricingEn: 'Pricing',
      download: '下載客戶端',
      downloadEn: 'Download',
      contact: '聯絡我們',
      contactEn: 'Contact',
      login: '登入',
      freeTrial: '免費試用',
      accountManagement: '帳號管理',
      logout: '退出登入'
    },
    hero: {
      title: '倦鳥歸巢 一鍵回國',
      subtitle: '專業的回國網路加速服務，讓海外華人輕鬆訪問國內網路資源',
      badge: '高速穩定 • 安全可靠 • 一鍵連接',
      security: '企業級安全',
      securityEn: 'Enterprise Security',
      latency: '毫秒級延遲',
      latencyEn: 'Ultra Low Latency',
      network: '全球節點',
      networkEn: 'Global Network',
      startTrial: '立即免費試用',
      downloadClient: '下載客戶端',
      windows: 'Windows',
      windowsDesc: 'PC客戶端',
      macos: 'macOS',
      macosDesc: 'Mac客戶端',
      ios: 'iOS',
      iosDesc: 'iPhone/iPad',
      android: 'Android',
      androidDesc: '安卓手機',
      browser: '瀏覽器',
      browserDesc: 'Chrome插件',
      clickDownload: '點擊下載'
    },
    features: {
      badge: '⚡ 產品特色',
      title: '為什麼選擇',
      titleBrand: '歸巢',
      subtitle: '專為海外華人打造的回國網路解決方案，讓您在海外也能無縫享受國內的網路服務',
      speed: '極速連接',
      speedDesc: '採用最新加速技術，連接速度提升300%，觀看4K影片無緩衝',
      speedHighlight: '毫秒級延遲',
      encryption: '軍用級加密',
      encryptionDesc: 'AES-256位加密技術，保護您的網路安全和隱私資料',
      encryptionHighlight: '銀行級安全',
      nodes: '全球節點',
      nodesDesc: '覆蓋全球50+城市，智慧選擇最優線路，確保連接穩定',
      nodesHighlight: '50+節點',
      devices: '多裝置支援',
      devicesDesc: '一個帳戶支援10台裝置同時使用，全家共享無憂',
      devicesHighlight: '10台裝置',
      uptime: '7x24在線',
      uptimeDesc: '99.9%服務可用性，全年無休為您提供穩定的網路服務',
      uptimeHighlight: '99.9%穩定',
      support: '專業客服',
      supportDesc: '中文技術支援團隊，微信群即時答疑，問題快速解決',
      supportHighlight: '中文支援',
      stat1: '1M+',
      stat1Label: '用戶信賴',
      stat1En: 'Active Users',
      stat2: '50+',
      stat2Label: '全球節點',
      stat2En: 'Global Nodes',
      stat3: '99.9%',
      stat3Label: '穩定運行',
      stat3En: 'Uptime SLA',
      stat4: '24/7',
      stat4Label: '技術支援',
      stat4En: 'Support'
    },
    scenarios: {
      title: '支援加速多種場景',
      subtitle: '無論是娛樂、學習還是工作，歸巢為您提供全方位的加速支援',
      video: '影音娛樂',
      videoDesc: '流暢觀看國內影片平台，享受高清串流媒體',
      sports: '體育賽事',
      sportsDesc: '即時觀看大陸體育賽事直播，不錯過精彩瞬間',
      gaming: '國服遊戲',
      gamingDesc: '降低遊戲延遲，暢玩國服熱門遊戲',
      education: '遠端學習',
      educationDesc: '穩定連接大陸教育平台，線上學習無憂',
      meeting: '辦公會議',
      meetingDesc: '高效跨境視訊會議，團隊協作更流暢',
      streaming: '達人直播',
      streamingDesc: '高清流暢直播推流，內容創作更專業'
    },
    pricing: {
      badge: '💰 套餐價格',
      title: '選擇適合您的',
      titleBrand: '套餐',
      subtitle: '靈活的價格方案，滿足不同用戶需求。支援微信、支付寶、USDT等多種支付方式',
      discount: '🎉 年付用戶享8折優惠，可節省高達HK$140',
      popular: '🔥 最受歡迎',
      trial: '體驗版',
      trialDesc: '新用戶專享，體驗歸巢服務',
      trialPrice: '免費',
      trialPeriod: '3天試用',
      trialButton: '立即試用',
      standard: '標準版',
      standardDesc: '個人用戶推薦，性價比之選',
      standardButton: '選擇標準版',
      premium: '旗艦版',
      premiumDesc: '家庭/企業用戶首選',
      premiumButton: '選擇旗艦版',
      selectPlan: '點擊選擇',
      guarantee1: '7天無憂退款',
      guarantee1Desc: '不滿意隨時退款',
      guarantee2: '24小時客服',
      guarantee2Desc: '隨時為您解答問題',
      guarantee3: '無限流量',
      guarantee3Desc: '暢享高速網路體驗',
      paymentTitle: '選擇支付方式',
      paymentSecurity: '支付過程安全加密，支援7天無憂退款',
      cancel: '取消',
      wechat: '微信支付',
      wechatDesc: '使用微信快速支付',
      alipayHK: '香港支付寶',
      alipayHKDesc: '支付寶(香港)便捷支付',
      paypal: 'PayPal',
      paypalDesc: '全球通用線上支付',
      googlePay: 'Google Pay',
      googlePayDesc: 'Google 快速支付',
      applePay: 'Apple Pay',
      applePayDesc: 'Apple 裝置專用支付',
      stripe: 'Stripe',
      stripeDesc: '信用卡/金融卡支付'
    },
    footer: {
      brand: '專為海外華人打造的回國網路加速服務，讓您在海外也能無縫享受國內的網路體驗。',
      wechatGroup: '微信群',
      email: '郵箱',
      products: '產品服務',
      features: '產品特色',
      pricing: '套餐價格',
      freeTrial: '免費試用',
      nodeStatus: '節點狀態',
      speedTest: '速度測試',
      download: '客戶端下載',
      windowsClient: 'Windows 客戶端',
      macosClient: 'macOS 客戶端',
      iosApp: 'iOS 應用',
      androidApp: 'Android 應用',
      webVersion: '網頁版',
      support: '幫助支援',
      tutorial: '使用教學',
      faq: '常見問題',
      contactSupport: '聯絡客服',
      feedback: '意見回饋',
      terms: '服務條款',
      newsletter: '最新動態',
      emailPlaceholder: '輸入郵箱位址',
      subscribe: '訂閱',
      copyright: '© 2024 歸巢 GuiChao.win. 保留所有權利。',
      privacy: '隱私政策',
      cookie: 'Cookie政策',
      research: '加速器技術研究',
      techBlog: '技術部落格',
      whitepapers: '白皮書',
      caseStudies: '案例分析',
      networkOptimization: '網路最佳化',
      securityResearch: '安全研究',
      tagline: '專業的海外華人回國網路服務提供商 | 讓距離不再是障礙',
      ownership: '本網頁是屬於 HK Guichao Technology Co., Limited所擁有和全權使用'
    },
    auth: {
      joinTitle: '加入',
      joinBrand: '歸巢',
      subtitle: '專為海外華人打造的回國網路加速服務，讓您在海外也能無縫享受國內的網路體驗。',
      fastConnection: '極速連接',
      fastDesc: '毫秒級延遲，4K影片無緩衝',
      militaryEncryption: '軍用級加密',
      encryptionDesc: 'AES-256位加密，保護隱私安全',
      globalNodes: '全球節點',
      nodesDesc: '覆蓋50+城市，智慧路由最佳化',
      review1: '"歸巢真的太好用了！連接速度超快，看國內影片完全沒問題。"',
      reviewer1: '- 來自美國的用戶 張先生',
      review2: '"在海外工作需要經常查詢企查查和天眼查，之前用國內手機流量又慢又貴。歸巢完美解決了我的痛點，速度快、價格實惠，商務辦公必備！"',
      reviewer2: '- 來自英國的用戶 李女士',
      welcomeTitle: '歡迎使用歸巢',
      welcomeDesc: '請登入或註冊您的帳號',
      login: '登入',
      register: '註冊',
      email: '郵箱',
      emailPlaceholder: '請輸入郵箱位址',
      password: '密碼',
      passwordPlaceholder: '請輸入密碼',
      passwordPlaceholder6: '請設定密碼（至少6位）',
      passwordPlaceholder8: '請輸入密碼（至少8位）',
      newPasswordPlaceholder: '請設定新密碼（至少6位）',
      confirmPassword: '確認密碼',
      confirmPasswordPlaceholder: '請再次輸入密碼',
      rememberMe: '記住我',
      forgotPassword: '忘記密碼？',
      loggingIn: '登入中...',
      loginButton: '登入',
      registerButton: '註冊帳號',
      registering: '註冊中...',
      agreeTerms1: '登入即表示您同意我們的',
      agreeTerms2: '服務條款',
      agreeTerms3: '和',
      agreeTerms4: '隱私協議',
      username: '用戶名',
      usernamePlaceholder: '請輸入用戶名',
      readAgree: '我已閱讀並同意',
      termsLink: '《服務條款》',
      privacyLink: '《隱私協議》',
      orDivider: '或',
      googleLogin: '使用 Google 登入',
      wechatLogin: '使用微信登入',
      // 登入方式
      emailLogin: '郵箱登入',
      phoneLogin: '手機號登入',
      otpLogin: '驗證碼登入',
      phone: '手機號',
      phonePlaceholder: '請輸入手機號',
      otpPlaceholder: '請輸入6位驗證碼',
      getOtp: '獲取驗證碼',
      resendOtp: '重新發送',
      // 登入狀態
      sendingOtp: '發送中...',
      verifying: '驗證中...',
      resetting: '重設中...',
      nextStep: '下一步',
      // 註冊
      phoneRegister: '手機號',
      emailRegister: '郵箱',
      // 忘記密碼
      resetPassword: '重設密碼',
      backToLogin: '返回登入',
      // 提示訊息
      pleaseAgreeTerms: '請先同意服務條款',
      otpSent: '驗證碼已發送',
      checkSms: '請查看手機短信',
      checkEmail: '請查看郵箱',
      sendFailed: '發送失敗',
      loginSuccess: '登入成功',
      verifyFailed: '驗證失敗',
      registerSuccess: '註冊成功',
      resetSuccess: '密碼重設成功',
      useNewPassword: '請使用新密碼登入',
      resetFailed: '重設失敗',
      phoneNotRegistered: '該手機號未註冊',
      emailNotRegistered: '該郵箱未註冊',
      pleaseRegisterFirst: '請先註冊帳號',
      cannotResetPassword: '無法重設密碼，請先註冊帳號',
      passwordMinLength: '密碼至少6個字元',
      invalidEmail: '請輸入有效的郵箱位址',
      invalidPhone: '請輸入有效的手機號碼',
      otpLength: '驗證碼為6位數字'
    },
    download: {
      badge: '📱 客戶端下載',
      title: '全平台',
      titleBrand: '客戶端',
      subtitle: '支援Windows、macOS、iOS、Android等全平台，一個帳號多裝置同時使用',
      smartDownload: '智慧下載',
      viewTutorial: '查看教學',
      downloadBtn: '下載',
      oneClickConnect: '一鍵連接',
      smartRouting: '智慧路由',
      autoStart: '開機自啟',
      nativeSupport: '原生支援',
      menubarControl: '選單列控制',
      systemIntegration: '系統整合',
      appStore: 'App Store 下載',
      shortcuts: '快捷指令',
      siriSupport: 'Siri 支援',
      googlePlay: 'Google Play',
      oneClickShare: '一鍵分享',
      powerSaving: '省電模式',
      routerFirmware: '路由器韌體',
      familyShare: '全家共享',
      deviceControl: '裝置管控',
      timedSwitch: '定時開關',
      browserExtension: '瀏覽器外掛',
      freeUse: '免費使用',
      webProxy: '網頁代理',
      smartSplit: '智慧分流',
      tutorialTitle: '使用',
      tutorialBrand: '教學',
      tutorialSubtitle: '簡單幾步，快速上手',
      windowsTutorial: 'Windows',
      windowsStep1: '下載並執行安裝程式',
      windowsStep2: '按照嚮導完成安裝',
      windowsStep3: '使用帳號密碼登入',
      windowsStep4: '選擇節點並點擊連接',
      mobileTutorial: '手機客戶端',
      mobileStep1: '從應用商店下載應用',
      mobileStep2: '註冊或登入帳號',
      mobileStep3: '允許VPN配置權限',
      mobileStep4: '選擇伺服器開始連接',
      routerTutorial: '路由器',
      routerStep1: '備份原韌體設定',
      routerStep2: '刷入歸巢專用韌體',
      routerStep3: '配置網路連接參數',
      routerStep4: '設定裝置存取控制',
      helpTitle: '需要',
      helpBrand: '幫助？',
      helpSubtitle: '我們的技術支援團隊隨時為您提供幫助',
      downloadIssues: '下載問題',
      downloadIssuesDesc: '下載失敗、安裝錯誤等問題',
      tutorialGuide: '使用教學',
      tutorialGuideDesc: '詳細的圖文和影片教學',
      support247: '24/7客服',
      support247Desc: '全天候線上技術支援',
      contactSupport: '聯絡客服'
    },
    notFound: {
      title: '頁面',
      titleBrand: '走丟了',
      subtitle: '抱歉，您訪問的頁面不存在或已被移動',
      backHome: '返回首頁',
      hint: '或者您可以嘗試使用導覽選單找到您需要的內容'
    },
    privacy: {
      title: '隱私政策',
      subtitle: '歸巢 GuiChao 深知個人資訊對您的重要性，我們將按照法律法規的要求，採取相應安全保護措施，盡力保護您的個人資訊安全可控。',
      updateDate: '更新日期：2024年12月30日',
      effectiveDate: '生效日期：2024年12月30日',
      importantTitle: '特別提示',
      importantText: '請您仔細閱讀本《歸巢隱私政策》（尤其是加粗的內容）並確定了解我們對您個人資訊的處理規則。在閱讀過程中，如您有任何疑問，可透過本政策中約定的聯絡方式與我們聯絡。如您不同意本協議中的任何條款，您應立即停止訪問和使用歸巢服務。',
      tocTitle: '目錄',
      section1: '一、我們如何收集和使用您的個人資訊',
      section2: '二、我們如何使用 Cookie 和同類技術',
      section3: '三、我們如何共享、轉讓、公開披露您的個人資訊',
      section4: '四、我們如何儲存和保護您的個人資訊',
      section5: '五、您管理個人資訊的權利',
      section6: '六、未成年人個人資訊的保護',
      section7: '七、隱私政策的變更和修訂',
      section8: '八、如何聯絡我們',
      introPara1: '歸巢（GuiChao）由 HK Guichao Technology Co., Limited 開發和營運。我們尊重並保護所有使用服務用戶的個人資訊，並將按照法律法規的規定保護用戶資訊及隱私安全。我們致力於維持您對我們的信任，恪守以下原則保護您的個人資訊：權責一致原則、目的明確原則、選擇同意原則、最少夠用原則、確保安全原則、主體參與原則、公開透明原則等。',
      introPara2: '請您在使用我們的產品和服務前，仔細閱讀並了解本隱私政策。一旦您開始使用歸巢服務，即表示您已充分理解並同意本政策。',
      s1h1: '1.1 帳號註冊與登入',
      s1p1: '當您註冊歸巢帳號時，我們會收集您的手機號碼、郵箱位址、密碼等資訊，用於建立帳號和驗證您的身份。您可以選擇透過第三方帳號（如微信、Apple ID）登入，我們將在獲得您授權後收集您的暱稱、頭像等公開資訊。',
      s1h2: '1.2 網路加速服務',
      s1p2: '為了向您提供網路加速服務，我們需要收集您的裝置資訊（裝置型號、作業系統版本、裝置識別碼）、網路資訊（IP位址、網路類型、網路狀態）、連接日誌等。這些資訊用於最佳化服務品質、診斷網路問題和保障服務安全。',
      s1h3: '1.3 支付功能',
      s1p3: '當您購買我們的付費服務時，我們可能會收集您的支付資訊，包括第三方支付帳號（支付寶、微信支付、Apple Pay等）。支付資訊由第三方支付機構收集和處理，我們僅保存必要的訂單資訊。',
      s1h4: '1.4 客戶服務',
      s1p4: '當您聯絡我們的客戶服務時，我們可能會收集您的聯絡方式、問題描述、聊天記錄等，以便為您提供支援和解決問題。',
      s1h5: '1.5 徵得授權同意的例外',
      s1p5: '根據相關法律法規規定，以下情形中收集您的個人資訊無需徵得您的授權同意：',
      s1l1: '與國家安全、國防安全直接相關的',
      s1l2: '與公共安全、公共衛生、重大公共利益直接相關的',
      s1l3: '與犯罪偵查、起訴、審判和判決執行等直接相關的',
      s1l4: '出於維護您或其他個人的生命、財產等重大合法權益但又很難得到本人同意的',
      s1l5: '您自行向社會公眾公開的個人資訊',
      s1l6: '從合法公開披露的資訊中收集的個人資訊',
      s2p1: '為確保網站正常運轉、為您獲得更輕鬆的訪問體驗、向您推薦您可能感興趣的內容，我們會在您的裝置上儲存名為 Cookie 的小資料檔案。Cookie 通常包含識別碼、站點名稱以及一些號碼和字元。',
      s2h1: 'Cookie 的主要用途：',
      s2l1: '保障產品與服務的安全、高效運轉：我們可能會設定認證與保障安全性的 Cookie，使您避免重複登入',
      s2l2: '幫助您獲得更輕鬆的訪問體驗：使用 Cookie 可以幫助您省去重複填寫資訊、輸入搜尋內容的步驟',
      s2l3: '為您推薦、展示個性化內容：我們可能會利用 Cookie 了解您的偏好和使用習慣，進行資料分析，以改善產品服務、推薦個性化內容',
      s2p2: '您可以透過瀏覽器設定管理或刪除 Cookie。但如果您這麼做，可能需要在每次訪問時親自更改用戶設定，並且您之前所記錄的相應資訊也均會被刪除，可能會對您使用的服務的安全性有一定影響。',
      s3h1: '3.1 共享',
      s3p1: '我們不會與任何公司、組織和個人共享您的個人資訊，但以下情況除外：',
      s3l1: '在獲取明確同意的情況下共享：獲得您的明確同意後，我們會與其他方共享您的個人資訊',
      s3l2: '在法定情形下的共享：根據法律法規、訴訟、爭議解決需要，或按行政、司法機關依法提出的要求，我們可能會共享您的個人資訊',
      s3l3: '與關聯公司共享：為便於我們向您提供服務，您的個人資訊可能會與我們的關聯公司共享',
      s3l4: '與授權合作夥伴共享：僅為實現本政策中聲明的目的，我們的某些服務將由授權合作夥伴提供。我們可能會與合作夥伴共享您的某些個人資訊',
      s3h2: '3.2 轉讓',
      s3p2: '我們不會將您的個人資訊轉讓給任何公司、組織和個人，但以下情況除外：在獲取明確同意的情況下轉讓；在涉及合併、收購或破產清算時，如涉及到個人資訊轉讓，我們會要求新的持有您個人資訊的公司、組織繼續受本政策的約束。',
      s3h3: '3.3 公開披露',
      s3p3: '我們僅會在以下情況下，公開披露您的個人資訊：獲得您明確同意後；基於法律的披露：在法律、法律程序、訴訟或政府主管部門強制性要求的情況下，我們可能會公開披露您的個人資訊。',
      s4h1: '4.1 資訊儲存',
      s4p1: '您的個人資訊將儲存於中華人民共和國境內。如需跨境傳輸，我們將會單獨徵得您的授權同意，並確保資料接收方有充足的資料保護能力來保護您的個人資訊。我們只會在達成本政策所述目的所需的期限內保留您的個人資訊，除非法律有強制的存留要求。',
      s4h2: '4.2 資訊安全',
      s4p2: '我們努力為用戶的資訊安全提供保障，以防止資訊的遺失、不當使用、未經授權存取或披露。我們採取的安全措施包括：',
      s4l1: '我們使用各種安全技術以保障資訊的安全。例如，我們會使用加密技術（如 SSL）來保護您的個人資訊',
      s4l2: '我們建立專門的管理制度、流程和組織以保障資訊的安全',
      s4l3: '我們對可能接觸到您的資訊的員工採取嚴格管理，包括採取不同的權限控制',
      s4l4: '我們會採取適當的符合業界標準的安全措施和技術手段儲存和保護您的個人資訊，以防止其遺失、被誤用、受到未授權存取或洩漏、被篡改或毀壞',
      s4h3: '4.3 安全事件處置',
      s4p3: '在不幸發生個人資訊安全事件後，我們將按照法律法規的要求，及時向您告知：安全事件的基本情況和可能的影響、我們已採取或將要採取的處置措施、您可自主防範和降低風險的建議、對您的補救措施等。我們將及時將事件相關情況以郵件、信函、電話、推送通知等方式告知您。',
      s5p1: '按照中國相關的法律、法規、標準，以及其他國家、地區的通行做法，我們保障您對自己的個人資訊行使以下權利：',
      s5h1: '5.1 存取和更新您的個人資訊',
      s5p2: '您有權存取和更新您的個人資訊，法律法規規定的例外情況除外。您可以透過以下方式自行存取和更新您的個人資訊：登入帳號後，在「個人中心」查看和修改您的帳號資訊、個人資料等。',
      s5h2: '5.2 刪除您的個人資訊',
      s5p3: '在以下情形中，您可以向我們提出刪除個人資訊的請求：',
      s5l1: '如果我們處理個人資訊的行為違反法律法規',
      s5l2: '如果我們收集、使用您的個人資訊，卻未徵得您的同意',
      s5l3: '如果我們處理個人資訊的行為違反了與您的約定',
      s5l4: '如果您登出了帳號',
      s5h3: '5.3 登出帳號',
      s5p4: '您可以透過聯絡客服的方式申請登出您的帳號。在您登出帳號後，我們將停止為您提供產品或服務，並根據您的要求刪除您的個人資訊，法律法規另有規定的除外。',
      s5h4: '5.4 撤回同意',
      s5p5: '您可以透過刪除資訊、關閉裝置功能、在網站或軟體中進行隱私設定等方式改變您授權我們繼續收集個人資訊的範圍或撤回您的授權。您也可以透過登出帳號的方式，撤回我們繼續收集您個人資訊的全部授權。',
      s5h5: '5.5 回應您的請求',
      s5p6: '為保障安全，您可能需要提供書面請求，或以其他方式證明您的身份。我們可能會先要求您驗證自己的身份，然後再處理您的請求。我們將在15個工作日內做出答覆。如您不滿意，還可以透過本政策中的聯絡方式投訴。',
      s6p1: '我們非常重視對未成年人個人資訊的保護。若您是18周歲以下的未成年人，在使用我們的產品和/或服務前，應事先取得您家長或法定監護人的書面同意。',
      s6p2: '我們根據國家相關法律法規的規定保護未成年人的個人資訊。對於經父母或法定監護人同意而收集未成年人個人資訊的情況，我們只會在受到法律允許、父母或監護人明確同意或者保護未成年人所必要的情況下使用或公開披露此資訊。',
      s6p3: '如果我們發現自己在未事先獲得可證實的父母或法定監護人同意的情況下收集了未成年人的個人資訊，則會設法盡快刪除相關資料。',
      s7p1: '為了給您提供更好的服務，我們可能會根據產品或服務的更新情況及法律法規的相關要求適時修改本政策的條款，該等修改構成本隱私政策的一部分。',
      s7p2: '如該等更新造成您在本隱私政策下權利的實質減少或重大變更，我們將在本政策生效前透過網站公告、推送通知、彈窗提示或其他方式來通知您，您如果不同意該等變更，可以選擇停止使用我們的產品和服務；如您仍然繼續使用我們的產品和服務，即表示您已充分閱讀、理解並同意受經修訂的本隱私政策的約束。',
      s7p3: '本政策所指的重大變更包括但不限於：',
      s7l1: '我們的服務模式發生重大變化',
      s7l2: '個人資訊共享、轉讓或公開披露的主要對象發生變化',
      s7l3: '您參與個人資訊處理方面的權利及其行使方式發生重大變化',
      s7l4: '我們負責處理個人資訊安全的責任部門、聯絡方式及投訴渠道發生變化',
      s8p1: '如果您對本隱私政策有任何疑問、意見或建議，或您在使用我們的服務時遇到任何與個人資訊保護相關的問題，您可以透過以下方式與我們聯絡：',
      s8p2: '一般情況下，我們將在15個工作日內回覆。如果您對我們的回覆不滿意，特別是您認為我們的個人資訊處理行為損害了您的合法權益，您還可以透過向被告住所地有管轄權的法院提起訴訟來尋求解決方案。',
      contactEmail: '電子郵件',
      companyName: '公司名稱',
      thanksTitle: '再次感謝您對歸巢的信任！',
      thanksText: '我們將竭誠為您提供安全、可靠的網路加速服務，並持續保護您的個人資訊安全。'
    },
    cookie: {
      title: 'Cookie政策',
      lastUpdated: '最後更新日期：2024年1月',
      intro: '本Cookie政策說明AI智聯加速器（「我們」或「本服務」）如何使用Cookie及類似技術來識別您訪問我們的網站、應用程式和服務時的身份。本政策解釋了這些技術是什麼，我們為何使用它們，以及您如何控制它們的使用。',
      
      whatAreCookies: {
        title: '什麼是Cookie？',
        content: 'Cookie是當您訪問網站時放置在您的電腦或行動裝置上的小型資料檔案。網站所有者廣泛使用Cookie來使其網站運行或更高效地運行，以及提供報告資訊。網站所有者設定的Cookie稱為「第一方Cookie」。由網站所有者以外的各方設定的Cookie稱為「第三方Cookie」。第三方Cookie啟用可在網站上或透過網站提供的第三方功能或功能（例如廣告、互動內容和分析）。設定這些第三方Cookie的各方可以在您的電腦訪問相關網站以及訪問某些其他網站時識別您的電腦。'
      },
      
      whyWeUseCookies: {
        title: '我們為什麼使用Cookie？',
        content: '我們使用第一方和第三方Cookie的原因有多種。出於技術原因，我們的網站需要某些Cookie才能運行，我們將其稱為「必需」或「絕對必要」Cookie。其他Cookie還使我們能夠追蹤和定位用戶的興趣，以增強我們線上資產上的體驗。第三方透過我們的網站提供Cookie，用於廣告、分析和其他目的。'
      },
      
      typesOfCookies: {
        title: '我們使用的Cookie類型',
        essential: {
          title: '必需Cookie',
          description: '這些Cookie對於向您提供透過我們的網站可用的服務以及使用其某些功能（例如存取安全區域）是絕對必要的。由於這些Cookie對於向您提供服務是絕對必要的，因此您無法拒絕它們而不影響我們網站的功能。您可以透過更改瀏覽器設定來阻止或刪除它們，但這可能會影響網站的某些功能。'
        },
        performance: {
          title: '效能和功能Cookie',
          description: '這些Cookie用於增強我們網站的效能和功能，但對其使用並非必不可少。但是，如果沒有這些Cookie，某些功能（如影片）可能會變得不可用，或者您將需要每次訪問網站時輸入您的登入詳細資訊，因為我們無法記住您之前已登入。'
        },
        analytics: {
          title: '分析和定制Cookie',
          description: '這些Cookie收集用於匯總分析我們網站使用情況的資訊，以便我們可以改善訪問者體驗。它們還允許我們測試新想法並監控和改善我們網站的效能。例如，我們使用這些Cookie來計算網站的訪問者數量並查看訪問者如何瀏覽網站。我們使用這些資訊來改進我們網站的工作方式，例如，透過確保用戶輕鬆找到所需內容。'
        },
        advertising: {
          title: '廣告Cookie',
          description: '這些Cookie用於使廣告資訊與您更相關。它們執行諸如防止相同廣告不斷重新出現、確保廣告正確顯示給廣告主以及在某些情況下根據您的興趣選擇廣告等功能。'
        }
      },
      
      howToControl: {
        title: '如何控制Cookie？',
        content: '您有權決定是否接受或拒絕Cookie。您可以透過在Cookie同意管理器中設定您的首選項來行使您的Cookie權利。Cookie同意管理器允許您選擇接受或拒絕哪些類別的Cookie。必需Cookie不能被拒絕，因為它們對於向您提供服務是絕對必要的。',
        browserSettings: '如果您選擇拒絕Cookie，您仍可以使用我們的網站，但您對網站某些功能和區域的存取可能會受到限制。您還可以設定或修改Web瀏覽器控制元件以接受或拒絕Cookie。'
      },
      
      specificCookies: {
        title: '我們使用的具體Cookie',
        sessionCookies: '工作階段Cookie：這些Cookie在您瀏覽工作階段期間臨時儲存資訊。它們在您關閉瀏覽器時被刪除。',
        persistentCookies: '持久Cookie：這些Cookie在您的裝置上保留更長時間，用於記住您的偏好設定和登入資訊。',
        securityCookies: '安全Cookie：這些Cookie用於驗證用戶身份、防止欺詐性使用登入憑證，並保護用戶資料免受未經授權方的侵害。'
      },
      
      thirdParty: {
        title: '第三方Cookie',
        content: '除了我們自己的Cookie之外，我們還可能使用各種第三方Cookie來報告我們網站的使用統計資訊、投放廣告等。這些第三方服務提供商可能會使用Cookie來收集您訪問我們網站和其他網站的資訊。我們不控制這些第三方Cookie，它們的使用受提供它們的公司的隱私政策約束。'
      },
      
      updates: {
        title: '本Cookie政策的更新',
        content: '我們可能會不時更新本Cookie政策，以反映我們使用的Cookie的更改或出於其他營運、法律或監管原因。因此，請定期重新訪問本Cookie政策以了解我們對Cookie和相關技術的使用情況。本Cookie政策頂部的日期表示其最後更新時間。'
      },
      
      contact: {
        title: '聯絡我們',
        content: '如果您對我們使用Cookie或其他技術有任何疑問，請透過以下方式與我們聯絡：',
        email: '郵箱：support@ai-accelerator.com'
      }
    },
    terms: {
      title: '服務條款',
      lastUpdate: '最後更新日期：2024年1月',
      importantTitle: '重要提示',
      importantText: '在使用我們的服務之前，請仔細閱讀並理解本服務條款。使用我們的服務即表示您同意接受本條款的約束。',
      section1Title: '1. 服務說明',
      s1p1: '我們提供的網路加速服務旨在最佳化您的網路連接體驗。服務內容包括但不限於：',
      s1l1: '網路連接加速和最佳化',
      s1l2: '多節點伺服器支援',
      s1l3: '資料傳輸加密',
      s1l4: '技術支援和客戶服務',
      s1p2: '我們保留隨時修改、暫停或終止部分或全部服務的權利，恕不另行通知。',
      section2Title: '2. 用戶責任與義務',
      s2p1: '作為服務用戶，您同意：',
      s2l1: '提供真實、準確的註冊資訊',
      s2l2: '妥善保管帳戶資訊和密碼',
      s2l3: '遵守所有適用的法律法規',
      s2l4: '不得將服務用於任何非法或未授權的目的',
      s2l5: '不得干擾或破壞服務的正常運行',
      s2l6: '不得嘗試未經授權存取我們的系統或網路',
      section3Title: '3. 禁止行為',
      s3p1: '使用我們的服務時，嚴禁從事以下行為：',
      s3l1: '發布、傳輸任何違法、有害、威脅、辱罵、騷擾、侵權、誹謗、粗俗、淫穢或其他令人反感的內容',
      s3l2: '侵犯他人的智慧財產權或其他合法權益',
      s3l3: '傳播病毒、惡意程式碼或其他可能損害系統的內容',
      s3l4: '進行任何形式的網路攻擊或惡意行為',
      s3l5: '濫用服務資源或影響其他用戶的正常使用',
      s3l6: '未經授權共享帳戶或轉售服務',
      section4Title: '4. 智慧財產權',
      s4p1: '本服務及其所有相關內容（包括但不限於軟體、文字、圖片、標誌、音訊、影片）的智慧財產權歸我們或相關權利人所有。',
      s4p2: '未經明確書面許可，您不得複製、修改、傳播、展示或以其他方式使用這些內容。',
      section5Title: '5. 免責聲明',
      s5p1: '我們將盡力提供穩定可靠的服務，但不對以下情況承擔責任：',
      s5l1: '因不可抗力、網路故障、系統維護等原因導致的服務中斷',
      s5l2: '因用戶自身原因（如裝置故障、網路問題）造成的使用障礙',
      s5l3: '第三方服務或內容的品質、安全性或合法性',
      s5l4: '因用戶違反本條款或相關法律法規造成的任何損失',
      s5p2: '服務按「現狀」和「可用」基礎提供，不提供任何明示或暗示的保證。',
      section6Title: '6. 費用與支付',
      s6p1: '部分服務需要付費使用。具體費用標準以網站公布的價格為準。',
      s6l1: '所有費用均以人民幣計價',
      s6l2: '支付後不支援退款，除非法律另有規定',
      s6l3: '我們保留隨時調整價格的權利',
      s6l4: '如因您的原因導致支付失敗，我們不承擔責任',
      section7Title: '7. 帳戶終止',
      s7p1: '在以下情況下，我們有權暫停或終止您的帳戶：',
      s7l1: '您違反本服務條款的任何規定',
      s7l2: '您的行為可能給我們或其他用戶帶來法律風險',
      s7l3: '您長期未使用帳戶（超過12個月）',
      s7l4: '應司法機關或政府部門的要求',
      s7p2: '帳戶終止後，您將無法存取服務，且我們不對任何資料遺失承擔責任。',
      section8Title: '8. 條款變更',
      s8p1: '我們保留隨時修改本服務條款的權利。重大變更將透過網站公告或電子郵件通知您。',
      s8p2: '繼續使用服務即表示您接受修改後的條款。如不同意變更，請停止使用服務。',
      section9Title: '9. 爭議解決',
      s9p1: '本條款受中華人民共和國法律管轄。因本條款引起的任何爭議，雙方應首先透過友好協商解決。',
      s9p2: '協商不成的，任何一方均可向我們所在地有管轄權的人民法院提起訴訟。',
      section10Title: '10. 聯絡我們',
      s10p1: '如您對本服務條款有任何疑問或建議，請透過以下方式聯絡我們：',
      contactEmail: '郵箱：support@example.com',
      contactService: '線上客服：工作日 9:00-18:00',
      agreementText: '使用我們的服務即表示您已閱讀、理解並同意遵守本服務條款的所有內容。'
    },
    research: {
      title: '加速器技術研究',
      subtitle: '探索網路加速技術的前沿，分享我們的技術洞察和實踐經驗',
      searchPlaceholder: '搜尋文章...',
      noArticlesFound: '未找到相關文章',
      noArticlesPublished: '暫無文章發布',
      readMore: '閱讀全文',
      navTitle: '技術研究',
      navTitleEn: 'Research',
      categories: {
        tech_blog: '技術部落格',
        whitepaper: '白皮書',
        case_study: '案例分析',
        network_optimization: '網路最佳化',
        security_research: '安全研究'
      }
    },
    profile: {
      title: '帳號管理',
      subtitle: '管理您的個人資訊和帳號設定',
      loading: '載入中...',
      accountInfo: '帳號資訊',
      purchases: '購買記錄',
      security: '安全設定',
      deleteAccount: '刪除帳號',
      accountInfoTitle: '帳號資訊',
      accountInfoDesc: '查看您的帳號狀態和訂閱資訊',
      emailAddress: '郵箱位址',
      phoneNumber: '手機號碼',
      notSet: '未設定',
      memberStatus: '會員狀態',
      vipMember: 'VIP會員',
      regularUser: '普通用戶',
      vipRemaining: 'VIP剩餘時長',
      days: '天',
      renew: '續費',
      purchase: '購買',
      expiryTime: '到期時間',
      vipBenefits: 'VIP會員權益',
      aiAdvanced: 'AI高級功能',
      priorityProcessing: '優先處理',
      exclusiveSupport: '專屬客服',
      exclusiveContent: '獨家內容',
      editEmail: '修改郵箱位址',
      editEmailDesc: '輸入新郵箱位址後，我們將傳送驗證郵件到新郵箱',
      newEmail: '新郵箱位址',
      newEmailPlaceholder: '請輸入新郵箱位址',
      verificationSent: '驗證郵件已傳送到',
      checkEmail: '，請檢查郵箱並點擊驗證連結',
      cancel: '取消',
      sending: '傳送中...',
      sendVerificationEmail: '傳送驗證郵件',
      done: '完成',
      editPhone: '修改手機號碼',
      editPhoneDesc: '輸入新手機號碼後，我們將傳送驗證碼到新手機',
      newPhone: '新手機號碼',
      newPhonePlaceholder: '請輸入新手機號碼',
      verificationCode: '驗證碼',
      verificationCodePlaceholder: '請輸入6位驗證碼',
      sendCode: '傳送驗證碼',
      verifying: '驗證中...',
      verifyAndUpdate: '驗證並更新',
      purchasesTitle: '購買記錄',
      purchasesDesc: '查看您的所有購買歷史',
      orderDate: '訂單日期',
      orderNumber: '訂單編號',
      memberType: '會員類型',
      memberDuration: '會員時長',
      acquisitionMethod: '獲取途徑',
      noPurchases: '暫無購買記錄',
      permanent: '永久',
      gifted: '贈送',
      purchased: '購買',
      securityTitle: '安全設定',
      securityDesc: '管理您的密碼和帳號安全',
      changePassword: '修改密碼',
      currentPassword: '目前密碼',
      currentPasswordPlaceholder: '請輸入目前密碼',
      newPassword: '新密碼',
      newPasswordPlaceholder: '請輸入新密碼',
      confirmNewPassword: '確認新密碼',
      confirmNewPasswordPlaceholder: '請再次輸入新密碼',
      changing: '修改中...',
      deleteAccountAgreement: '帳號登出協議',
      agreementSection1: '一、登出前需滿足的條件',
      agreementSection1Item1: '已取消所有自動訂閱服務，確保無未完成的訂閱套餐；',
      agreementSection1Item2: '帳號目前不存在任何糾紛、投訴或被舉報的情況，且未違反用戶協議。',
      agreementSection2: '二、登出流程說明',
      agreementSection2Item1: '確認滿足上述條件後，可提交帳號刪除申請，提交後無法撤回；',
      agreementSection2Item2: '申請提交後帳號將立即登出，所有資料將被清除。',
      agreementSection3: '三、資料刪除與保留說明',
      agreementSection3Item1: '帳號登出後，我們將刪除帳號註冊時使用的郵箱、手機號及密碼；',
      agreementSection3Item2: '同時刪除訂單記錄、登入記錄及使用GUICHAO服務的歷史資料；',
      agreementSection3Item3: '帳號剩餘會員天數等所有權益將清空，無法恢復。',
      agreementSection4: '四、其他提示',
      agreementSection4Item1: '登出後，原帳號繫結的手機號、郵箱及第三方登入資訊將被釋放，可重新用於註冊或繫結；',
      agreementSection4Item2: '已登出帳號無法再次登入或恢復，重新註冊亦無法享受此前已獲得的新用戶福利；',
      agreementSection4Item3: '如需再次使用GUICHAO服務，需重新註冊帳號。',
      agreementCheckbox: '我已仔細閱讀並理解《帳號登出協議》的全部內容，明確知曉登出後的所有後果，並自願申請登出帳號',
      deleteWarning: '警告：此操作無法撤銷',
      deleteWarningDesc: '刪除帳號將永久刪除以下內容：',
      deleteWarningItem1: '您的所有個人資料',
      deleteWarningItem2: '購買記錄和訂閱資訊',
      deleteWarningItem3: '帳號相關的所有資料',
      confirmDelete: '確認刪除帳號',
      confirmDeleteDesc: '為了確保帳號安全，請輸入您的登入密碼以繼續刪除操作。',
      loginPassword: '登入密碼',
      loginPasswordPlaceholder: '請輸入您的登入密碼',
      deleteNote: '此操作無法撤銷，將永久刪除您的帳號及所有相關資料。',
      deleting: '刪除中...',
      confirmDeleteBtn: '確認刪除',
      loadFailed: '載入失敗',
      loadPurchasesFailed: '載入購買記錄失敗',
      saveFailed: '儲存失敗',
      saveSuccess: '儲存成功',
      profileUpdated: '您的個人資訊已更新',
      oldPasswordError: '舊密碼錯誤',
      oldPasswordErrorDesc: '您輸入的目前密碼不正確，請重試',
      changeSuccess: '修改成功',
      passwordUpdated: '您的密碼已更新',
      changeFailed: '修改失敗',
      loggedOut: '已退出登入',
      logoutSuccess: '您已成功退出帳號',
      logoutFailed: '退出失敗',
      enterPassword: '請輸入密碼',
      enterPasswordDesc: '為了安全起見，請輸入您的登入密碼',
      passwordError: '密碼錯誤',
      passwordErrorDesc: '您輸入的密碼不正確，請重試',
      verificationSuccess: '驗證成功',
      deleteRequestSubmitted: '您的帳號刪除請求已提交，請聯絡管理員完成刪除',
      verificationFailed: '驗證失敗',
      enterContact: '請輸入新的聯絡方式',
      emailVerificationSent: '驗證郵件已傳送',
      checkNewEmail: '請檢查您的新郵箱並點擊驗證連結',
      codeVerificationSent: '驗證碼已傳送',
      checkSMS: '請檢查您的手機簡訊',
      sendFailed: '傳送失敗',
      enterCode: '請輸入驗證碼',
      phoneUpdated: '手機號已更新',
      phoneUpdateSuccess: '您的手機號已成功修改',
      emailVerification: '郵箱驗證',
      clickEmailLink: '請點擊郵件中的驗證連結完成郵箱更新',
      usernameMin: '用戶名至少2個字元',
      usernameMax: '用戶名最多50個字元',
      invalidURL: '請輸入有效的URL',
      bioMax: '簡介最多500個字元',
      enterCurrentPassword: '請輸入目前密碼',
      passwordMin: '密碼至少6個字元',
      passwordMismatch: '兩次密碼輸入不一致',
      noSubscription: '未設定訂閱',
      expired: '已過期'
    }
  }
};
