import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'zh' || saved === 'en') ? saved : 'zh';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  zh: {
    header: {
      tagline: '专为海外华人设计',
      taglineEn: 'Built for Chinese Abroad',
      home: '首页',
      homeEn: 'Home',
      features: '产品特色',
      featuresEn: 'Features',
      pricing: '套餐价格',
      pricingEn: 'Pricing',
      download: '下载客户端',
      downloadEn: 'Download',
      contact: '联系我们',
      contactEn: 'Contact',
      login: '登录',
      freeTrial: '免费试用'
    },
    hero: {
      title: '倦鸟归巢 一键回国',
      subtitle: '专业的回国网络加速服务，让海外华人轻松访问国内网络资源',
      badge: '高速稳定 • 安全可靠 • 一键连接',
      security: '企业级安全',
      securityEn: 'Enterprise Security',
      latency: '毫秒级延迟',
      latencyEn: 'Ultra Low Latency',
      network: '全球节点',
      networkEn: 'Global Network',
      startTrial: '立即免费试用',
      downloadClient: '下载客户端',
      windows: 'Windows',
      windowsDesc: 'PC客户端',
      macos: 'macOS',
      macosDesc: 'Mac客户端',
      ios: 'iOS',
      iosDesc: 'iPhone/iPad',
      android: 'Android',
      androidDesc: '安卓手机',
      browser: '浏览器',
      browserDesc: 'Chrome插件',
      clickDownload: '点击下载'
    },
    features: {
      badge: '⚡ 产品特色',
      title: '为什么选择',
      titleBrand: '归巢',
      subtitle: '专为海外华人打造的回国网络解决方案，让您在海外也能无缝享受国内的网络服务',
      speed: '极速连接',
      speedDesc: '采用最新加速技术，连接速度提升300%，观看4K视频无缓冲',
      speedHighlight: '毫秒级延迟',
      encryption: '军用级加密',
      encryptionDesc: 'AES-256位加密技术，保护您的网络安全和隐私数据',
      encryptionHighlight: '银行级安全',
      nodes: '全球节点',
      nodesDesc: '覆盖全球50+城市，智能选择最优线路，确保连接稳定',
      nodesHighlight: '50+节点',
      devices: '多设备支持',
      devicesDesc: '一个账户支持10台设备同时使用，全家共享无忧',
      devicesHighlight: '10台设备',
      uptime: '7x24在线',
      uptimeDesc: '99.9%服务可用性，全年无休为您提供稳定的网络服务',
      uptimeHighlight: '99.9%稳定',
      support: '专业客服',
      supportDesc: '中文技术支持团队，微信群实时答疑，问题快速解决',
      supportHighlight: '中文支持',
      stat1: '1M+',
      stat1Label: '用户信赖',
      stat1En: 'Active Users',
      stat2: '50+',
      stat2Label: '全球节点',
      stat2En: 'Global Nodes',
      stat3: '99.9%',
      stat3Label: '稳定运行',
      stat3En: 'Uptime SLA',
      stat4: '24/7',
      stat4Label: '技术支持',
      stat4En: 'Support'
    },
    scenarios: {
      title: '支持加速多种场景',
      subtitle: '无论是娱乐、学习还是工作，归巢为您提供全方位的加速支持',
      video: '影音娱乐',
      videoDesc: '流畅观看国内视频平台，享受高清流媒体',
      sports: '体育赛事',
      sportsDesc: '实时观看大陆体育赛事直播，不错过精彩瞬间',
      gaming: '国服游戏',
      gamingDesc: '降低游戏延迟，畅玩国服热门游戏',
      education: '远程学习',
      educationDesc: '稳定连接大陆教育平台，在线学习无忧',
      meeting: '办公会议',
      meetingDesc: '高效跨境视频会议，团队协作更流畅',
      streaming: '达人直播',
      streamingDesc: '高清流畅直播推流，内容创作更专业'
    },
    pricing: {
      badge: '💰 套餐价格',
      title: '选择适合您的',
      titleBrand: '套餐',
      subtitle: '灵活的价格方案，满足不同用户需求。支持微信、支付宝、USDT等多种支付方式',
      discount: '🎉 年付用户享8折优惠，可节省高达HK$140',
      popular: '🔥 最受欢迎',
      trial: '体验版',
      trialDesc: '新用户专享，体验归巢服务',
      trialPrice: '免费',
      trialPeriod: '3天试用',
      trialButton: '立即试用',
      standard: '标准版',
      standardDesc: '个人用户推荐，性价比之选',
      standardButton: '选择标准版',
      premium: '旗舰版',
      premiumDesc: '家庭/企业用户首选',
      premiumButton: '选择旗舰版',
      selectPlan: '点击选择',
      guarantee1: '7天无忧退款',
      guarantee1Desc: '不满意随时退款',
      guarantee2: '24小时客服',
      guarantee2Desc: '随时为您解答问题',
      guarantee3: '无限流量',
      guarantee3Desc: '畅享高速网络体验',
      paymentTitle: '选择支付方式',
      paymentSecurity: '支付过程安全加密，支持7天无忧退款',
      cancel: '取消',
      wechat: '微信支付',
      wechatDesc: '使用微信快速支付',
      alipayHK: '香港支付宝',
      alipayHKDesc: '支付宝(香港)便捷支付',
      paypal: 'PayPal',
      paypalDesc: '全球通用在线支付',
      googlePay: 'Google Pay',
      googlePayDesc: 'Google 快速支付',
      applePay: 'Apple Pay',
      applePayDesc: 'Apple 设备专用支付',
      stripe: 'Stripe',
      stripeDesc: '信用卡/借记卡支付'
    },
    footer: {
      brand: '专为海外华人打造的回国网络加速服务，让您在海外也能无缝享受国内的网络体验。',
      wechatGroup: '微信群',
      email: '邮箱',
      products: '产品服务',
      features: '产品特色',
      pricing: '套餐价格',
      freeTrial: '免费试用',
      nodeStatus: '节点状态',
      speedTest: '速度测试',
      download: '客户端下载',
      windowsClient: 'Windows 客户端',
      macosClient: 'macOS 客户端',
      iosApp: 'iOS 应用',
      androidApp: 'Android 应用',
      webVersion: '网页版',
      support: '帮助支持',
      tutorial: '使用教程',
      faq: '常见问题',
      contactSupport: '联系客服',
      feedback: '意见反馈',
      terms: '服务条款',
      newsletter: '最新动态',
      emailPlaceholder: '输入邮箱地址',
      subscribe: '订阅',
      copyright: '© 2024 归巢 GuiChao.win. 保留所有权利。',
      privacy: '隐私政策',
      cookie: 'Cookie政策',
      tagline: '专业的海外华人回国网络服务提供商 | 让距离不再是障碍',
      ownership: '本网页是属于 HK Guichao Technology Co., Limited所拥有和全权使用'
    },
    auth: {
      joinTitle: '加入',
      joinBrand: '归巢',
      subtitle: '专为海外华人打造的回国网络加速服务，让您在海外也能无缝享受国内的网络体验。',
      fastConnection: '极速连接',
      fastDesc: '毫秒级延迟，4K视频无缓冲',
      militaryEncryption: '军用级加密',
      encryptionDesc: 'AES-256位加密，保护隐私安全',
      globalNodes: '全球节点',
      nodesDesc: '覆盖50+城市，智能路由优化',
      review1: '"归巢真的太好用了！连接速度超快，看国内视频完全没问题。"',
      reviewer1: '- 来自美国的用户 张先生',
      review2: '"在海外工作需要经常查询企查查和天眼查，之前用国内手机流量又慢又贵。归巢完美解决了我的痛点，速度快、价格实惠，商务办公必备！"',
      reviewer2: '- 来自英国的用户 李女士',
      welcomeTitle: '欢迎使用归巢',
      welcomeDesc: '请登录或注册您的账号',
      login: '登录',
      register: '注册',
      email: '邮箱',
      emailPlaceholder: '请输入邮箱地址',
      password: '密码',
      passwordPlaceholder: '请输入密码',
      passwordPlaceholder8: '请输入密码（至少8位）',
      confirmPassword: '确认密码',
      confirmPasswordPlaceholder: '请再次输入密码',
      rememberMe: '记住我',
      forgotPassword: '忘记密码？',
      loggingIn: '登录中...',
      loginButton: '登录',
      registerButton: '注册账号',
      registering: '注册中...',
      agreeTerms1: '登录即表示您同意我们的',
      agreeTerms2: '服务条款',
      agreeTerms3: '和',
      agreeTerms4: '隐私协议',
      username: '用户名',
      usernamePlaceholder: '请输入用户名',
      readAgree: '我已阅读并同意',
      termsLink: '《服务条款》',
      privacyLink: '《隐私协议》',
      orDivider: '或',
      googleLogin: '使用 Google 登录',
      wechatLogin: '使用微信登录'
    },
    download: {
      badge: '📱 客户端下载',
      title: '全平台',
      titleBrand: '客户端',
      subtitle: '支持Windows、macOS、iOS、Android等全平台，一个账号多设备同时使用',
      smartDownload: '智能下载',
      viewTutorial: '查看教程',
      downloadBtn: '下载',
      oneClickConnect: '一键连接',
      smartRouting: '智能路由',
      autoStart: '开机自启',
      nativeSupport: '原生支持',
      menubarControl: '菜单栏控制',
      systemIntegration: '系统集成',
      appStore: 'App Store 下载',
      shortcuts: '快捷指令',
      siriSupport: 'Siri 支持',
      googlePlay: 'Google Play',
      oneClickShare: '一键分享',
      powerSaving: '省电模式',
      routerFirmware: '路由器固件',
      familyShare: '全家共享',
      deviceControl: '设备管控',
      timedSwitch: '定时开关',
      browserExtension: '浏览器插件',
      freeUse: '免费使用',
      webProxy: '网页代理',
      smartSplit: '智能分流',
      tutorialTitle: '使用',
      tutorialBrand: '教程',
      tutorialSubtitle: '简单几步，快速上手',
      windowsTutorial: 'Windows',
      windowsStep1: '下载并运行安装程序',
      windowsStep2: '按照向导完成安装',
      windowsStep3: '使用账号密码登录',
      windowsStep4: '选择节点并点击连接',
      mobileTutorial: '手机客户端',
      mobileStep1: '从应用商店下载应用',
      mobileStep2: '注册或登录账号',
      mobileStep3: '允许VPN配置权限',
      mobileStep4: '选择服务器开始连接',
      routerTutorial: '路由器',
      routerStep1: '备份原固件设置',
      routerStep2: '刷入归巢专用固件',
      routerStep3: '配置网络连接参数',
      routerStep4: '设置设备访问控制',
      helpTitle: '需要',
      helpBrand: '帮助？',
      helpSubtitle: '我们的技术支持团队随时为您提供帮助',
      downloadIssues: '下载问题',
      downloadIssuesDesc: '下载失败、安装错误等问题',
      tutorialGuide: '使用教程',
      tutorialGuideDesc: '详细的图文和视频教程',
      support247: '24/7客服',
      support247Desc: '全天候在线技术支持',
      contactSupport: '联系客服'
    },
    notFound: {
      title: '页面',
      titleBrand: '走丢了',
      subtitle: '抱歉，您访问的页面不存在或已被移动',
      backHome: '返回首页',
      hint: '或者您可以尝试使用导航菜单找到您需要的内容'
    },
    privacy: {
      title: '隐私政策',
      subtitle: '归巢 GuiChao 深知个人信息对您的重要性，我们将按照法律法规的要求，采取相应安全保护措施，尽力保护您的个人信息安全可控。',
      updateDate: '更新日期：2024年12月30日',
      effectiveDate: '生效日期：2024年12月30日',
      importantTitle: '特别提示',
      importantText: '请您仔细阅读本《归巢隐私政策》（尤其是加粗的内容）并确定了解我们对您个人信息的处理规则。在阅读过程中，如您有任何疑问，可通过本政策中约定的联系方式与我们联系。如您不同意本协议中的任何条款，您应立即停止访问和使用归巢服务。',
      tocTitle: '目录',
      section1: '一、我们如何收集和使用您的个人信息',
      section2: '二、我们如何使用 Cookie 和同类技术',
      section3: '三、我们如何共享、转让、公开披露您的个人信息',
      section4: '四、我们如何存储和保护您的个人信息',
      section5: '五、您管理个人信息的权利',
      section6: '六、未成年人个人信息的保护',
      section7: '七、隐私政策的变更和修订',
      section8: '八、如何联系我们',
      contactEmail: '电子邮件',
      companyName: '公司名称',
      thanksTitle: '再次感谢您对归巢的信任！',
      thanksText: '我们将竭诚为您提供安全、可靠的网络加速服务，并持续保护您的个人信息安全。'
    },
    terms: {
      title: '服务条款',
      lastUpdate: '最后更新日期：2024年1月',
      importantTitle: '重要提示',
      importantText: '在使用我们的服务之前，请仔细阅读并理解本服务条款。使用我们的服务即表示您同意接受本条款的约束。',
      section1Title: '1. 服务说明',
      section2Title: '2. 用户责任与义务',
      section3Title: '3. 禁止行为',
      section4Title: '4. 知识产权',
      section5Title: '5. 免责声明',
      section6Title: '6. 费用与支付',
      section7Title: '7. 账户终止',
      section8Title: '8. 条款变更',
      section9Title: '9. 争议解决',
      section10Title: '10. 联系我们',
      contactEmail: '邮箱：support@example.com',
      contactService: '在线客服：工作日 9:00-18:00',
      agreementText: '使用我们的服务即表示您已阅读、理解并同意遵守本服务条款的所有内容。'
    }
  },
  en: {
    header: {
      tagline: 'Built for Chinese Abroad',
      taglineEn: '专为海外华人设计',
      home: 'Home',
      homeEn: '首页',
      features: 'Features',
      featuresEn: '产品特色',
      pricing: 'Pricing',
      pricingEn: '套餐价格',
      download: 'Download',
      downloadEn: '下载客户端',
      contact: 'Contact',
      contactEn: '联系我们',
      login: 'Login',
      freeTrial: 'Free Trial'
    },
    hero: {
      title: 'Home Network Access Simplified',
      subtitle: 'Professional network acceleration service for Chinese living abroad to easily access domestic network resources',
      badge: 'Fast & Stable • Secure & Reliable • One-Click Connect',
      security: 'Enterprise Security',
      securityEn: '企业级安全',
      latency: 'Ultra Low Latency',
      latencyEn: '毫秒级延迟',
      network: 'Global Network',
      networkEn: '全球节点',
      startTrial: 'Start Free Trial',
      downloadClient: 'Download Client',
      windows: 'Windows',
      windowsDesc: 'PC Client',
      macos: 'macOS',
      macosDesc: 'Mac Client',
      ios: 'iOS',
      iosDesc: 'iPhone/iPad',
      android: 'Android',
      androidDesc: 'Android Phone',
      browser: 'Browser',
      browserDesc: 'Chrome Extension',
      clickDownload: 'Click to Download'
    },
    features: {
      badge: '⚡ Features',
      title: 'Why Choose',
      titleBrand: 'GuiChao',
      subtitle: 'Network solution designed for overseas Chinese, enabling seamless access to domestic network services',
      speed: 'Lightning Fast',
      speedDesc: 'Latest acceleration technology, 300% speed boost, buffer-free 4K streaming',
      speedHighlight: 'Ultra Low Latency',
      encryption: 'Military Grade Encryption',
      encryptionDesc: 'AES-256 encryption protects your network security and privacy',
      encryptionHighlight: 'Bank Level Security',
      nodes: 'Global Network',
      nodesDesc: '50+ cities worldwide, intelligent routing for stable connections',
      nodesHighlight: '50+ Nodes',
      devices: 'Multi-Device Support',
      devicesDesc: 'One account supports 10 devices simultaneously, family sharing made easy',
      devicesHighlight: '10 Devices',
      uptime: '7x24 Online',
      uptimeDesc: '99.9% service availability, year-round stable network service',
      uptimeHighlight: '99.9% Uptime',
      support: 'Professional Support',
      supportDesc: 'Chinese technical support team, WeChat group real-time assistance',
      supportHighlight: 'Chinese Support',
      stat1: '1M+',
      stat1Label: 'Active Users',
      stat1En: '用户信赖',
      stat2: '50+',
      stat2Label: 'Global Nodes',
      stat2En: '全球节点',
      stat3: '99.9%',
      stat3Label: 'Uptime SLA',
      stat3En: '稳定运行',
      stat4: '24/7',
      stat4Label: 'Support',
      stat4En: '技术支持'
    },
    scenarios: {
      title: 'Multiple Acceleration Scenarios',
      subtitle: 'Whether entertainment, learning or work, GuiChao provides comprehensive acceleration support',
      video: 'Video Entertainment',
      videoDesc: 'Smooth streaming from domestic video platforms, enjoy HD content',
      sports: 'Sports Events',
      sportsDesc: 'Watch mainland sports broadcasts in real-time, never miss exciting moments',
      gaming: 'Domestic Gaming',
      gamingDesc: 'Reduce game latency, enjoy popular domestic games smoothly',
      education: 'Remote Learning',
      educationDesc: 'Stable connection to mainland education platforms, worry-free online learning',
      meeting: 'Business Meetings',
      meetingDesc: 'Efficient cross-border video conferences, smoother team collaboration',
      streaming: 'Live Streaming',
      streamingDesc: 'HD smooth streaming, more professional content creation'
    },
    pricing: {
      badge: '💰 Pricing',
      title: 'Choose Your',
      titleBrand: 'Plan',
      subtitle: 'Flexible pricing plans to meet different user needs. Supports WeChat Pay, Alipay, USDT and more',
      discount: '🎉 Annual plan users enjoy 20% off, save up to HK$140',
      popular: '🔥 Most Popular',
      trial: 'Trial',
      trialDesc: 'New user exclusive, experience GuiChao service',
      trialPrice: 'Free',
      trialPeriod: '3-day trial',
      trialButton: 'Start Trial',
      standard: 'Standard',
      standardDesc: 'Recommended for individual users, best value',
      standardButton: 'Choose Standard',
      premium: 'Premium',
      premiumDesc: 'Best choice for families/enterprises',
      premiumButton: 'Choose Premium',
      selectPlan: 'Click to Select',
      guarantee1: '7-Day Money Back',
      guarantee1Desc: 'Refund anytime if unsatisfied',
      guarantee2: '24-Hour Support',
      guarantee2Desc: 'Answer your questions anytime',
      guarantee3: 'Unlimited Data',
      guarantee3Desc: 'Enjoy high-speed network experience',
      paymentTitle: 'Select Payment Method',
      paymentSecurity: 'Secure encrypted payment, supports 7-day money-back guarantee',
      cancel: 'Cancel',
      wechat: 'WeChat Pay',
      wechatDesc: 'Quick payment with WeChat',
      alipayHK: 'Alipay HK',
      alipayHKDesc: 'Convenient payment with Alipay (Hong Kong)',
      paypal: 'PayPal',
      paypalDesc: 'Global online payment',
      googlePay: 'Google Pay',
      googlePayDesc: 'Quick payment with Google',
      applePay: 'Apple Pay',
      applePayDesc: 'Payment for Apple devices',
      stripe: 'Stripe',
      stripeDesc: 'Credit/Debit card payment'
    },
    footer: {
      brand: 'Network acceleration service designed for overseas Chinese, enabling seamless access to domestic network experience abroad.',
      wechatGroup: 'WeChat Group',
      email: 'Email',
      products: 'Products & Services',
      features: 'Features',
      pricing: 'Pricing',
      freeTrial: 'Free Trial',
      nodeStatus: 'Node Status',
      speedTest: 'Speed Test',
      download: 'Download',
      windowsClient: 'Windows Client',
      macosClient: 'macOS Client',
      iosApp: 'iOS App',
      androidApp: 'Android App',
      webVersion: 'Web Version',
      support: 'Help & Support',
      tutorial: 'Tutorial',
      faq: 'FAQ',
      contactSupport: 'Contact Support',
      feedback: 'Feedback',
      terms: 'Terms of Service',
      newsletter: 'Newsletter',
      emailPlaceholder: 'Enter email address',
      subscribe: 'Subscribe',
      copyright: '© 2024 GuiChao GuiChao.win. All rights reserved.',
      privacy: 'Privacy Policy',
      cookie: 'Cookie Policy',
      tagline: 'Professional network service provider for overseas Chinese | Distance is no longer a barrier',
      ownership: 'This website is owned and operated by HK Guichao Technology Co., Limited'
    },
    auth: {
      joinTitle: 'Join',
      joinBrand: 'GuiChao',
      subtitle: 'Network acceleration service designed for overseas Chinese, enabling seamless access to domestic network experience.',
      fastConnection: 'Lightning Fast',
      fastDesc: 'Ultra low latency, buffer-free 4K streaming',
      militaryEncryption: 'Military Grade Encryption',
      encryptionDesc: 'AES-256 encryption, privacy protection',
      globalNodes: 'Global Network',
      nodesDesc: '50+ cities worldwide, intelligent routing',
      review1: '"GuiChao is amazing! Super fast connection, watching domestic videos is flawless."',
      reviewer1: '- User from USA, Mr. Zhang',
      review2: '"Working abroad, I often need to access domestic business databases. GuiChao perfectly solves my pain point with fast speed and affordable price. Essential for business!"',
      reviewer2: '- User from UK, Ms. Li',
      welcomeTitle: 'Welcome to GuiChao',
      welcomeDesc: 'Please login or register your account',
      login: 'Login',
      register: 'Register',
      email: 'Email',
      emailPlaceholder: 'Enter email address',
      password: 'Password',
      passwordPlaceholder: 'Enter password',
      passwordPlaceholder8: 'Enter password (at least 8 characters)',
      confirmPassword: 'Confirm Password',
      confirmPasswordPlaceholder: 'Enter password again',
      rememberMe: 'Remember me',
      forgotPassword: 'Forgot password?',
      loggingIn: 'Logging in...',
      loginButton: 'Login',
      registerButton: 'Register Account',
      registering: 'Registering...',
      agreeTerms1: 'By logging in, you agree to our',
      agreeTerms2: 'Terms of Service',
      agreeTerms3: 'and',
      agreeTerms4: 'Privacy Policy',
      username: 'Username',
      usernamePlaceholder: 'Enter username',
      readAgree: 'I have read and agree to',
      termsLink: 'Terms of Service',
      privacyLink: 'Privacy Policy',
      orDivider: 'or',
      googleLogin: 'Login with Google',
      wechatLogin: 'Login with WeChat'
    },
    download: {
      badge: '📱 Download',
      title: 'All',
      titleBrand: 'Platforms',
      subtitle: 'Supports Windows, macOS, iOS, Android and more. One account for multiple devices',
      smartDownload: 'Smart Download',
      viewTutorial: 'View Tutorial',
      downloadBtn: 'Download',
      oneClickConnect: 'One-Click Connect',
      smartRouting: 'Smart Routing',
      autoStart: 'Auto Start',
      nativeSupport: 'Native Support',
      menubarControl: 'Menubar Control',
      systemIntegration: 'System Integration',
      appStore: 'App Store Download',
      shortcuts: 'Shortcuts',
      siriSupport: 'Siri Support',
      googlePlay: 'Google Play',
      oneClickShare: 'One-Click Share',
      powerSaving: 'Power Saving Mode',
      routerFirmware: 'Router Firmware',
      familyShare: 'Family Share',
      deviceControl: 'Device Control',
      timedSwitch: 'Timed Switch',
      browserExtension: 'Browser Extension',
      freeUse: 'Free to Use',
      webProxy: 'Web Proxy',
      smartSplit: 'Smart Split',
      tutorialTitle: 'Usage',
      tutorialBrand: 'Tutorial',
      tutorialSubtitle: 'Quick start in simple steps',
      windowsTutorial: 'Windows',
      windowsStep1: 'Download and run installer',
      windowsStep2: 'Follow wizard to complete installation',
      windowsStep3: 'Login with your credentials',
      windowsStep4: 'Select node and click connect',
      mobileTutorial: 'Mobile Client',
      mobileStep1: 'Download app from store',
      mobileStep2: 'Register or login',
      mobileStep3: 'Allow VPN configuration',
      mobileStep4: 'Select server and connect',
      routerTutorial: 'Router',
      routerStep1: 'Backup original firmware',
      routerStep2: 'Flash GuiChao firmware',
      routerStep3: 'Configure network parameters',
      routerStep4: 'Set device access control',
      helpTitle: 'Need',
      helpBrand: 'Help?',
      helpSubtitle: 'Our technical support team is here to assist you',
      downloadIssues: 'Download Issues',
      downloadIssuesDesc: 'Download failures, installation errors',
      tutorialGuide: 'Tutorial Guide',
      tutorialGuideDesc: 'Detailed text and video tutorials',
      support247: '24/7 Support',
      support247Desc: 'Round-the-clock technical support',
      contactSupport: 'Contact Support'
    },
    notFound: {
      title: 'Page',
      titleBrand: 'Not Found',
      subtitle: 'Sorry, the page you are looking for does not exist or has been moved',
      backHome: 'Back to Home',
      hint: 'Or you can try using the navigation menu to find what you need'
    },
    privacy: {
      title: 'Privacy Policy',
      subtitle: 'GuiChao values your personal information. We will take security measures in accordance with laws and regulations to protect your personal information.',
      updateDate: 'Last Updated: December 30, 2024',
      effectiveDate: 'Effective Date: December 30, 2024',
      importantTitle: 'Important Notice',
      importantText: 'Please read this GuiChao Privacy Policy carefully (especially the bold content) and ensure you understand how we handle your personal information. If you have any questions, please contact us. If you do not agree to any terms, please stop using GuiChao services immediately.',
      tocTitle: 'Table of Contents',
      section1: '1. How We Collect and Use Your Personal Information',
      section2: '2. How We Use Cookies and Similar Technologies',
      section3: '3. How We Share, Transfer, and Publicly Disclose Your Personal Information',
      section4: '4. How We Store and Protect Your Personal Information',
      section5: '5. Your Rights to Manage Personal Information',
      section6: '6. Protection of Minors\' Personal Information',
      section7: '7. Changes and Revisions to Privacy Policy',
      section8: '8. How to Contact Us',
      contactEmail: 'Email',
      companyName: 'Company Name',
      thanksTitle: 'Thank you again for trusting GuiChao!',
      thanksText: 'We will provide secure and reliable network acceleration services and continue to protect your personal information.'
    },
    terms: {
      title: 'Terms of Service',
      lastUpdate: 'Last Updated: January 2024',
      importantTitle: 'Important Notice',
      importantText: 'Please read and understand these Terms of Service carefully before using our services. Using our services indicates your agreement to be bound by these terms.',
      section1Title: '1. Service Description',
      section2Title: '2. User Responsibilities and Obligations',
      section3Title: '3. Prohibited Activities',
      section4Title: '4. Intellectual Property',
      section5Title: '5. Disclaimer',
      section6Title: '6. Fees and Payment',
      section7Title: '7. Account Termination',
      section8Title: '8. Terms Changes',
      section9Title: '9. Dispute Resolution',
      section10Title: '10. Contact Us',
      contactEmail: 'Email: support@example.com',
      contactService: 'Online Support: Weekdays 9:00-18:00',
      agreementText: 'By using our services, you have read, understood, and agreed to comply with all contents of these Terms of Service.'
    }
  }
};
