import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'zh' || saved === 'en') ? saved : 'zh';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  zh: {
    header: {
      tagline: '专为海外华人设计',
      taglineEn: 'Built for Chinese Abroad',
      home: '首页',
      homeEn: 'Home',
      features: '产品特色',
      featuresEn: 'Features',
      pricing: '套餐价格',
      pricingEn: 'Pricing',
      download: '下载客户端',
      downloadEn: 'Download',
      contact: '联系我们',
      contactEn: 'Contact',
      login: '登录',
      freeTrial: '免费试用',
      accountManagement: '账号管理',
      logout: '退出登录'
    },
    hero: {
      title: '倦鸟归巢 一键回国',
      subtitle: '专业的回国网络加速服务，让海外华人轻松访问国内网络资源',
      badge: '高速稳定 • 安全可靠 • 一键连接',
      security: '企业级安全',
      securityEn: 'Enterprise Security',
      latency: '毫秒级延迟',
      latencyEn: 'Ultra Low Latency',
      network: '全球节点',
      networkEn: 'Global Network',
      startTrial: '立即免费试用',
      downloadClient: '下载客户端',
      windows: 'Windows',
      windowsDesc: 'PC客户端',
      macos: 'macOS',
      macosDesc: 'Mac客户端',
      ios: 'iOS',
      iosDesc: 'iPhone/iPad',
      android: 'Android',
      androidDesc: '安卓手机',
      browser: '浏览器',
      browserDesc: 'Chrome插件',
      clickDownload: '点击下载'
    },
    features: {
      badge: '⚡ 产品特色',
      title: '为什么选择',
      titleBrand: '归巢',
      subtitle: '专为海外华人打造的回国网络解决方案，让您在海外也能无缝享受国内的网络服务',
      speed: '极速连接',
      speedDesc: '采用最新加速技术，连接速度提升300%，观看4K视频无缓冲',
      speedHighlight: '毫秒级延迟',
      encryption: '军用级加密',
      encryptionDesc: 'AES-256位加密技术，保护您的网络安全和隐私数据',
      encryptionHighlight: '银行级安全',
      nodes: '全球节点',
      nodesDesc: '覆盖全球50+城市，智能选择最优线路，确保连接稳定',
      nodesHighlight: '50+节点',
      devices: '多设备支持',
      devicesDesc: '一个账户支持10台设备同时使用，全家共享无忧',
      devicesHighlight: '10台设备',
      uptime: '7x24在线',
      uptimeDesc: '99.9%服务可用性，全年无休为您提供稳定的网络服务',
      uptimeHighlight: '99.9%稳定',
      support: '专业客服',
      supportDesc: '中文技术支持团队，微信群实时答疑，问题快速解决',
      supportHighlight: '中文支持',
      stat1: '1M+',
      stat1Label: '用户信赖',
      stat1En: 'Active Users',
      stat2: '50+',
      stat2Label: '全球节点',
      stat2En: 'Global Nodes',
      stat3: '99.9%',
      stat3Label: '稳定运行',
      stat3En: 'Uptime SLA',
      stat4: '24/7',
      stat4Label: '技术支持',
      stat4En: 'Support'
    },
    scenarios: {
      title: '支持加速多种场景',
      subtitle: '无论是娱乐、学习还是工作，归巢为您提供全方位的加速支持',
      video: '影音娱乐',
      videoDesc: '流畅观看国内视频平台，享受高清流媒体',
      sports: '体育赛事',
      sportsDesc: '实时观看大陆体育赛事直播，不错过精彩瞬间',
      gaming: '国服游戏',
      gamingDesc: '降低游戏延迟，畅玩国服热门游戏',
      education: '远程学习',
      educationDesc: '稳定连接大陆教育平台，在线学习无忧',
      meeting: '办公会议',
      meetingDesc: '高效跨境视频会议，团队协作更流畅',
      streaming: '达人直播',
      streamingDesc: '高清流畅直播推流，内容创作更专业'
    },
    pricing: {
      badge: '💰 套餐价格',
      title: '选择适合您的',
      titleBrand: '套餐',
      subtitle: '灵活的价格方案，满足不同用户需求。支持微信、支付宝、USDT等多种支付方式',
      discount: '🎉 年付用户享8折优惠，可节省高达HK$140',
      popular: '🔥 最受欢迎',
      trial: '体验版',
      trialDesc: '新用户专享，体验归巢服务',
      trialPrice: '免费',
      trialPeriod: '3天试用',
      trialButton: '立即试用',
      standard: '标准版',
      standardDesc: '个人用户推荐，性价比之选',
      standardButton: '选择标准版',
      premium: '旗舰版',
      premiumDesc: '家庭/企业用户首选',
      premiumButton: '选择旗舰版',
      selectPlan: '点击选择',
      guarantee1: '7天无忧退款',
      guarantee1Desc: '不满意随时退款',
      guarantee2: '24小时客服',
      guarantee2Desc: '随时为您解答问题',
      guarantee3: '无限流量',
      guarantee3Desc: '畅享高速网络体验',
      paymentTitle: '选择支付方式',
      paymentSecurity: '支付过程安全加密，支持7天无忧退款',
      cancel: '取消',
      wechat: '微信支付',
      wechatDesc: '使用微信快速支付',
      alipayHK: '香港支付宝',
      alipayHKDesc: '支付宝(香港)便捷支付',
      paypal: 'PayPal',
      paypalDesc: '全球通用在线支付',
      googlePay: 'Google Pay',
      googlePayDesc: 'Google 快速支付',
      applePay: 'Apple Pay',
      applePayDesc: 'Apple 设备专用支付',
      stripe: 'Stripe',
      stripeDesc: '信用卡/借记卡支付'
    },
    footer: {
      brand: '专为海外华人打造的回国网络加速服务，让您在海外也能无缝享受国内的网络体验。',
      wechatGroup: '微信群',
      email: '邮箱',
      products: '产品服务',
      features: '产品特色',
      pricing: '套餐价格',
      freeTrial: '免费试用',
      nodeStatus: '节点状态',
      speedTest: '速度测试',
      download: '客户端下载',
      windowsClient: 'Windows 客户端',
      macosClient: 'macOS 客户端',
      iosApp: 'iOS 应用',
      androidApp: 'Android 应用',
      webVersion: '网页版',
      support: '帮助支持',
      tutorial: '使用教程',
      faq: '常见问题',
      contactSupport: '联系客服',
      feedback: '意见反馈',
      terms: '服务条款',
      newsletter: '最新动态',
      emailPlaceholder: '输入邮箱地址',
      subscribe: '订阅',
      copyright: '© 2024 归巢 GuiChao.win. 保留所有权利。',
      privacy: '隐私政策',
      cookie: 'Cookie政策',
      research: '加速器技术研究',
      techBlog: '技术博客',
      whitepapers: '白皮书',
      caseStudies: '案例分析',
      networkOptimization: '网络优化',
      securityResearch: '安全研究',
      tagline: '专业的海外华人回国网络服务提供商 | 让距离不再是障碍',
      ownership: '本网页是属于 HK Guichao Technology Co., Limited所拥有和全权使用'
    },
    auth: {
      joinTitle: '加入',
      joinBrand: '归巢',
      subtitle: '专为海外华人打造的回国网络加速服务，让您在海外也能无缝享受国内的网络体验。',
      fastConnection: '极速连接',
      fastDesc: '毫秒级延迟，4K视频无缓冲',
      militaryEncryption: '军用级加密',
      encryptionDesc: 'AES-256位加密，保护隐私安全',
      globalNodes: '全球节点',
      nodesDesc: '覆盖50+城市，智能路由优化',
      review1: '"归巢真的太好用了！连接速度超快，看国内视频完全没问题。"',
      reviewer1: '- 来自美国的用户 张先生',
      review2: '"在海外工作需要经常查询企查查和天眼查，之前用国内手机流量又慢又贵。归巢完美解决了我的痛点，速度快、价格实惠，商务办公必备！"',
      reviewer2: '- 来自英国的用户 李女士',
      welcomeTitle: '欢迎使用归巢',
      welcomeDesc: '请登录或注册您的账号',
      login: '登录',
      register: '注册',
      email: '邮箱',
      emailPlaceholder: '请输入邮箱地址',
      password: '密码',
      passwordPlaceholder: '请输入密码',
      passwordPlaceholder8: '请输入密码（至少8位）',
      confirmPassword: '确认密码',
      confirmPasswordPlaceholder: '请再次输入密码',
      rememberMe: '记住我',
      forgotPassword: '忘记密码？',
      loggingIn: '登录中...',
      loginButton: '登录',
      registerButton: '注册账号',
      registering: '注册中...',
      agreeTerms1: '登录即表示您同意我们的',
      agreeTerms2: '服务条款',
      agreeTerms3: '和',
      agreeTerms4: '隐私协议',
      username: '用户名',
      usernamePlaceholder: '请输入用户名',
      readAgree: '我已阅读并同意',
      termsLink: '《服务条款》',
      privacyLink: '《隐私协议》',
      orDivider: '或',
      googleLogin: '使用 Google 登录',
      wechatLogin: '使用微信登录'
    },
    download: {
      badge: '📱 客户端下载',
      title: '全平台',
      titleBrand: '客户端',
      subtitle: '支持Windows、macOS、iOS、Android等全平台，一个账号多设备同时使用',
      smartDownload: '智能下载',
      viewTutorial: '查看教程',
      downloadBtn: '下载',
      oneClickConnect: '一键连接',
      smartRouting: '智能路由',
      autoStart: '开机自启',
      nativeSupport: '原生支持',
      menubarControl: '菜单栏控制',
      systemIntegration: '系统集成',
      appStore: 'App Store 下载',
      shortcuts: '快捷指令',
      siriSupport: 'Siri 支持',
      googlePlay: 'Google Play',
      oneClickShare: '一键分享',
      powerSaving: '省电模式',
      routerFirmware: '路由器固件',
      familyShare: '全家共享',
      deviceControl: '设备管控',
      timedSwitch: '定时开关',
      browserExtension: '浏览器插件',
      freeUse: '免费使用',
      webProxy: '网页代理',
      smartSplit: '智能分流',
      tutorialTitle: '使用',
      tutorialBrand: '教程',
      tutorialSubtitle: '简单几步，快速上手',
      windowsTutorial: 'Windows',
      windowsStep1: '下载并运行安装程序',
      windowsStep2: '按照向导完成安装',
      windowsStep3: '使用账号密码登录',
      windowsStep4: '选择节点并点击连接',
      mobileTutorial: '手机客户端',
      mobileStep1: '从应用商店下载应用',
      mobileStep2: '注册或登录账号',
      mobileStep3: '允许VPN配置权限',
      mobileStep4: '选择服务器开始连接',
      routerTutorial: '路由器',
      routerStep1: '备份原固件设置',
      routerStep2: '刷入归巢专用固件',
      routerStep3: '配置网络连接参数',
      routerStep4: '设置设备访问控制',
      helpTitle: '需要',
      helpBrand: '帮助？',
      helpSubtitle: '我们的技术支持团队随时为您提供帮助',
      downloadIssues: '下载问题',
      downloadIssuesDesc: '下载失败、安装错误等问题',
      tutorialGuide: '使用教程',
      tutorialGuideDesc: '详细的图文和视频教程',
      support247: '24/7客服',
      support247Desc: '全天候在线技术支持',
      contactSupport: '联系客服'
    },
    notFound: {
      title: '页面',
      titleBrand: '走丢了',
      subtitle: '抱歉，您访问的页面不存在或已被移动',
      backHome: '返回首页',
      hint: '或者您可以尝试使用导航菜单找到您需要的内容'
    },
    privacy: {
      title: '隐私政策',
      subtitle: '归巢 GuiChao 深知个人信息对您的重要性，我们将按照法律法规的要求，采取相应安全保护措施，尽力保护您的个人信息安全可控。',
      updateDate: '更新日期：2024年12月30日',
      effectiveDate: '生效日期：2024年12月30日',
      importantTitle: '特别提示',
      importantText: '请您仔细阅读本《归巢隐私政策》（尤其是加粗的内容）并确定了解我们对您个人信息的处理规则。在阅读过程中，如您有任何疑问，可通过本政策中约定的联系方式与我们联系。如您不同意本协议中的任何条款，您应立即停止访问和使用归巢服务。',
      tocTitle: '目录',
      section1: '一、我们如何收集和使用您的个人信息',
      section2: '二、我们如何使用 Cookie 和同类技术',
      section3: '三、我们如何共享、转让、公开披露您的个人信息',
      section4: '四、我们如何存储和保护您的个人信息',
      section5: '五、您管理个人信息的权利',
      section6: '六、未成年人个人信息的保护',
      section7: '七、隐私政策的变更和修订',
      section8: '八、如何联系我们',
      introPara1: '归巢（GuiChao）由 HK Guichao Technology Co., Limited 开发和运营。我们尊重并保护所有使用服务用户的个人信息，并将按照法律法规的规定保护用户信息及隐私安全。我们致力于维持您对我们的信任，恪守以下原则保护您的个人信息：权责一致原则、目的明确原则、选择同意原则、最少够用原则、确保安全原则、主体参与原则、公开透明原则等。',
      introPara2: '请您在使用我们的产品和服务前，仔细阅读并了解本隐私政策。一旦您开始使用归巢服务，即表示您已充分理解并同意本政策。',
      s1h1: '1.1 账号注册与登录',
      s1p1: '当您注册归巢账号时，我们会收集您的手机号码、邮箱地址、密码等信息，用于创建账号和验证您的身份。您可以选择通过第三方账号（如微信、Apple ID）登录，我们将在获得您授权后收集您的昵称、头像等公开信息。',
      s1h2: '1.2 网络加速服务',
      s1p2: '为了向您提供网络加速服务，我们需要收集您的设备信息（设备型号、操作系统版本、设备标识符）、网络信息（IP地址、网络类型、网络状态）、连接日志等。这些信息用于优化服务质量、诊断网络问题和保障服务安全。',
      s1h3: '1.3 支付功能',
      s1p3: '当您购买我们的付费服务时，我们可能会收集您的支付信息，包括第三方支付账号（支付宝、微信支付、Apple Pay等）。支付信息由第三方支付机构收集和处理，我们仅保存必要的订单信息。',
      s1h4: '1.4 客户服务',
      s1p4: '当您联系我们的客户服务时，我们可能会收集您的联系方式、问题描述、聊天记录等，以便为您提供支持和解决问题。',
      s1h5: '1.5 征得授权同意的例外',
      s1p5: '根据相关法律法规规定，以下情形中收集您的个人信息无需征得您的授权同意：',
      s1l1: '与国家安全、国防安全直接相关的',
      s1l2: '与公共安全、公共卫生、重大公共利益直接相关的',
      s1l3: '与犯罪侦查、起诉、审判和判决执行等直接相关的',
      s1l4: '出于维护您或其他个人的生命、财产等重大合法权益但又很难得到本人同意的',
      s1l5: '您自行向社会公众公开的个人信息',
      s1l6: '从合法公开披露的信息中收集的个人信息',
      s2p1: '为确保网站正常运转、为您获得更轻松的访问体验、向您推荐您可能感兴趣的内容，我们会在您的设备上存储名为 Cookie 的小数据文件。Cookie 通常包含标识符、站点名称以及一些号码和字符。',
      s2h1: 'Cookie 的主要用途：',
      s2l1: '保障产品与服务的安全、高效运转：我们可能会设置认证与保障安全性的 Cookie，使您避免重复登录',
      s2l2: '帮助您获得更轻松的访问体验：使用 Cookie 可以帮助您省去重复填写信息、输入搜索内容的步骤',
      s2l3: '为您推荐、展示个性化内容：我们可能会利用 Cookie 了解您的偏好和使用习惯，进行数据分析，以改善产品服务、推荐个性化内容',
      s2p2: '您可以通过浏览器设置管理或删除 Cookie。但如果您这么做，可能需要在每次访问时亲自更改用户设置，并且您之前所记录的相应信息也均会被删除，可能会对您使用的服务的安全性有一定影响。',
      s3h1: '3.1 共享',
      s3p1: '我们不会与任何公司、组织和个人共享您的个人信息，但以下情况除外：',
      s3l1: '在获取明确同意的情况下共享：获得您的明确同意后，我们会与其他方共享您的个人信息',
      s3l2: '在法定情形下的共享：根据法律法规、诉讼、争议解决需要，或按行政、司法机关依法提出的要求，我们可能会共享您的个人信息',
      s3l3: '与关联公司共享：为便于我们向您提供服务，您的个人信息可能会与我们的关联公司共享',
      s3l4: '与授权合作伙伴共享：仅为实现本政策中声明的目的，我们的某些服务将由授权合作伙伴提供。我们可能会与合作伙伴共享您的某些个人信息',
      s3h2: '3.2 转让',
      s3p2: '我们不会将您的个人信息转让给任何公司、组织和个人，但以下情况除外：在获取明确同意的情况下转让；在涉及合并、收购或破产清算时，如涉及到个人信息转让，我们会要求新的持有您个人信息的公司、组织继续受本政策的约束。',
      s3h3: '3.3 公开披露',
      s3p3: '我们仅会在以下情况下，公开披露您的个人信息：获得您明确同意后；基于法律的披露：在法律、法律程序、诉讼或政府主管部门强制性要求的情况下，我们可能会公开披露您的个人信息。',
      s4h1: '4.1 信息存储',
      s4p1: '您的个人信息将存储于中华人民共和国境内。如需跨境传输，我们将会单独征得您的授权同意，并确保数据接收方有充足的数据保护能力来保护您的个人信息。我们只会在达成本政策所述目的所需的期限内保留您的个人信息，除非法律有强制的存留要求。',
      s4h2: '4.2 信息安全',
      s4p2: '我们努力为用户的信息安全提供保障，以防止信息的丢失、不当使用、未经授权访问或披露。我们采取的安全措施包括：',
      s4l1: '我们使用各种安全技术以保障信息的安全。例如，我们会使用加密技术（如 SSL）来保护您的个人信息',
      s4l2: '我们建立专门的管理制度、流程和组织以保障信息的安全',
      s4l3: '我们对可能接触到您的信息的员工采取严格管理，包括采取不同的权限控制',
      s4l4: '我们会采取适当的符合业界标准的安全措施和技术手段存储和保护您的个人信息，以防止其丢失、被误用、受到未授权访问或泄漏、被篡改或毁坏',
      s4h3: '4.3 安全事件处置',
      s4p3: '在不幸发生个人信息安全事件后，我们将按照法律法规的要求，及时向您告知：安全事件的基本情况和可能的影响、我们已采取或将要采取的处置措施、您可自主防范和降低风险的建议、对您的补救措施等。我们将及时将事件相关情况以邮件、信函、电话、推送通知等方式告知您。',
      s5p1: '按照中国相关的法律、法规、标准，以及其他国家、地区的通行做法，我们保障您对自己的个人信息行使以下权利：',
      s5h1: '5.1 访问和更新您的个人信息',
      s5p2: '您有权访问和更新您的个人信息，法律法规规定的例外情况除外。您可以通过以下方式自行访问和更新您的个人信息：登录账号后，在"个人中心"查看和修改您的账号信息、个人资料等。',
      s5h2: '5.2 删除您的个人信息',
      s5p3: '在以下情形中，您可以向我们提出删除个人信息的请求：',
      s5l1: '如果我们处理个人信息的行为违反法律法规',
      s5l2: '如果我们收集、使用您的个人信息，却未征得您的同意',
      s5l3: '如果我们处理个人信息的行为违反了与您的约定',
      s5l4: '如果您注销了账号',
      s5h3: '5.3 注销账号',
      s5p4: '您可以通过联系客服的方式申请注销您的账号。在您注销账号后，我们将停止为您提供产品或服务，并根据您的要求删除您的个人信息，法律法规另有规定的除外。',
      s5h4: '5.4 撤回同意',
      s5p5: '您可以通过删除信息、关闭设备功能、在网站或软件中进行隐私设置等方式改变您授权我们继续收集个人信息的范围或撤回您的授权。您也可以通过注销账号的方式，撤回我们继续收集您个人信息的全部授权。',
      s5h5: '5.5 响应您的请求',
      s5p6: '为保障安全，您可能需要提供书面请求，或以其他方式证明您的身份。我们可能会先要求您验证自己的身份，然后再处理您的请求。我们将在15个工作日内做出答复。如您不满意，还可以通过本政策中的联系方式投诉。',
      s6p1: '我们非常重视对未成年人个人信息的保护。若您是18周岁以下的未成年人，在使用我们的产品和/或服务前，应事先取得您家长或法定监护人的书面同意。',
      s6p2: '我们根据国家相关法律法规的规定保护未成年人的个人信息。对于经父母或法定监护人同意而收集未成年人个人信息的情况，我们只会在受到法律允许、父母或监护人明确同意或者保护未成年人所必要的情况下使用或公开披露此信息。',
      s6p3: '如果我们发现自己在未事先获得可证实的父母或法定监护人同意的情况下收集了未成年人的个人信息，则会设法尽快删除相关数据。',
      s7p1: '为了给您提供更好的服务，我们可能会根据产品或服务的更新情况及法律法规的相关要求适时修改本政策的条款，该等修改构成本隐私政策的一部分。',
      s7p2: '如该等更新造成您在本隐私政策下权利的实质减少或重大变更，我们将在本政策生效前通过网站公告、推送通知、弹窗提示或其他方式来通知您，您如果不同意该等变更，可以选择停止使用我们的产品和服务；如您仍然继续使用我们的产品和服务，即表示您已充分阅读、理解并同意受经修订的本隐私政策的约束。',
      s7p3: '本政策所指的重大变更包括但不限于：',
      s7l1: '我们的服务模式发生重大变化',
      s7l2: '个人信息共享、转让或公开披露的主要对象发生变化',
      s7l3: '您参与个人信息处理方面的权利及其行使方式发生重大变化',
      s7l4: '我们负责处理个人信息安全的责任部门、联络方式及投诉渠道发生变化',
      s8p1: '如果您对本隐私政策有任何疑问、意见或建议，或您在使用我们的服务时遇到任何与个人信息保护相关的问题，您可以通过以下方式与我们联系：',
      s8p2: '一般情况下，我们将在15个工作日内回复。如果您对我们的回复不满意，特别是您认为我们的个人信息处理行为损害了您的合法权益，您还可以通过向被告住所地有管辖权的法院提起诉讼来寻求解决方案。',
      contactEmail: '电子邮件',
      companyName: '公司名称',
      thanksTitle: '再次感谢您对归巢的信任！',
      thanksText: '我们将竭诚为您提供安全、可靠的网络加速服务，并持续保护您的个人信息安全。'
    },
    cookie: {
      title: 'Cookie政策',
      lastUpdated: '最后更新日期：2024年1月',
      intro: '本Cookie政策说明AI智联加速器（"我们"或"本服务"）如何使用Cookie及类似技术来识别您访问我们的网站、应用程序和服务时的身份。本政策解释了这些技术是什么，我们为何使用它们，以及您如何控制它们的使用。',
      
      whatAreCookies: {
        title: '什么是Cookie？',
        content: 'Cookie是当您访问网站时放置在您的计算机或移动设备上的小型数据文件。网站所有者广泛使用Cookie来使其网站运行或更高效地运行，以及提供报告信息。网站所有者设置的Cookie称为"第一方Cookie"。由网站所有者以外的各方设置的Cookie称为"第三方Cookie"。第三方Cookie启用可在网站上或通过网站提供的第三方功能或功能（例如广告、交互式内容和分析）。设置这些第三方Cookie的各方可以在您的计算机访问相关网站以及访问某些其他网站时识别您的计算机。'
      },
      
      whyWeUseCookies: {
        title: '我们为什么使用Cookie？',
        content: '我们使用第一方和第三方Cookie的原因有多种。出于技术原因，我们的网站需要某些Cookie才能运行，我们将其称为"必需"或"绝对必要"Cookie。其他Cookie还使我们能够跟踪和定位用户的兴趣，以增强我们在线资产上的体验。第三方通过我们的网站提供Cookie，用于广告、分析和其他目的。'
      },
      
      typesOfCookies: {
        title: '我们使用的Cookie类型',
        essential: {
          title: '必需Cookie',
          description: '这些Cookie对于向您提供通过我们的网站可用的服务以及使用其某些功能（例如访问安全区域）是绝对必要的。由于这些Cookie对于向您提供服务是绝对必要的，因此您无法拒绝它们而不影响我们网站的功能。您可以通过更改浏览器设置来阻止或删除它们，但这可能会影响网站的某些功能。'
        },
        performance: {
          title: '性能和功能Cookie',
          description: '这些Cookie用于增强我们网站的性能和功能，但对其使用并非必不可少。但是，如果没有这些Cookie，某些功能（如视频）可能会变得不可用，或者您将需要每次访问网站时输入您的登录详细信息，因为我们无法记住您之前已登录。'
        },
        analytics: {
          title: '分析和定制Cookie',
          description: '这些Cookie收集用于汇总分析我们网站使用情况的信息，以便我们可以改善访问者体验。它们还允许我们测试新想法并监控和改善我们网站的性能。例如，我们使用这些Cookie来计算网站的访问者数量并查看访问者如何浏览网站。我们使用这些信息来改进我们网站的工作方式，例如，通过确保用户轻松找到所需内容。'
        },
        advertising: {
          title: '广告Cookie',
          description: '这些Cookie用于使广告信息与您更相关。它们执行诸如防止相同广告不断重新出现、确保广告正确显示给广告主以及在某些情况下根据您的兴趣选择广告等功能。'
        }
      },
      
      howToControl: {
        title: '如何控制Cookie？',
        content: '您有权决定是否接受或拒绝Cookie。您可以通过在Cookie同意管理器中设置您的首选项来行使您的Cookie权利。Cookie同意管理器允许您选择接受或拒绝哪些类别的Cookie。必需Cookie不能被拒绝，因为它们对于向您提供服务是绝对必要的。',
        browserSettings: '如果您选择拒绝Cookie，您仍可以使用我们的网站，但您对网站某些功能和区域的访问可能会受到限制。您还可以设置或修改Web浏览器控件以接受或拒绝Cookie。'
      },
      
      specificCookies: {
        title: '我们使用的具体Cookie',
        sessionCookies: '会话Cookie：这些Cookie在您浏览会话期间临时存储信息。它们在您关闭浏览器时被删除。',
        persistentCookies: '持久Cookie：这些Cookie在您的设备上保留更长时间，用于记住您的偏好设置和登录信息。',
        securityCookies: '安全Cookie：这些Cookie用于验证用户身份、防止欺诈性使用登录凭证，并保护用户数据免受未经授权方的侵害。'
      },
      
      thirdParty: {
        title: '第三方Cookie',
        content: '除了我们自己的Cookie之外，我们还可能使用各种第三方Cookie来报告我们网站的使用统计信息、投放广告等。这些第三方服务提供商可能会使用Cookie来收集您访问我们网站和其他网站的信息。我们不控制这些第三方Cookie，它们的使用受提供它们的公司的隐私政策约束。'
      },
      
      updates: {
        title: '本Cookie政策的更新',
        content: '我们可能会不时更新本Cookie政策，以反映我们使用的Cookie的更改或出于其他运营、法律或监管原因。因此，请定期重新访问本Cookie政策以了解我们对Cookie和相关技术的使用情况。本Cookie政策顶部的日期表示其最后更新时间。'
      },
      
      contact: {
        title: '联系我们',
        content: '如果您对我们使用Cookie或其他技术有任何疑问，请通过以下方式与我们联系：',
        email: '邮箱：support@ai-accelerator.com'
      }
    },
    terms: {
      title: '服务条款',
      lastUpdate: '最后更新日期：2024年1月',
      importantTitle: '重要提示',
      importantText: '在使用我们的服务之前，请仔细阅读并理解本服务条款。使用我们的服务即表示您同意接受本条款的约束。',
      section1Title: '1. 服务说明',
      s1p1: '我们提供的网络加速服务旨在优化您的网络连接体验。服务内容包括但不限于：',
      s1l1: '网络连接加速和优化',
      s1l2: '多节点服务器支持',
      s1l3: '数据传输加密',
      s1l4: '技术支持和客户服务',
      s1p2: '我们保留随时修改、暂停或终止部分或全部服务的权利，恕不另行通知。',
      section2Title: '2. 用户责任与义务',
      s2p1: '作为服务用户，您同意：',
      s2l1: '提供真实、准确的注册信息',
      s2l2: '妥善保管账户信息和密码',
      s2l3: '遵守所有适用的法律法规',
      s2l4: '不得将服务用于任何非法或未授权的目的',
      s2l5: '不得干扰或破坏服务的正常运行',
      s2l6: '不得尝试未经授权访问我们的系统或网络',
      section3Title: '3. 禁止行为',
      s3p1: '使用我们的服务时，严禁从事以下行为：',
      s3l1: '发布、传输任何违法、有害、威胁、辱骂、骚扰、侵权、中伤、粗俗、淫秽或其他令人反感的内容',
      s3l2: '侵犯他人的知识产权或其他合法权益',
      s3l3: '传播病毒、恶意代码或其他可能损害系统的内容',
      s3l4: '进行任何形式的网络攻击或恶意行为',
      s3l5: '滥用服务资源或影响其他用户的正常使用',
      s3l6: '未经授权共享账户或转售服务',
      section4Title: '4. 知识产权',
      s4p1: '本服务及其所有相关内容（包括但不限于软件、文本、图片、标志、音频、视频）的知识产权归我们或相关权利人所有。',
      s4p2: '未经明确书面许可，您不得复制、修改、传播、展示或以其他方式使用这些内容。',
      section5Title: '5. 免责声明',
      s5p1: '我们将尽力提供稳定可靠的服务，但不对以下情况承担责任：',
      s5l1: '因不可抗力、网络故障、系统维护等原因导致的服务中断',
      s5l2: '因用户自身原因（如设备故障、网络问题）造成的使用障碍',
      s5l3: '第三方服务或内容的质量、安全性或合法性',
      s5l4: '因用户违反本条款或相关法律法规造成的任何损失',
      s5p2: '服务按"现状"和"可用"基础提供，不提供任何明示或暗示的保证。',
      section6Title: '6. 费用与支付',
      s6p1: '部分服务需要付费使用。具体费用标准以网站公布的价格为准。',
      s6l1: '所有费用均以人民币计价',
      s6l2: '支付后不支持退款，除非法律另有规定',
      s6l3: '我们保留随时调整价格的权利',
      s6l4: '如因您的原因导致支付失败，我们不承担责任',
      section7Title: '7. 账户终止',
      s7p1: '在以下情况下，我们有权暂停或终止您的账户：',
      s7l1: '您违反本服务条款的任何规定',
      s7l2: '您的行为可能给我们或其他用户带来法律风险',
      s7l3: '您长期未使用账户（超过12个月）',
      s7l4: '应司法机关或政府部门的要求',
      s7p2: '账户终止后，您将无法访问服务，且我们不对任何数据丢失承担责任。',
      section8Title: '8. 条款变更',
      s8p1: '我们保留随时修改本服务条款的权利。重大变更将通过网站公告或电子邮件通知您。',
      s8p2: '继续使用服务即表示您接受修改后的条款。如不同意变更，请停止使用服务。',
      section9Title: '9. 争议解决',
      s9p1: '本条款受中华人民共和国法律管辖。因本条款引起的任何争议，双方应首先通过友好协商解决。',
      s9p2: '协商不成的，任何一方均可向我们所在地有管辖权的人民法院提起诉讼。',
      section10Title: '10. 联系我们',
      s10p1: '如您对本服务条款有任何疑问或建议，请通过以下方式联系我们：',
      contactEmail: '邮箱：support@example.com',
      contactService: '在线客服：工作日 9:00-18:00',
      agreementText: '使用我们的服务即表示您已阅读、理解并同意遵守本服务条款的所有内容。'
    },
    profile: {
      title: '账号管理',
      subtitle: '管理您的个人信息和账号设置',
      loading: '加载中...',
      accountInfo: '账号信息',
      purchases: '购买记录',
      security: '安全设置',
      deleteAccount: '删除账号',
      accountInfoTitle: '账号信息',
      accountInfoDesc: '查看您的账号状态和订阅信息',
      emailAddress: '邮箱地址',
      phoneNumber: '手机号码',
      notSet: '未设置',
      memberStatus: '会员状态',
      vipMember: 'VIP会员',
      regularUser: '普通用户',
      vipRemaining: 'VIP剩余时长',
      days: '天',
      renew: '续费',
      purchase: '购买',
      expiryTime: '到期时间',
      vipBenefits: 'VIP会员权益',
      aiAdvanced: 'AI高级功能',
      priorityProcessing: '优先处理',
      exclusiveSupport: '专属客服',
      exclusiveContent: '独家内容',
      editEmail: '修改邮箱地址',
      editEmailDesc: '输入新邮箱地址后，我们将发送验证邮件到新邮箱',
      newEmail: '新邮箱地址',
      newEmailPlaceholder: '请输入新邮箱地址',
      verificationSent: '验证邮件已发送到',
      checkEmail: '，请检查邮箱并点击验证链接',
      cancel: '取消',
      sending: '发送中...',
      sendVerificationEmail: '发送验证邮件',
      done: '完成',
      editPhone: '修改手机号码',
      editPhoneDesc: '输入新手机号码后，我们将发送验证码到新手机',
      newPhone: '新手机号码',
      newPhonePlaceholder: '请输入新手机号码',
      verificationCode: '验证码',
      verificationCodePlaceholder: '请输入6位验证码',
      sendCode: '发送验证码',
      verifying: '验证中...',
      verifyAndUpdate: '验证并更新',
      purchasesTitle: '购买记录',
      purchasesDesc: '查看您的所有购买历史',
      orderDate: '订单日期',
      orderNumber: '订单编号',
      memberType: '会员类型',
      memberDuration: '会员时长',
      acquisitionMethod: '获取途径',
      noPurchases: '暂无购买记录',
      permanent: '永久',
      gifted: '赠送',
      purchased: '购买',
      securityTitle: '安全设置',
      securityDesc: '管理您的密码和账号安全',
      changePassword: '修改密码',
      currentPassword: '当前密码',
      currentPasswordPlaceholder: '请输入当前密码',
      newPassword: '新密码',
      newPasswordPlaceholder: '请输入新密码',
      confirmNewPassword: '确认新密码',
      confirmNewPasswordPlaceholder: '请再次输入新密码',
      changing: '修改中...',
      deleteAccountAgreement: '账号注销协议',
      agreementSection1: '一、注销前需满足的条件',
      agreementSection1Item1: '已取消所有自动订阅服务，确保无未完成的订阅套餐；',
      agreementSection1Item2: '账号当前不存在任何纠纷、投诉或被举报的情况，且未违反用户协议。',
      agreementSection2: '二、注销流程说明',
      agreementSection2Item1: '确认满足上述条件后，可提交账号删除申请，提交后无法撤回；',
      agreementSection2Item2: '申请提交后账号将立即注销，所有数据将被清除。',
      agreementSection3: '三、数据删除与保留说明',
      agreementSection3Item1: '账号注销后，我们将删除账号注册时使用的邮箱、手机号及密码；',
      agreementSection3Item2: '同时删除订单记录、登录记录及使用GUICHAO服务的历史数据；',
      agreementSection3Item3: '账号剩余会员天数等所有权益将清空，无法恢复。',
      agreementSection4: '四、其他提示',
      agreementSection4Item1: '注销后，原账号绑定的手机号、邮箱及第三方登录信息将被释放，可重新用于注册或绑定；',
      agreementSection4Item2: '已注销账号无法再次登录或恢复，重新注册亦无法享受此前已获得的新用户福利；',
      agreementSection4Item3: '如需再次使用GUICHAO服务，需重新注册账号。',
      agreementCheckbox: '我已仔细阅读并理解《账号注销协议》的全部内容，明确知晓注销后的所有后果，并自愿申请注销账号',
      deleteWarning: '警告：此操作无法撤销',
      deleteWarningDesc: '删除账号将永久删除以下内容：',
      deleteWarningItem1: '您的所有个人资料',
      deleteWarningItem2: '购买记录和订阅信息',
      deleteWarningItem3: '账号相关的所有数据',
      confirmDelete: '确认删除账号',
      confirmDeleteDesc: '为了确保账号安全，请输入您的登录密码以继续删除操作。',
      loginPassword: '登录密码',
      loginPasswordPlaceholder: '请输入您的登录密码',
      deleteNote: '此操作无法撤销，将永久删除您的账号及所有相关数据。',
      deleting: '删除中...',
      confirmDeleteBtn: '确认删除',
      loadFailed: '加载失败',
      loadPurchasesFailed: '加载购买记录失败',
      saveFailed: '保存失败',
      saveSuccess: '保存成功',
      profileUpdated: '您的个人信息已更新',
      oldPasswordError: '旧密码错误',
      oldPasswordErrorDesc: '您输入的当前密码不正确，请重试',
      changeSuccess: '修改成功',
      passwordUpdated: '您的密码已更新',
      changeFailed: '修改失败',
      loggedOut: '已退出登录',
      logoutSuccess: '您已成功退出账号',
      logoutFailed: '退出失败',
      enterPassword: '请输入密码',
      enterPasswordDesc: '为了安全起见，请输入您的登录密码',
      passwordError: '密码错误',
      passwordErrorDesc: '您输入的密码不正确，请重试',
      verificationSuccess: '验证成功',
      deleteRequestSubmitted: '您的账号删除请求已提交，请联系管理员完成删除',
      verificationFailed: '验证失败',
      enterContact: '请输入新的联系方式',
      emailVerificationSent: '验证邮件已发送',
      checkNewEmail: '请检查您的新邮箱并点击验证链接',
      codeVerificationSent: '验证码已发送',
      checkSMS: '请检查您的手机短信',
      sendFailed: '发送失败',
      enterCode: '请输入验证码',
      phoneUpdated: '手机号已更新',
      phoneUpdateSuccess: '您的手机号已成功修改',
      emailVerification: '邮箱验证',
      clickEmailLink: '请点击邮件中的验证链接完成邮箱更新',
      usernameMin: '用户名至少2个字符',
      usernameMax: '用户名最多50个字符',
      invalidURL: '请输入有效的URL',
      bioMax: '简介最多500个字符',
      enterCurrentPassword: '请输入当前密码',
      passwordMin: '密码至少6个字符',
      passwordMismatch: '两次密码输入不一致',
      noSubscription: '未设置订阅',
      expired: '已过期'
    }
  },
  en: {
    header: {
      tagline: 'Built for Chinese Abroad',
      taglineEn: '专为海外华人设计',
      home: 'Home',
      homeEn: '首页',
      features: 'Features',
      featuresEn: '产品特色',
      pricing: 'Pricing',
      pricingEn: '套餐价格',
      download: 'Download',
      downloadEn: '下载客户端',
      contact: 'Contact',
      contactEn: '联系我们',
      login: 'Login',
      freeTrial: 'Free Trial',
      accountManagement: 'Account',
      logout: 'Logout'
    },
    hero: {
      title: 'Home Network Access Simplified',
      subtitle: 'Professional network acceleration service for Chinese living abroad to easily access domestic network resources',
      badge: 'Fast & Stable • Secure & Reliable • One-Click Connect',
      security: 'Enterprise Security',
      securityEn: '企业级安全',
      latency: 'Ultra Low Latency',
      latencyEn: '毫秒级延迟',
      network: 'Global Network',
      networkEn: '全球节点',
      startTrial: 'Start Free Trial',
      downloadClient: 'Download Client',
      windows: 'Windows',
      windowsDesc: 'PC Client',
      macos: 'macOS',
      macosDesc: 'Mac Client',
      ios: 'iOS',
      iosDesc: 'iPhone/iPad',
      android: 'Android',
      androidDesc: 'Android Phone',
      browser: 'Browser',
      browserDesc: 'Chrome Extension',
      clickDownload: 'Click to Download'
    },
    features: {
      badge: '⚡ Features',
      title: 'Why Choose',
      titleBrand: 'GuiChao',
      subtitle: 'Network solution designed for overseas Chinese, enabling seamless access to domestic network services',
      speed: 'Lightning Fast',
      speedDesc: 'Latest acceleration technology, 300% speed boost, buffer-free 4K streaming',
      speedHighlight: 'Ultra Low Latency',
      encryption: 'Military Grade Encryption',
      encryptionDesc: 'AES-256 encryption protects your network security and privacy',
      encryptionHighlight: 'Bank Level Security',
      nodes: 'Global Network',
      nodesDesc: '50+ cities worldwide, intelligent routing for stable connections',
      nodesHighlight: '50+ Nodes',
      devices: 'Multi-Device Support',
      devicesDesc: 'One account supports 10 devices simultaneously, family sharing made easy',
      devicesHighlight: '10 Devices',
      uptime: '7x24 Online',
      uptimeDesc: '99.9% service availability, year-round stable network service',
      uptimeHighlight: '99.9% Uptime',
      support: 'Professional Support',
      supportDesc: 'Chinese technical support team, WeChat group real-time assistance',
      supportHighlight: 'Chinese Support',
      stat1: '1M+',
      stat1Label: 'Active Users',
      stat1En: '用户信赖',
      stat2: '50+',
      stat2Label: 'Global Nodes',
      stat2En: '全球节点',
      stat3: '99.9%',
      stat3Label: 'Uptime SLA',
      stat3En: '稳定运行',
      stat4: '24/7',
      stat4Label: 'Support',
      stat4En: '技术支持'
    },
    scenarios: {
      title: 'Multiple Acceleration Scenarios',
      subtitle: 'Whether entertainment, learning or work, GuiChao provides comprehensive acceleration support',
      video: 'Video Entertainment',
      videoDesc: 'Smooth streaming from domestic video platforms, enjoy HD content',
      sports: 'Sports Events',
      sportsDesc: 'Watch mainland sports broadcasts in real-time, never miss exciting moments',
      gaming: 'Domestic Gaming',
      gamingDesc: 'Reduce game latency, enjoy popular domestic games smoothly',
      education: 'Remote Learning',
      educationDesc: 'Stable connection to mainland education platforms, worry-free online learning',
      meeting: 'Business Meetings',
      meetingDesc: 'Efficient cross-border video conferences, smoother team collaboration',
      streaming: 'Live Streaming',
      streamingDesc: 'HD smooth streaming, more professional content creation'
    },
    pricing: {
      badge: '💰 Pricing',
      title: 'Choose Your',
      titleBrand: 'Plan',
      subtitle: 'Flexible pricing plans to meet different user needs. Supports WeChat Pay, Alipay, USDT and more',
      discount: '🎉 Annual plan users enjoy 20% off, save up to HK$140',
      popular: '🔥 Most Popular',
      trial: 'Trial',
      trialDesc: 'New user exclusive, experience GuiChao service',
      trialPrice: 'Free',
      trialPeriod: '3-day trial',
      trialButton: 'Start Trial',
      standard: 'Standard',
      standardDesc: 'Recommended for individual users, best value',
      standardButton: 'Choose Standard',
      premium: 'Premium',
      premiumDesc: 'Best choice for families/enterprises',
      premiumButton: 'Choose Premium',
      selectPlan: 'Click to Select',
      guarantee1: '7-Day Money Back',
      guarantee1Desc: 'Refund anytime if unsatisfied',
      guarantee2: '24-Hour Support',
      guarantee2Desc: 'Answer your questions anytime',
      guarantee3: 'Unlimited Data',
      guarantee3Desc: 'Enjoy high-speed network experience',
      paymentTitle: 'Select Payment Method',
      paymentSecurity: 'Secure encrypted payment, supports 7-day money-back guarantee',
      cancel: 'Cancel',
      wechat: 'WeChat Pay',
      wechatDesc: 'Quick payment with WeChat',
      alipayHK: 'Alipay HK',
      alipayHKDesc: 'Convenient payment with Alipay (Hong Kong)',
      paypal: 'PayPal',
      paypalDesc: 'Global online payment',
      googlePay: 'Google Pay',
      googlePayDesc: 'Quick payment with Google',
      applePay: 'Apple Pay',
      applePayDesc: 'Payment for Apple devices',
      stripe: 'Stripe',
      stripeDesc: 'Credit/Debit card payment'
    },
    footer: {
      brand: 'Network acceleration service designed for overseas Chinese, enabling seamless access to domestic network experience abroad.',
      wechatGroup: 'WeChat Group',
      email: 'Email',
      products: 'Products & Services',
      features: 'Features',
      pricing: 'Pricing',
      freeTrial: 'Free Trial',
      nodeStatus: 'Node Status',
      speedTest: 'Speed Test',
      download: 'Download',
      windowsClient: 'Windows Client',
      macosClient: 'macOS Client',
      iosApp: 'iOS App',
      androidApp: 'Android App',
      webVersion: 'Web Version',
      support: 'Help & Support',
      tutorial: 'Tutorial',
      faq: 'FAQ',
      contactSupport: 'Contact Support',
      feedback: 'Feedback',
      terms: 'Terms of Service',
      newsletter: 'Newsletter',
      emailPlaceholder: 'Enter email address',
      subscribe: 'Subscribe',
      copyright: '© 2024 GuiChao GuiChao.win. All rights reserved.',
      privacy: 'Privacy Policy',
      cookie: 'Cookie Policy',
      research: 'Accelerator Technology Research',
      techBlog: 'Tech Blog',
      whitepapers: 'Whitepapers',
      caseStudies: 'Case Studies',
      networkOptimization: 'Network Optimization',
      securityResearch: 'Security Research',
      tagline: 'Professional network service provider for overseas Chinese | Distance is no longer a barrier',
      ownership: 'This website is owned and operated by HK Guichao Technology Co., Limited'
    },
    auth: {
      joinTitle: 'Join',
      joinBrand: 'GuiChao',
      subtitle: 'Network acceleration service designed for overseas Chinese, enabling seamless access to domestic network experience.',
      fastConnection: 'Lightning Fast',
      fastDesc: 'Ultra low latency, buffer-free 4K streaming',
      militaryEncryption: 'Military Grade Encryption',
      encryptionDesc: 'AES-256 encryption, privacy protection',
      globalNodes: 'Global Network',
      nodesDesc: '50+ cities worldwide, intelligent routing',
      review1: '"GuiChao is amazing! Super fast connection, watching domestic videos is flawless."',
      reviewer1: '- User from USA, Mr. Zhang',
      review2: '"Working abroad, I often need to access domestic business databases. GuiChao perfectly solves my pain point with fast speed and affordable price. Essential for business!"',
      reviewer2: '- User from UK, Ms. Li',
      welcomeTitle: 'Welcome to GuiChao',
      welcomeDesc: 'Please login or register your account',
      login: 'Login',
      register: 'Register',
      email: 'Email',
      emailPlaceholder: 'Enter email address',
      password: 'Password',
      passwordPlaceholder: 'Enter password',
      passwordPlaceholder8: 'Enter password (at least 8 characters)',
      confirmPassword: 'Confirm Password',
      confirmPasswordPlaceholder: 'Enter password again',
      rememberMe: 'Remember me',
      forgotPassword: 'Forgot password?',
      loggingIn: 'Logging in...',
      loginButton: 'Login',
      registerButton: 'Register Account',
      registering: 'Registering...',
      agreeTerms1: 'By logging in, you agree to our',
      agreeTerms2: 'Terms of Service',
      agreeTerms3: 'and',
      agreeTerms4: 'Privacy Policy',
      username: 'Username',
      usernamePlaceholder: 'Enter username',
      readAgree: 'I have read and agree to',
      termsLink: 'Terms of Service',
      privacyLink: 'Privacy Policy',
      orDivider: 'or',
      googleLogin: 'Login with Google',
      wechatLogin: 'Login with WeChat'
    },
    download: {
      badge: '📱 Download',
      title: 'All',
      titleBrand: 'Platforms',
      subtitle: 'Supports Windows, macOS, iOS, Android and more. One account for multiple devices',
      smartDownload: 'Smart Download',
      viewTutorial: 'View Tutorial',
      downloadBtn: 'Download',
      oneClickConnect: 'One-Click Connect',
      smartRouting: 'Smart Routing',
      autoStart: 'Auto Start',
      nativeSupport: 'Native Support',
      menubarControl: 'Menubar Control',
      systemIntegration: 'System Integration',
      appStore: 'App Store Download',
      shortcuts: 'Shortcuts',
      siriSupport: 'Siri Support',
      googlePlay: 'Google Play',
      oneClickShare: 'One-Click Share',
      powerSaving: 'Power Saving Mode',
      routerFirmware: 'Router Firmware',
      familyShare: 'Family Share',
      deviceControl: 'Device Control',
      timedSwitch: 'Timed Switch',
      browserExtension: 'Browser Extension',
      freeUse: 'Free to Use',
      webProxy: 'Web Proxy',
      smartSplit: 'Smart Split',
      tutorialTitle: 'Usage',
      tutorialBrand: 'Tutorial',
      tutorialSubtitle: 'Quick start in simple steps',
      windowsTutorial: 'Windows',
      windowsStep1: 'Download and run installer',
      windowsStep2: 'Follow wizard to complete installation',
      windowsStep3: 'Login with your credentials',
      windowsStep4: 'Select node and click connect',
      mobileTutorial: 'Mobile Client',
      mobileStep1: 'Download app from store',
      mobileStep2: 'Register or login',
      mobileStep3: 'Allow VPN configuration',
      mobileStep4: 'Select server and connect',
      routerTutorial: 'Router',
      routerStep1: 'Backup original firmware',
      routerStep2: 'Flash GuiChao firmware',
      routerStep3: 'Configure network parameters',
      routerStep4: 'Set device access control',
      helpTitle: 'Need',
      helpBrand: 'Help?',
      helpSubtitle: 'Our technical support team is here to assist you',
      downloadIssues: 'Download Issues',
      downloadIssuesDesc: 'Download failures, installation errors',
      tutorialGuide: 'Tutorial Guide',
      tutorialGuideDesc: 'Detailed text and video tutorials',
      support247: '24/7 Support',
      support247Desc: 'Round-the-clock technical support',
      contactSupport: 'Contact Support'
    },
    notFound: {
      title: 'Page',
      titleBrand: 'Not Found',
      subtitle: 'Sorry, the page you are looking for does not exist or has been moved',
      backHome: 'Back to Home',
      hint: 'Or you can try using the navigation menu to find what you need'
    },
    privacy: {
      title: 'Privacy Policy',
      subtitle: 'GuiChao values your personal information. We will take security measures in accordance with laws and regulations to protect your personal information.',
      updateDate: 'Last Updated: December 30, 2024',
      effectiveDate: 'Effective Date: December 30, 2024',
      importantTitle: 'Important Notice',
      importantText: 'Please read this GuiChao Privacy Policy carefully (especially the bold content) and ensure you understand how we handle your personal information. If you have any questions, please contact us. If you do not agree to any terms, please stop using GuiChao services immediately.',
      tocTitle: 'Table of Contents',
      section1: '1. How We Collect and Use Your Personal Information',
      section2: '2. How We Use Cookies and Similar Technologies',
      section3: '3. How We Share, Transfer, and Publicly Disclose Your Personal Information',
      section4: '4. How We Store and Protect Your Personal Information',
      section5: '5. Your Rights to Manage Personal Information',
      section6: '6. Protection of Minors\' Personal Information',
      section7: '7. Changes and Revisions to Privacy Policy',
      section8: '8. How to Contact Us',
      introPara1: 'GuiChao is developed and operated by HK Guichao Technology Co., Limited. We respect and protect the personal information of all users, and will protect user information and privacy security in accordance with laws and regulations. We are committed to maintaining your trust and adhering to the following principles: accountability, purpose limitation, consent, data minimization, security, participation, and transparency.',
      introPara2: 'Please read and understand this Privacy Policy carefully before using our products and services. Once you start using GuiChao services, it indicates that you have fully understood and agreed to this policy.',
      s1h1: '1.1 Account Registration and Login',
      s1p1: 'When you register a GuiChao account, we will collect your phone number, email address, password and other information to create an account and verify your identity. You can choose to log in through third-party accounts (such as WeChat, Apple ID), and we will collect your nickname, avatar and other public information after obtaining your authorization.',
      s1h2: '1.2 Network Acceleration Service',
      s1p2: 'To provide you with network acceleration services, we need to collect your device information (device model, operating system version, device identifier), network information (IP address, network type, network status), connection logs, etc. This information is used to optimize service quality, diagnose network problems, and ensure service security.',
      s1h3: '1.3 Payment Function',
      s1p3: 'When you purchase our paid services, we may collect your payment information, including third-party payment accounts (Alipay, WeChat Pay, Apple Pay, etc.). Payment information is collected and processed by third-party payment institutions, and we only save necessary order information.',
      s1h4: '1.4 Customer Service',
      s1p4: 'When you contact our customer service, we may collect your contact information, problem description, chat records, etc., in order to provide you with support and solve problems.',
      s1h5: '1.5 Exceptions to Authorization and Consent',
      s1p5: 'According to relevant laws and regulations, collection of your personal information does not require your authorization and consent in the following circumstances:',
      s1l1: 'Directly related to national security and defense security',
      s1l2: 'Directly related to public security, public health, and major public interests',
      s1l3: 'Directly related to criminal investigation, prosecution, trial and judgment execution',
      s1l4: 'For maintaining your or other individuals\' life, property and other major legitimate rights but it is difficult to obtain consent',
      s1l5: 'Personal information that you disclose to the public',
      s1l6: 'Personal information collected from legally disclosed information',
      s2p1: 'To ensure the normal operation of the website, provide you with an easier access experience, and recommend content that may interest you, we will store small data files called Cookies on your device. Cookies usually contain identifiers, site names, and some numbers and characters.',
      s2h1: 'Main uses of Cookies:',
      s2l1: 'Ensuring security and efficient operation of products and services: We may set authentication and security Cookies to avoid repeated logins',
      s2l2: 'Helping you get an easier access experience: Using Cookies can help you skip repeated form filling and search input',
      s2l3: 'Recommending and displaying personalized content: We may use Cookies to understand your preferences and usage habits, perform data analysis, improve product services, and recommend personalized content',
      s2p2: 'You can manage or delete Cookies through browser settings. However, if you do so, you may need to personally change user settings each time you visit, and the corresponding information you previously recorded will be deleted, which may have a certain impact on the security of the services you use.',
      s3h1: '3.1 Sharing',
      s3p1: 'We will not share your personal information with any company, organization or individual, except in the following circumstances:',
      s3l1: 'Sharing with explicit consent: After obtaining your explicit consent, we will share your personal information with other parties',
      s3l2: 'Sharing under legal circumstances: According to laws and regulations, litigation, dispute resolution needs, or at the request of administrative and judicial authorities, we may share your personal information',
      s3l3: 'Sharing with affiliates: For the convenience of providing you with services, your personal information may be shared with our affiliates',
      s3l4: 'Sharing with authorized partners: Only to achieve the purposes stated in this policy, some of our services will be provided by authorized partners. We may share some of your personal information with partners',
      s3h2: '3.2 Transfer',
      s3p2: 'We will not transfer your personal information to any company, organization or individual, except in the following circumstances: transfer with explicit consent; in the event of merger, acquisition or bankruptcy liquidation, if personal information transfer is involved, we will require the new company or organization holding your personal information to continue to be bound by this policy.',
      s3h3: '3.3 Public Disclosure',
      s3p3: 'We will only publicly disclose your personal information in the following circumstances: after obtaining your explicit consent; disclosure based on law: in the case of laws, legal procedures, litigation or mandatory requirements of government authorities, we may publicly disclose your personal information.',
      s4h1: '4.1 Information Storage',
      s4p1: 'Your personal information will be stored in the People\'s Republic of China. If cross-border transmission is required, we will obtain your separate authorization and consent, and ensure that the data recipient has sufficient data protection capabilities to protect your personal information. We will only retain your personal information for the period necessary to achieve the purposes stated in this policy, unless there is a mandatory legal retention requirement.',
      s4h2: '4.2 Information Security',
      s4p2: 'We strive to provide security for users\' information to prevent information loss, improper use, unauthorized access or disclosure. The security measures we take include:',
      s4l1: 'We use various security technologies to ensure information security. For example, we will use encryption technology (such as SSL) to protect your personal information',
      s4l2: 'We establish specialized management systems, processes and organizations to ensure information security',
      s4l3: 'We take strict management measures for employees who may have access to your information, including adopting different permission controls',
      s4l4: 'We will take appropriate security measures and technical means that comply with industry standards to store and protect your personal information to prevent it from being lost, misused, subjected to unauthorized access or disclosure, tampered with or destroyed',
      s4h3: '4.3 Security Incident Handling',
      s4p3: 'In the unfortunate event of a personal information security incident, we will notify you in accordance with legal requirements: the basic situation of the security incident and possible impact, the disposal measures we have taken or will take, suggestions for you to independently prevent and reduce risks, remedial measures for you, etc. We will promptly notify you of the relevant information about the incident by email, letter, phone, push notification, etc.',
      s5p1: 'In accordance with relevant laws, regulations, standards of China, as well as common practices in other countries and regions, we guarantee that you can exercise the following rights regarding your personal information:',
      s5h1: '5.1 Access and Update Your Personal Information',
      s5p2: 'You have the right to access and update your personal information, except as otherwise provided by laws and regulations. You can access and update your personal information by yourself in the following ways: After logging in to your account, view and modify your account information, personal data, etc. in "Personal Center".',
      s5h2: '5.2 Delete Your Personal Information',
      s5p3: 'In the following circumstances, you can request us to delete your personal information:',
      s5l1: 'If our handling of personal information violates laws and regulations',
      s5l2: 'If we collect and use your personal information without obtaining your consent',
      s5l3: 'If our handling of personal information violates our agreement with you',
      s5l4: 'If you have deactivated your account',
      s5h3: '5.3 Account Deactivation',
      s5p4: 'You can apply to deactivate your account by contacting customer service. After you deactivate your account, we will stop providing you with products or services and delete your personal information according to your request, except as otherwise provided by laws and regulations.',
      s5h4: '5.4 Withdraw Consent',
      s5p5: 'You can change the scope of your authorization for us to continue collecting personal information or withdraw your authorization by deleting information, turning off device functions, making privacy settings on the website or software, etc. You can also withdraw all authorization for us to continue collecting your personal information by deactivating your account.',
      s5h5: '5.5 Responding to Your Requests',
      s5p6: 'To ensure security, you may need to provide a written request or prove your identity in other ways. We may first require you to verify your identity before processing your request. We will respond within 15 working days. If you are not satisfied, you can also file a complaint through the contact information in this policy.',
      s6p1: 'We attach great importance to the protection of minors\' personal information. If you are a minor under the age of 18, you should obtain the written consent of your parents or legal guardians before using our products and/or services.',
      s6p2: 'We protect minors\' personal information in accordance with national laws and regulations. For the collection of minors\' personal information with the consent of parents or legal guardians, we will only use or publicly disclose this information when permitted by law, with the explicit consent of parents or guardians, or when necessary to protect minors.',
      s6p3: 'If we discover that we have collected personal information of minors without first obtaining verifiable parental or legal guardian consent, we will try to delete the relevant data as soon as possible.',
      s7p1: 'In order to provide you with better services, we may modify the terms of this policy from time to time according to the update of products or services and relevant requirements of laws and regulations. Such modifications constitute part of this Privacy Policy.',
      s7p2: 'If such updates result in a substantial reduction or major change to your rights under this Privacy Policy, we will notify you by website announcement, push notification, pop-up prompt or other means before this policy takes effect. If you do not agree to such changes, you can choose to stop using our products and services; if you continue to use our products and services, it means that you have fully read, understood and agreed to be bound by this revised Privacy Policy.',
      s7p3: 'The major changes referred to in this policy include but are not limited to:',
      s7l1: 'Major changes in our service model',
      s7l2: 'Changes in the main objects of personal information sharing, transfer or public disclosure',
      s7l3: 'Major changes in your rights regarding personal information processing and how to exercise them',
      s7l4: 'Changes in the department responsible for personal information security, contact information and complaint channels',
      s8p1: 'If you have any questions, opinions or suggestions about this Privacy Policy, or encounter any problems related to personal information protection when using our services, you can contact us in the following ways:',
      s8p2: 'In general, we will respond within 15 working days. If you are not satisfied with our response, especially if you believe that our personal information processing behavior has damaged your legitimate rights and interests, you can also seek a solution by filing a lawsuit with a court having jurisdiction over the defendant\'s domicile.',
      contactEmail: 'Email',
      companyName: 'Company Name',
      thanksTitle: 'Thank you again for trusting GuiChao!',
      thanksText: 'We will provide secure and reliable network acceleration services and continue to protect your personal information.'
    },
    cookie: {
      title: 'Cookie Policy',
      lastUpdated: 'Last Updated: January 2024',
      intro: 'This Cookie Policy explains how AI Smart Accelerator (\'we\' or \'the Service\') uses cookies and similar technologies to recognize you when you visit our websites, applications, and services. It explains what these technologies are, why we use them, and how you can control their use.',
      
      whatAreCookies: {
        title: 'What Are Cookies?',
        content: 'Cookies are small data files that are placed on your computer or mobile device when you visit a website. Cookies are widely used by website owners to make their websites work, or to work more efficiently, as well as to provide reporting information. Cookies set by the website owner (in this case, AI Smart Accelerator) are called \'first-party cookies.\' Cookies set by parties other than the website owner are called \'third-party cookies.\' Third-party cookies enable third-party features or functionality to be provided on or through the website (e.g., advertising, interactive content, and analytics). The parties that set these third-party cookies can recognize your computer both when it visits the website in question and also when it visits certain other websites.'
      },
      
      whyWeUseCookies: {
        title: 'Why Do We Use Cookies?',
        content: 'We use first-party and third-party cookies for several reasons. Some cookies are required for technical reasons for our websites to operate, and we refer to these as \'essential\' or \'strictly necessary\' cookies. Other cookies enable us to track and target the interests of our users to enhance the experience on our online properties. Third parties serve cookies through our websites for advertising, analytics, and other purposes.'
      },
      
      typesOfCookies: {
        title: 'Types of Cookies We Use',
        essential: {
          title: 'Essential Cookies',
          description: 'These cookies are strictly necessary to provide you with services available through our websites and to use some of its features, such as access to secure areas. Because these cookies are strictly necessary to deliver the services to you, you cannot refuse them without impacting how our websites function. You can block or delete them by changing your browser settings, but this may affect certain features of the website.'
        },
        performance: {
          title: 'Performance and Functionality Cookies',
          description: 'These cookies are used to enhance the performance and functionality of our websites but are not essential to their use. However, without these cookies, certain functionality (like videos) may become unavailable, or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously.'
        },
        analytics: {
          title: 'Analytics and Customization Cookies',
          description: 'These cookies collect information that is used to help us understand how our websites are being used or how effective our marketing campaigns are, or to help us customize our websites for you. For example, we use these cookies to count the number of visitors to the website and see how visitors move around the website. We use this information to improve the way our websites work, for example, by ensuring that users are finding what they are looking for easily.'
        },
        advertising: {
          title: 'Advertising Cookies',
          description: 'These cookies are used to make advertising messages more relevant to you. They perform functions like preventing the same ad from continuously reappearing, ensuring that ads are properly displayed for advertisers, and in some cases selecting advertisements that are based on your interests.'
        }
      },
      
      howToControl: {
        title: 'How Can You Control Cookies?',
        content: 'You have the right to decide whether to accept or reject cookies. You can exercise your cookie rights by setting your preferences in the Cookie Consent Manager. The Cookie Consent Manager allows you to select which categories of cookies you accept or reject. Essential cookies cannot be rejected as they are strictly necessary to provide you with services.',
        browserSettings: 'If you choose to reject cookies, you may still use our website, but your access to some functionality and areas of our website may be restricted. You may also set or amend your web browser controls to accept or refuse cookies.'
      },
      
      specificCookies: {
        title: 'Specific Cookies We Use',
        sessionCookies: 'Session Cookies: These cookies temporarily store information during your browsing session. They are deleted when you close your browser.',
        persistentCookies: 'Persistent Cookies: These cookies remain on your device for a longer period and are used to remember your preferences and login information.',
        securityCookies: 'Security Cookies: These cookies are used to authenticate users, prevent fraudulent use of login credentials, and protect user data from unauthorized parties.'
      },
      
      thirdParty: {
        title: 'Third-Party Cookies',
        content: 'In addition to our own cookies, we may also use various third-party cookies to report usage statistics of the website, deliver advertisements, and so on. These third-party service providers may use cookies to collect information about your visits to our website and other websites. We do not control these third-party cookies, and their use is governed by the privacy policies of the companies that provide them.'
      },
      
      updates: {
        title: 'Updates to This Cookie Policy',
        content: 'We may update this Cookie Policy from time to time to reflect changes to the cookies we use or for other operational, legal, or regulatory reasons. Please therefore revisit this Cookie Policy regularly to stay informed about our use of cookies and related technologies. The date at the top of this Cookie Policy indicates when it was last updated.'
      },
      
      contact: {
        title: 'Contact Us',
        content: 'If you have any questions about our use of cookies or other technologies, please contact us at:',
        email: 'Email: support@ai-accelerator.com'
      }
    },
    terms: {
      title: 'Terms of Service',
      lastUpdate: 'Last Updated: January 2024',
      importantTitle: 'Important Notice',
      importantText: 'Please read and understand these Terms of Service carefully before using our services. Using our services indicates your agreement to be bound by these terms.',
      section1Title: '1. Service Description',
      s1p1: 'Our network acceleration service is designed to optimize your network connection experience. Services include but are not limited to:',
      s1l1: 'Network connection acceleration and optimization',
      s1l2: 'Multi-node server support',
      s1l3: 'Data transmission encryption',
      s1l4: 'Technical support and customer service',
      s1p2: 'We reserve the right to modify, suspend or terminate part or all of the services at any time without notice.',
      section2Title: '2. User Responsibilities and Obligations',
      s2p1: 'As a service user, you agree to:',
      s2l1: 'Provide true and accurate registration information',
      s2l2: 'Properly keep account information and passwords',
      s2l3: 'Comply with all applicable laws and regulations',
      s2l4: 'Not use the service for any illegal or unauthorized purposes',
      s2l5: 'Not interfere with or disrupt the normal operation of the service',
      s2l6: 'Not attempt to access our systems or networks without authorization',
      section3Title: '3. Prohibited Activities',
      s3p1: 'When using our services, the following activities are strictly prohibited:',
      s3l1: 'Posting or transmitting any illegal, harmful, threatening, abusive, harassing, infringing, defamatory, vulgar, obscene or otherwise objectionable content',
      s3l2: 'Infringing on the intellectual property rights or other legitimate rights of others',
      s3l3: 'Spreading viruses, malicious code or other content that may damage the system',
      s3l4: 'Conducting any form of cyber attack or malicious behavior',
      s3l5: 'Abusing service resources or affecting other users\' normal use',
      s3l6: 'Sharing accounts or reselling services without authorization',
      section4Title: '4. Intellectual Property',
      s4p1: 'The intellectual property rights of this service and all related content (including but not limited to software, text, images, logos, audio, video) belong to us or relevant rights holders.',
      s4p2: 'Without explicit written permission, you may not copy, modify, distribute, display or otherwise use this content.',
      section5Title: '5. Disclaimer',
      s5p1: 'We will strive to provide stable and reliable services, but are not responsible for the following situations:',
      s5l1: 'Service interruptions due to force majeure, network failures, system maintenance, etc.',
      s5l2: 'Usage obstacles caused by user reasons (such as device failures, network problems)',
      s5l3: 'The quality, security or legality of third-party services or content',
      s5l4: 'Any losses caused by users violating these terms or relevant laws and regulations',
      s5p2: 'Services are provided on an "as is" and "as available" basis, without any express or implied warranties.',
      section6Title: '6. Fees and Payment',
      s6p1: 'Some services require payment. Specific fee standards are subject to the prices published on the website.',
      s6l1: 'All fees are denominated in RMB',
      s6l2: 'Refunds are not supported after payment, unless otherwise provided by law',
      s6l3: 'We reserve the right to adjust prices at any time',
      s6l4: 'We are not responsible for payment failures caused by your reasons',
      section7Title: '7. Account Termination',
      s7p1: 'We reserve the right to suspend or terminate your account in the following circumstances:',
      s7l1: 'You violate any provision of these Terms of Service',
      s7l2: 'Your behavior may bring legal risks to us or other users',
      s7l3: 'You have not used your account for a long time (more than 12 months)',
      s7l4: 'At the request of judicial authorities or government departments',
      s7p2: 'After account termination, you will not be able to access the service, and we are not responsible for any data loss.',
      section8Title: '8. Terms Changes',
      s8p1: 'We reserve the right to modify these Terms of Service at any time. Major changes will be notified to you through website announcements or email.',
      s8p2: 'Continued use of the service indicates your acceptance of the modified terms. If you do not agree to the changes, please stop using the service.',
      section9Title: '9. Dispute Resolution',
      s9p1: 'These terms are governed by the laws of the People\'s Republic of China. Any disputes arising from these terms should first be resolved through friendly negotiation.',
      s9p2: 'If negotiation fails, either party may file a lawsuit with a people\'s court having jurisdiction over our location.',
      section10Title: '10. Contact Us',
      s10p1: 'If you have any questions or suggestions about these Terms of Service, please contact us in the following ways:',
      contactEmail: 'Email: support@example.com',
      contactService: 'Online Support: Weekdays 9:00-18:00',
      agreementText: 'By using our services, you have read, understood, and agreed to comply with all contents of these Terms of Service.'
    },
    profile: {
      title: 'Account Management',
      subtitle: 'Manage your personal information and account settings',
      loading: 'Loading...',
      accountInfo: 'Account Info',
      purchases: 'Purchase History',
      security: 'Security',
      deleteAccount: 'Delete Account',
      accountInfoTitle: 'Account Information',
      accountInfoDesc: 'View your account status and subscription information',
      emailAddress: 'Email Address',
      phoneNumber: 'Phone Number',
      notSet: 'Not Set',
      memberStatus: 'Membership Status',
      vipMember: 'VIP Member',
      regularUser: 'Regular User',
      vipRemaining: 'VIP Remaining',
      days: 'days',
      renew: 'Renew',
      purchase: 'Purchase',
      expiryTime: 'Expiry Time',
      vipBenefits: 'VIP Benefits',
      aiAdvanced: 'AI Advanced Features',
      priorityProcessing: 'Priority Processing',
      exclusiveSupport: 'Exclusive Support',
      exclusiveContent: 'Exclusive Content',
      editEmail: 'Edit Email Address',
      editEmailDesc: 'After entering your new email address, we will send a verification email to the new address',
      newEmail: 'New Email Address',
      newEmailPlaceholder: 'Enter new email address',
      verificationSent: 'Verification email sent to',
      checkEmail: ', please check your inbox and click the verification link',
      cancel: 'Cancel',
      sending: 'Sending...',
      sendVerificationEmail: 'Send Verification Email',
      done: 'Done',
      editPhone: 'Edit Phone Number',
      editPhoneDesc: 'After entering your new phone number, we will send a verification code to the new number',
      newPhone: 'New Phone Number',
      newPhonePlaceholder: 'Enter new phone number',
      verificationCode: 'Verification Code',
      verificationCodePlaceholder: 'Enter 6-digit code',
      sendCode: 'Send Code',
      verifying: 'Verifying...',
      verifyAndUpdate: 'Verify & Update',
      purchasesTitle: 'Purchase History',
      purchasesDesc: 'View all your purchase records',
      orderDate: 'Order Date',
      orderNumber: 'Order Number',
      memberType: 'Member Type',
      memberDuration: 'Member Duration',
      acquisitionMethod: 'Acquisition Method',
      noPurchases: 'No purchase records',
      permanent: 'Permanent',
      gifted: 'Gifted',
      purchased: 'Purchased',
      securityTitle: 'Security Settings',
      securityDesc: 'Manage your password and account security',
      changePassword: 'Change Password',
      currentPassword: 'Current Password',
      currentPasswordPlaceholder: 'Enter current password',
      newPassword: 'New Password',
      newPasswordPlaceholder: 'Enter new password',
      confirmNewPassword: 'Confirm New Password',
      confirmNewPasswordPlaceholder: 'Enter new password again',
      changing: 'Changing...',
      deleteAccountAgreement: 'Account Deletion Agreement',
      agreementSection1: '1. Requirements Before Deletion',
      agreementSection1Item1: 'All automatic subscriptions have been cancelled, ensuring no unfinished subscription packages;',
      agreementSection1Item2: 'The account currently has no disputes, complaints, or reports, and has not violated the user agreement.',
      agreementSection2: '2. Deletion Process',
      agreementSection2Item1: 'After confirming the above requirements, you can submit an account deletion request, which cannot be withdrawn;',
      agreementSection2Item2: 'After submission, the account will be immediately deleted and all data will be cleared.',
      agreementSection3: '3. Data Deletion and Retention',
      agreementSection3Item1: 'After account deletion, we will delete the email, phone number and password used for account registration;',
      agreementSection3Item2: 'Order records, login records and historical data of using GUICHAO services will be deleted;',
      agreementSection3Item3: 'All benefits including remaining VIP days will be cleared and cannot be recovered.',
      agreementSection4: '4. Other Notes',
      agreementSection4Item1: 'After deletion, the phone number, email and third-party login information bound to the original account will be released and can be used for registration or binding again;',
      agreementSection4Item2: 'Deleted accounts cannot be logged in or restored. New registrations cannot enjoy the new user benefits obtained before;',
      agreementSection4Item3: 'If you need to use GUICHAO services again, you need to register a new account.',
      agreementCheckbox: 'I have carefully read and understood all contents of the "Account Deletion Agreement", clearly know all consequences after deletion, and voluntarily apply for account deletion',
      deleteWarning: 'Warning: This action cannot be undone',
      deleteWarningDesc: 'Deleting your account will permanently delete:',
      deleteWarningItem1: 'All your personal information',
      deleteWarningItem2: 'Purchase records and subscription information',
      deleteWarningItem3: 'All account-related data',
      confirmDelete: 'Confirm Account Deletion',
      confirmDeleteDesc: 'To ensure account security, please enter your login password to continue the deletion operation.',
      loginPassword: 'Login Password',
      loginPasswordPlaceholder: 'Enter your login password',
      deleteNote: 'This action cannot be undone and will permanently delete your account and all related data.',
      deleting: 'Deleting...',
      confirmDeleteBtn: 'Confirm Delete',
      loadFailed: 'Load Failed',
      loadPurchasesFailed: 'Failed to load purchase records',
      saveFailed: 'Save Failed',
      saveSuccess: 'Save Successful',
      profileUpdated: 'Your profile has been updated',
      oldPasswordError: 'Incorrect Old Password',
      oldPasswordErrorDesc: 'The current password you entered is incorrect, please try again',
      changeSuccess: 'Change Successful',
      passwordUpdated: 'Your password has been updated',
      changeFailed: 'Change Failed',
      loggedOut: 'Logged Out',
      logoutSuccess: 'You have successfully logged out',
      logoutFailed: 'Logout Failed',
      enterPassword: 'Please Enter Password',
      enterPasswordDesc: 'For security reasons, please enter your login password',
      passwordError: 'Password Error',
      passwordErrorDesc: 'The password you entered is incorrect, please try again',
      verificationSuccess: 'Verification Successful',
      deleteRequestSubmitted: 'Your account deletion request has been submitted, please contact the administrator to complete deletion',
      verificationFailed: 'Verification Failed',
      enterContact: 'Please enter new contact information',
      emailVerificationSent: 'Verification email sent',
      checkNewEmail: 'Please check your new email inbox and click the verification link',
      codeVerificationSent: 'Verification code sent',
      checkSMS: 'Please check your SMS',
      sendFailed: 'Send Failed',
      enterCode: 'Please enter verification code',
      phoneUpdated: 'Phone Number Updated',
      phoneUpdateSuccess: 'Your phone number has been successfully updated',
      emailVerification: 'Email Verification',
      clickEmailLink: 'Please click the verification link in the email to complete email update',
      usernameMin: 'Username must be at least 2 characters',
      usernameMax: 'Username must be at most 50 characters',
      invalidURL: 'Please enter a valid URL',
      bioMax: 'Bio must be at most 500 characters',
      enterCurrentPassword: 'Please enter current password',
      passwordMin: 'Password must be at least 6 characters',
      passwordMismatch: 'Passwords do not match',
      noSubscription: 'No subscription set',
      expired: 'Expired'
    }
  }
};
