// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrpqguorttvvdcujeuss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhycHFndW9ydHR2dmRjdWpldXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDAzNTcsImV4cCI6MjA3MDgxNjM1N30.bFzjyGeiqCv2oyqIU4dN1ln6quDf2xefi1KjVI8CBJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});